### ISSUE TITLE
Logo for Button needed

### ISSUE THREAD

**Issue by ReimarBauer** [PyFilesystem/pyfilesystem2#101]
I need a logo to add on a QT button. 
Is it ok, to use this, it is extracted from the logo string of the docs. https://www.pyfilesystem.org/

![fs_logo](https://user-images.githubusercontent.com/278728/32544168-04d52f44-c478-11e7-947d-049409d34e60.png)

It will then become used in a places area, is my fs_filepicker,

![places](https://user-images.githubusercontent.com/278728/32544585-26dd7226-c479-11e7-82b3-29f949b15930.png)

Have you a better one?

**Comment by willmcgugan** [comment]
This one may work better...

https://github.com/PyFilesystem/pyfilesystem.org/blob/master/logo/favicon.png

You're welcome to use any of the resources in the [pyfilesystem.org](https://github.com/PyFilesystem/pyfilesystem.org) repos.
