### ISSUE TITLE
join or combine with a webdav url 

### ISSUE THREAD

**Issue by ReimarBauer** [PyFilesystem/pyfilesystem2#105]
Hi 
if I try to combine or join a webdav url webdav:// the second slash gets removed
print(fs.path.combine("webdav://", "something"))
webdav:/something

What is the proper solution to get webdav://something ?

**Comment by willmcgugan** [comment]
The functions in `fs.path` weren't intended fro use with FS urls. If you want to construct a FS url from parts, you can simply concatenate the strings.

Although if you need to do this, it may be an indication that you should just import the filesystem, and create it with the constructor.

If you have a use case for some kind of `fs_urlencode` function, I could be convinced to add it...

**Comment by willmcgugan** [comment]
Closing for now, but let me know if you do need a way to unparse FS urls.
