### ISSUE TITLE
Test suite should check for details/modified being a datetime

### ISSUE THREAD

**Issue by zopyx** [PyFilesystem/pyfilesystem2#106]
The webdavfs driver returns the `details/modified` date as RFC822 string instead as datetime instance. Clearly a bug in our driver. However the testsuite should check explicitly for the documented  behaviour

https://docs.pyfilesystem.org/en/latest/info.html

and check the `details/modified` property for its type in order to provide identical behaviour across all drivers.

**Comment by willmcgugan** [comment]
Agreed. That would be worth checking for.

**Comment by willmcgugan** [comment]
https://github.com/PyFilesystem/pyfilesystem2/pull/201
