### ISSUE TITLE
Maybe discard readme.md ?

### ISSUE THREAD

**Issue by althonos** [PyFilesystem/pyfilesystem2#107]
Hi Will, 
just noticed that with 86244ed you did not update `README.rst`, but then I asked myself another question: is `readme.md` really needed, since GitHub (and GitLab as well) support displaying README files in reStructuredText format ?

**Comment by willmcgugan** [comment]
Maybe. Normally I do a `make readme` which converts the `.md` to `.rst`. But I forgot to do that when I last edited the readme.

To be honest though, I don't feel that inclined to change the status quo because I prefer editing markdown. The `rst` is only required for PyPi.

**Comment by althonos** [comment]
No problem, just thought it was something I needed to ask. I tend to do all of my Python README in rst, although I agree markdown is easier to edit.
