### ISSUE TITLE
"Testing Filesystems" documentation section

### ISSUE THREAD

**Issue by qvasic** [PyFilesystem/pyfilesystem2#109]
"The simplest possible example to test a filesystem" example do not work. Is there any prerequisite, which must be known by the reader? Like some other testing module? If so, it should be mentioned in that section, I guess.

PS. I am new to Python, so I might not know something obvious. If this is the case, please excuse my ignorance.

**Comment by willmcgugan** [comment]
To test your FS object, you would do something like this...

```python
from fs.test import FSTestCases

class TestMyFS(FSTestCases):
    def make_fs(self):
        # return your FS interface
```

Simplest way to run the tests is with `nose`, which you can install with `pip`.

If you save that as `test_myfs.py` or similar, then run `nosetests -v` it will run the tests.

The naming is important, `nose` runs all the tests that start with the word `test`.

If you can't get it to work, let me know what you tried and I'll try and point you in the right direction.

I will also write up the procedure for testing in more detail at some point. Your experiences might help with that.

**Comment by qvasic** [comment]
I tried like you said, but it looks like nose does not pick up the tests...

`(env) qvasic@qzenbook:~/code/filesyst$ ls
dropboxfs.py  env  __pycache__  test_dropboxfs.py
(env) qvasic@qzenbook:~/code/filesyst$ cat test_dropboxfs.py
import dropboxfs
from fs.test import FSTestCases

class TestMyFS(FSTestCases):
    def make_fs(self):
        return dropboxfs.d
(env) qvasic@qzenbook:~/code/filesyst$ nosetests -v

----------------------------------------------------------------------
Ran 0 tests in 0.002s

OK
(env) qvasic@qzenbook:~/code/filesyst$`

**Comment by willmcgugan** [comment]
Sorry, should have mentioned FSTestCases is a mixin.

```python
import unittest

class TestMyFS(FSTestCases, unittest.TestCase):
    def make_fs(self):
```

Please see [this example](https://github.com/PyFilesystem/s3fs/blob/master/fs_s3fs/tests/test_s3fs.py)

**Comment by qvasic** [comment]
No, result is still the same :(

```
(env) qvasic@qzenbook:~/code/filesyst$ ls
dropboxfs.py  env  __pycache__  test_dropboxfs.py
(env) qvasic@qzenbook:~/code/filesyst$ cat test_dropboxfs.py
import unittest
from fs.test import FSTestCases
import dropboxfs

class TestDropBoxFS(FSTestCases, unittest.TestCase):
    def make_fs(self):
        return dropboxfs.d
(env) qvasic@qzenbook:~/code/filesyst$ nosetests -v

----------------------------------------------------------------------
Ran 0 tests in 0.002s

OK
(env) qvasic@qzenbook:~/code/filesyst$
```

**Comment by willmcgugan** [comment]
Sorry, didn't mean to be so slow to respond. Hope you managed to figure it out. This worked for me...

```
import unittest
from fs.test import FSTestCases
from fs.memoryfs import MemoryFS

class TestMemoryFS(FSTestCases, unittest.TestCase):
    def make_fs(self):
        return MemoryFS()
```

```
$ nosetests test_memory.py
...............................................................
----------------------------------------------------------------------
Ran 63 tests in 0.130s

OK

```
