### ISSUE TITLE
Add get_filesystem() method

### ISSUE THREAD

**Issue by Hong-Xiang** [PyFilesystem/pyfilesystem2#113]
fs provides a great abstraction and useful operations by multiple types of FS objects, a common usage of filesystem is performing many tasks implemented in different functions on one given FS object, like:

```
def high_level_task(directory_path):
    with OSFS(directory_path) as fs:
        low_level_task0(some_args, fs)
        with fs.opendir(sub_dir_path) as sub_fs:
            low_level_task1(some_args, sub_fs)
        low_level_task1(some_args, fs)

def low_level_task0(some_args, fs):
    ... (operations on fs)


def low_level_task1(some_args, fs):
    ... (operations on fs)
```

FS object need to be passed everywhere. But using `with` statement, it should not be a necessary requirement. An example is `variable_scope` in TensorFlow.

Thus if we has an function `get_filesystem()` to get current FS constructed by `with` statement, we can make previous code cleaner like:

```
def high_level_task(directory_path):
    with OSFS(directory_path) as fs:
        low_level_task0(some_args)
        with fs.opendir(sub_dir_path):
            low_level_task1(some_args)
        low_level_task1(some_args)

def low_level_task0(some_args):
    with fs.get_filesystem() as fs:
        ... (operations on fs)

def low_level_task1(some_args):
    with fs.get_filesystem() as fs:
        ... (operations on fs)
```

Further more following functionality may be useful:
 `get_filesystem()` returns default file system when no file system is constructed 
 `get_filesystem(name:str)` returns some other FS object by its name

**Comment by willmcgugan** [comment]
I think this is something best left to the application developer. There's no one answer for how and when it should be configured, how to manage the lifetime of the filesystem(s), or how concurrency should be handled.

If you need such a system, then it shouldn't be too hard to implement according to your requirements. But I can't see it being generic enough to go in to the core library...
