### ISSUE TITLE
Subfolders in MultiFS (Subfolders=False)

### ISSUE THREAD

**Issue by merlink01** [PyFilesystem/pyfilesystem2#118]
I need a modification of MultiFS to show the contents of different Filesystems in a subfolder defined by "name" in add_fs.

For example like:
theme_fs = MultiFS(subfolders=False)
theme_fs.add_fs('mytemplates', OSFS('templates'))
theme_fs.add_fs('mytheme', OSFS('theme'))
theme_fs.listdir('/')
["mytemplates","mytheme"]

Is it possible to implement this in MultiFS?

I can do this, but I think you are much faster than me ;-)

I can also create a completely new FS if it's not fitting in the structure of MultiFS.

Thank you.

**Comment by althonos** [comment]
What you want is using a [MountFS](http://pyfilesystem2.readthedocs.io/en/latest/reference/mountfs.html) I guess :smile:

**Comment by merlink01** [comment]
Oha, was I so blind?

I'll Test, Thank you.
