### ISSUE TITLE
[SFTP] Support sftp again

### ISSUE THREAD

**Issue by maxgrenderjones** [PyFilesystem/pyfilesystem2#12]
My main use of pyfilesystem was to access SFTP filesystems, but version 2 seems to have launched without that support (fair enough, it's complicated, and probably requires adding paramiko as an optional dependency). That said, it would be great to bring it back again so that I can upgrade.

**Comment by willmcgugan** [comment]
Yeah, it will eventually. As an external package. Stay tuned.

**Comment by chris-hailstorm** [comment]
+1

**Comment by quinot** [comment]
I see this has been almost a year ago. Has the external package to support SFTP been released?

**Comment by willmcgugan** [comment]
You may be interested in [fs.sshfs](https://github.com/althonos/fs.sshfs)

**Comment by quinot** [comment]
Thanks @willmcgugan, works like a charm!
