### ISSUE TITLE
Add support for macOS and Windows  CI

### ISSUE THREAD

**Issue by pombredanne** [PyFilesystem/pyfilesystem2#122]
For macOS, you need to contact Travis support by email to ask them to enable macOS, then setup a matrix in .travils.yml

For Windows, setting up appveyor is a good way.

**Comment by willmcgugan** [comment]
Half there. Got Windows in appveyor now.

**Comment by willmcgugan** [comment]
Giving up osx in travis. According to their docs "Python builds are not available on the macOS environment."

I develop on OSX, so at least I can run tests manually.
