### ISSUE TITLE
Drop support for older Python 3 versions

### ISSUE THREAD

**Issue by pombredanne** [PyFilesystem/pyfilesystem2#123]
IMHO it does not make sense to support any version of Python 3 before 3.5. The actual usage of 3.3 and 3.4 is at best confidential.

**Comment by willmcgugan** [comment]
As long as its not overly problematic to maintain support for older versions of Python3 I would be reluctant to drop them. I could be persuaded other wise if there were some hard statistics I could look at...

**Comment by pombredanne** [comment]
That's not a problem for now I guess. But if this comes about, then dropping them only makes sense IMHO
