### ISSUE TITLE
New Filesystem youtubefs

### ISSUE THREAD

**Issue by merlink01** [PyFilesystem/pyfilesystem2#128]
Hi devs,

I want to release my first Filesystem now.

Here is the code: https://github.com/merlink01/fs.youtube

It would be nice if you could have a look on it, if everything is fine before I release it.

Thank you.

**Comment by willmcgugan** [comment]
Thanks, I'll have a look!

**Comment by willmcgugan** [comment]
Sorry for the delay. It's quite an interesting use case for PyFilesystem!

Implementation looks good, but I'm guessing its not a generic filesystem with full write-access? Without running the full test-suite it is hard to be certain if conforms to the spec. Perhaps there should be a test-suite for read-only filesystems.

You might want to call your info namespace `youtube`, I think the name `media` is too generic.

Would you like me to add it to the wiki?

**Comment by merlink01** [comment]
Hi @willmcgugan,

thank you for having a look.

Yes a test-suite for read only filesystems would be really great.

I can only see one problem here:
I can't generate testfiles on a filesystem that is not owned by me.
Thatswhy I used the first file found from listdir and can't test for encoding of textdata or something like that.

The namespace 'media' is chosen to get an entrypoint for a bigger project I want to build on top of these Media Filesystems.
So if I have a filesystem , I can get 'media' Namespace and determine the type ['video','audio','picture'].
If I shoud choose 'youtube' I need additionally informations how to determine the namespace.
Do you have a better solution for this?

Yes, that would see this project at your wiki page.

One small question:
I need a filewrapper based on a HTML download with seeking capapilities if the Server allows this.
This is already implemented inside of the YoutubeFS.
Because I will use this code inside multiple projects (typical platforms: Youtube, Twitch, Vimeo,...) it would be nice to have a HTTPFileWrapper implemented inside of Pyfilesystem.

Do you think that is the right place for this?
 
Thank you.

**Comment by willmcgugan** [comment]
Added it to the [wiki](https://www.pyfilesystem.org/search?q=youtube). Let me now if you want to change any of the wording.

> I can only see one problem here:
> I can't generate testfiles on a filesystem that is not owned by me.
> Thatswhy I used the first file found from listdir and can't test for encoding of textdata or something like that.

Tricky one, if we can't manipulate the contents , but there might be a subset of tests we can come up which runs through the filesystem and checks for conformance. It could `opendir` all the directories, read all the files etc.

> The namespace 'media' is chosen to get an entrypoint for a bigger project I want to build on top of these Media Filesystems.

Ah okay, so there may be more filesystems that export the same info namespace? I agree that 'media' would be a good name in that case. But I would prefer to have a standard defined for such a generic term, so that it could potentially be used by others.

How about we create a convention of adopting a *vendor prefix*, so you could call your namespace `"merlink.media"` for the time being. Chances are we will just make it an official part of the spec at some point, then you can drop the vendor prefix. @althonos, what do you think?

> Because I will use this code inside multiple projects (typical platforms: Youtube, Twitch, Vimeo,...) it would be nice to have a HTTPFileWrapper implemented inside of Pyfilesystem.

That sounds like a useful thing. I'd probably leave it out of Pyfilesystem if it's not used in the core library itself. I'd suggest either keeping a copy in each of your filesystems, or factor it out to an independent module on pypi.

**Comment by althonos** [comment]
Hi @willmcgugan, sorry for not being extremely responsive lately, exam season is not over yet.
    
>> So if I have a filesystem , I can get 'media' Namespace and determine the type     ['video','audio','picture'] the title+thumbnail to show this in the Main application.

I wanted to submit a `mime` namespace, with file mimetypes, but I was unsure of how to proceed, and I didn't continue exploring the idea. This could be the solution to know the content type of the file through a single `getinfo` call.

> How about we create a convention of adopting a vendor prefix, so you could call your namespace "merlink.media" for the time being.

Sounds good to me, just to give some time to check the acceptance of the namespace, and also check how generic it is, and if it could benefit to some other FS implementations. Only issue is that if we end up accepting `merlink.media` as the official `media` namespace, all code will have to be changed. Maybe another possibility would be to add a `_vendor` key to the returned info namespace, and have code proceed only on `info.get("media", "_vendor") == "merlink"`.

@merlink01 : 
>> Because I will use this code inside multiple projects (typical platforms: Youtube, Twitch, Vimeo,...) it would be nice to have a HTTPFileWrapper implemented inside of Pyfilesystem.

I agree with Will, this is something too specific for the core `fs` module, providing there's no HTTP filesystem in it. But if you need help with the implementation, I could give you a hand (I've become quite accustomed to writing buffered stream readers lately).

Also, @willmcgugan, although this may be a tad too specific, I could be interesting to provide several file wrappers with different buffering logic to ease the emulation of seekable files in filesystems where there are none. I've got a few other ideas, but most of them are kept in a `TODO` for now :smile:

**Comment by willmcgugan** [comment]
> Hi @willmcgugan, sorry for not being extremely responsive lately, exam season is not over yet.

No worries. Don't let me distract you from studying.

> I wanted to submit a mime namespace, with file mimetypes, but I was unsure of how to proceed, and I didn't continue exploring the idea. This could be the solution to know the content type of the file through a single getinfo call.

:+1:

> Only issue is that if we end up accepting merlink.media as the official media namespace, all code will have to be changed.

Not necessarily. It's relatively easy to continue to support both. If @merlink01 ends up defining the standard, then `media` and `merlink.media` could just be aliases for each another.

> Also, @willmcgugan, although this may be a tad too specific, I could be interesting to provide several file wrappers with different buffering logic to ease the emulation of seekable files in filesystems where there are none. I've got a few other ideas, but most of them are kept in a TODO for now 😄

That does sound worthwhile. Its a tricky thing to get right, and a wheel that doesn't need re-inventing.

Good luck with the exams!

**Comment by willmcgugan** [comment]
@merlink01 Keep us updated with your progress!

**Comment by merlink01** [comment]
Now online on pypi:

https://pypi.python.org/pypi/fs.youtube

**Comment by media-proxy** [comment]
@willmcgugan, I moved the repo on github.

It would be nice to change the Link of your filesystem list to pypi or to https://github.com/media-proxy/fs.youtube

**Comment by willmcgugan** [comment]
Done!

**Comment by merlink01** [comment]
Thank you :-)

**Comment by merlink01** [comment]
Thank you :-)

**Comment by media-proxy** [comment]
@willmcgugan , here the next Project:

https://github.com/media-proxy/fs.dlna

A Filesystem for accessing DLNA ContentDirectory Server :-)

**Comment by willmcgugan** [comment]
Cool. Added to wiki.
