### ISSUE TITLE
Command line utilities?

### ISSUE THREAD

**Issue by chris-hailstorm** [PyFilesystem/pyfilesystem2#13]
Does version 2 support fscat, fsls, fstree and so on?

I upgraded my prior version and these appear missing.

Thanks

**Comment by willmcgugan** [comment]
Not yet. It will eventually. If you need them you might want to stick with fs2 for now.

**Comment by lurch** [comment]
Is this still on the TODO list?

**Comment by willmcgugan** [comment]
Potentially. It would be nice, but I can't see myself finding the time in the near future.

**Comment by pythonwood** [comment]
I want it, will command-line come back ?

**Comment by willmcgugan** [comment]
Unlikely, unless I get sponsorship, I’m afraid.

**Comment by pythonwood** [comment]
maybe a pull request is required. 
so, let `s try to push something.

**Comment by pythonwood** [comment]
I will try click command group. [](https://github.com/pallets/click) 

like:
`  pyfs ls --url webdav://user:pass@127.0.0.1/webdav/subdir/`
