### ISSUE TITLE
problem with symbolic links

### ISSUE THREAD

**Issue by ReimarBauer** [PyFilesystem/pyfilesystem2#131]
Linux Link files (ln -s) currently are not looked up as files on linux by _getinfo_,
fs directly tries to resolve the linked destination. If the destination not exists
fs.errors.ResourceNotFound is triggered.
I am not sure about if that is a failure. But  anyway I would like to show
 an information that we have a link file there which links to some item.  

Testcase
```
touch /tmp/mytest
mkdir ~/TEST
cd ~/TEST
ln -s /tmp/mytest
rm /tmp/mytest
```
```
import fs
data = fs.open_fs("~/TEST")
items = data.listdir(u".")
for _item in items:
     try:
         info = data.getinfo(_item, namespaces=[u'details', u'access', u'stat'])
     except fs.errors.ResourceNotFound:
         print(_item)
```

**Comment by willmcgugan** [comment]
You should be able to get the `lstat` namespace for a symlink. But looking at the code for OSFS, I suspect it might throw a ResourceNotFound error if the link is broken. That may be a bug.

**Comment by ReimarBauer** [comment]
or also `link`, seen just in the documentation. But in case of the not existing file, I get first the exception.
