### ISSUE TITLE
Question about TARFS

### ISSUE THREAD

**Issue by ReimarBauer** [PyFilesystem/pyfilesystem2#133]
Is it possible to directly access a directory in a tar file? Or how can I access a directory in a container by path?

I know the methods for listing, these also work similar to an osfs directory

Tar Example:
```
u = "tar:///user/tmp/TAR/example.tar"
 _fs = fs.open_fs(u)
_fs.listdir("bar/foo")
```
osfs example:
```
u = "~/tmp/TAR"
_fs = fs.open_fs(u)
_fs.listdir("bar/foo")
```

Now the difference on opening. 

On osfs I can directly open the foo directory.

```
u = "~/tmp/TAR/bar/foo"
_fs = fs.open_fs(u)
_fs.listdir("")
```
Is it planned to have a similar functionality, for containers?
 e.g.:
```
u = "tar:///user/tmp/TAR/example.tar/bar/foo"
_fs = fs.open_fs(u)
```

**Comment by willmcgugan** [comment]
```
u = "tar:///user/tmp/TAR/example.tar/bar/foo"
_fs = fs.open_fs(u)
```
The problem with this example is that there is no way to know that you aren't attempting to open a tar file called `foo`.

FS URLs do have a syntax that allows you to specify an additional path with a `!` as a separator. Here's an example:

```
from fs import opener
u = "tar:///user/tmp/TAR/example.tar!/bar/foo"
tar_fs, tar_path = opener.open(u)
```

But that doesn't actually open the directory for you. You would have to call `tar_fs.opendir(tar_path)` to open the directory.

**Comment by ReimarBauer** [comment]
ok great, that's all I need, I just return the path in that syntax.
