### ISSUE TITLE
Question -- implementing file systems in v1 and v2

### ISSUE THREAD

**Issue by chris-hailstorm** [PyFilesystem/pyfilesystem2#14]
Is there a way to implement a file system that applies in both v1 and v2?

I'm contemplating building a file system module and would appreciate any advice relating to an efficient way to make that usable in both generations of pyfilesystem.

Thanks

**Comment by willmcgugan** [comment]
I'm not sure that would be feasible to be honest. I can't think of any way in which you could write a class that satisfies both interfaces.

You could implement both versions. But I suspect the best solution would be to pick which version has the ecosystem you need. If you have any requirements for tools and other implementations then that would probably be fs1 for now.
