### ISSUE TITLE
AttributeError ftplib in storbinary

### ISSUE THREAD

**Issue by geoffjukes** [PyFilesystem/pyfilesystem2#141]
Hi,

I'm using `fs` version 2.0.18 and I'm having issues trying to send files via FTP. Nothing fancy, just copy a directory to an FTP server (I have tried 3 different FTP servers, all fail).

The same code works for SFTP (using fs.sshfs) and for disk-to disk copies. I have tried `copy_fs`, `move_fs` and `mirror`. All throw the same error:

```
AttributeError: __exit__
  File "nameko/containers.py", line 388, in _run_worker
    result = method(*worker_ctx.args, **worker_ctx.kwargs)
  File "service/deliver.py", line 29, in event
    status, message = getattr(self, package['method'])(**package['settings'], dry_run=dry_run)
  File "service/deliver.py", line 82, in copy
    storage.copy_fs(temp_fs, target_fs)
  File "fs/copy.py", line 31, in copy_fs
    walker=walker, on_copy=on_copy)
  File "fs/copy.py", line 242, in copy_dir
    dst_path
  File "fs/copy.py", line 138, in copy_file_internal
    dst_fs.setbinfile(dst_path, read_file)
  File "fs/wrapfs.py", line 374, in setbinfile
    _fs.setbinfile(_path, file)
  File "fs/ftpfs.py", line 664, in setbinfile
    file
  File "python3.5/ftplib.py", line 503, in storbinary
    with self.transfercmd(cmd, rest) as conn:
```
I'm connecting like this:
```
                with storage.open(target, create=True) as target_fs:
                    storage.move_fs(source_fs, target_fs)

```
and it writes a 0-byte file.

**Comment by geoffjukes** [comment]
I'm using Nameko (https://github.com/nameko/nameko) which uses Eventlet. Could that be the issue?

**Comment by geoffjukes** [comment]
Looks like it probably is...
https://github.com/eventlet/eventlet/issues/429

**Comment by willmcgugan** [comment]
Thanks for investigating.

**Comment by geoffjukes** [comment]
No problem.
This issue was fixed in Eventlet 0.22. Unfortunately for me, Nameko is pinned to 0.21 until they can fix some compatibility issues.

**Comment by geoffjukes** [comment]
For anyone else stuck on Eventlet 0.21, you can monkey patch GreenSocket:

```
############################
# Monkey patch Eventlet GreenThread to add context manager
# This is not required in eventlet 0.22 and up
from eventlet.greenio.base import GreenSocket
def add_enter(self):
    return self
def add_exit(self, *args):
    self.close()
GreenSocket.__enter__ = add_enter
GreenSocket.__exit__ = add_exit
######################
```
Just do that anywhere in the module/package that makes use of ftplib

**Comment by geoffjukes** [comment]
As an addendum - make sure you also import the 'greened' ftplib 👍 
```
from eventlet.green import ftplib
```
