### ISSUE TITLE
userconf:// on linux -> root path does not exist

### ISSUE THREAD

**Issue by ReimarBauer** [PyFilesystem/pyfilesystem2#142]
Hi

I tried to use `open_fs('userconf://appname:author:version').`
I always get:
`fs.errors.CreateFailed: root path does not exist`

What did I wrong?

**Comment by althonos** [comment]
@ReimarBauer: By default, the keyword argument `create` of the `open_fs` function is set to `False`. This means it won't create the filesystem actual directory if it doesn't exist on your local filesystem.

To create the directory if it does not exist, use:
```python
>>> fs.open_fs("userconf://appname:author:version", create=True)
```
