### ISSUE TITLE
fs.path.abspath and protocolls

### ISSUE THREAD

**Issue by ReimarBauer** [PyFilesystem/pyfilesystem2#145]
It behaves as it is documented

Since FS objects have no concept of a current directory, this simply adds a leading / character if the path doesn’t already have one.

But

not sure if that is intented to call it with a protocoll url

```
>>> fs.path.abspath(u'webdav://some.dav.de')
u'/webdav://some.dav.de'
```
However if it  finds a fs protocoll it should not do that.

**Comment by willmcgugan** [comment]
I'm afraid there is no way to know for certain if a string contains a FS URL or not. Your example could very well be a path.
