### ISSUE TITLE
join path and protocol

### ISSUE THREAD

**Issue by ReimarBauer** [PyFilesystem/pyfilesystem2#146]
How can I join protocols and pathes?

fs.path.join removes the second protocol slash.

```
fs.path.join(u'webdav://some.dav.de', u'somepath')
u'webdav:/some.dav.de/somepath'
```

**Comment by willmcgugan** [comment]
You will need to do the string manipulation manually. We could use FS unparse functionality in the library to help with such things.

But bear in mind, the components of the fs URL may have different meanings for each filesystem.

**Comment by ReimarBauer** [comment]
current solution, forcedir :)

filename = u"{}{}{}".format(fs.path.forcedir(u'webdav://some.dav.de'), fs.path.forcedir(u'dirname'), u'filename.png')
