### ISSUE TITLE
Add support for Google Cloud Storage.

### ISSUE THREAD

**Issue by tweeter0830** [PyFilesystem/pyfilesystem2#147]
GCS would be a great addition to pyfs2.

**Comment by geoffjukes** [comment]
@tweeter0830 in the meantime, you can use S3FS and enable 'Interoperability Mode' in your Google CLoud account: https://cloud.google.com/storage/docs/interoperability
You can set the GCS request endpoint as a URL parameter in S3FS
I've not tested it yet, but I set this up yesterday (testing today, hopefully) but on-paper it should work.

**Comment by willmcgugan** [comment]
Agreed. It would have to wait until someone has the time to implement it. Unless it was sponsored.

In the meantime, @geoffjukes 's suggestion looks great.

**Comment by geoffjukes** [comment]
@willmcgugan This solution works well for small files. However, if you start working with anything larger than 8MB, boto3 will automatically switch to Multipart uploads - which Google does not support.

Reference: http://boto3.readthedocs.io/en/latest/_modules/boto3/s3/transfer.html
