### ISSUE TITLE
fs.path.join breaks URLs

### ISSUE THREAD

**Issue by rotu** [PyFilesystem/pyfilesystem2#151]
`fs.path.join` coalesces slashes, which breaks protocol declarations if passed a URL. I'm not sure if it _should_ be URL-aware, but it should probably be consistent with `fs.path.combine`:

```
fs.path.join('smb://user:pass@host/svc','path')
'smb:/user:pass@host/svc/path'
# open_fs will treat this as an OS path

fs.path.combine('smb://user:pass@host/svc','path')
'smb://user:pass@host/svc/path'
# open_fs will treat this as a SMB path
```

**Comment by willmcgugan** [comment]
`fs.path.join` (and the fs.path module in general)  is purely for [FS paths](https://docs.pyfilesystem.org/en/latest/concepts.html#paths).
