### ISSUE TITLE
On Windows, `open_fs('C:')` opens the wrong directory

### ISSUE THREAD

**Issue by rotu** [PyFilesystem/pyfilesystem2#152]
On Windows, `open_fs('C:')` is expected to open the root directory of the drive mapped to 'C'. Instead, it opens the working directory. This does not happen for other disks.

```
>>> fs.open_fs('C:')
OSFS('C:\\Python36')
>>> fs.open_fs('C:/')
OSFS('C:\\')
>>> fs.open_fs('D:')
OSFS('D:\\')
>>> fs.open_fs('D:/')
OSFS('D:\\')
```

**Comment by willmcgugan** [comment]
Should be fixed in 2.0.27.
