### ISSUE TITLE
Parallel file copying

### ISSUE THREAD

**Issue by geoffjukes** [PyFilesystem/pyfilesystem2#158]
Hi,

I’m using the `mirror` function to copy a large number of files between file systems. I have an abundance of bandwidth, and I’d like to try and optimize the copy process.

My thought is to get a list of files, then use `concurrent.futures.ThreadPoolExecutor` to manage multiple `fs.copy.copy_file` processes. But reading through the code, I suspect I should use `fs.copy.copy_file_internal` to avoid the `lock()`.

My question is, is there an alternative/better way to parallelise the copy processes?

Thanks in advance,

Geoff

**Comment by willmcgugan** [comment]
I'm afraid that copy_file_internal wouldn't help you there. Some of the methods it calls will do a lock.

You can avoid locking by doing a simply file copy with two open files. That should play nicely with a thread pool.

The original filesystem had a [method](https://github.com/PyFilesystem/pyfilesystem/blob/master/fs/utils.py#L80) which did just that. It might be worth porting that over, but in the meantime that might work for you.

**Comment by althonos** [comment]
The simplest is probably to `openbin` the source and destination, and use `fs.tools.copy_file_data` to copy files. It shouldn't use any lock (this is internally used by `getfile` after locking).

**Comment by Joeasaurus** [comment]
I am looking for a way to do this nicely as well. It's a shame that manual copy_file_data calls are necessary. I was thinking to just open multiple filesystem objects and move different subdirectories in each one. Or will the locks get in the way across instantiations?

**Comment by willmcgugan** [comment]
Locks are per-instanace, so that should work.

I wouldn't mind tackling a more parallel copier. There is some code one of the command line apps in the original Pyfilesytem which did just that. Not sure when I'll find the time to implement it I'm afraid.

**Comment by Joeasaurus** [comment]
@willmcgugan sub-filesystems (`fs.opendir()`) will be locked with the parent, or they are a separate instantiation too?

**Comment by willmcgugan** [comment]
A SubFS will use the parent's lock.

**Comment by willmcgugan** [comment]
@geoffjukes @Joeasaurus I've [started work](https://github.com/pyfilesystem/pyfilesystem2/tree/parallel-copy) on this.

I've added a `workers` parameter to `mirror`. If this is non-zero it will do that many file copies in parallel. 

Still a work in progress, but if you want to give it a try, you can `pip install fs==2.0.25a0`.

There are still some interface concerns to work out. Currently any errors in the workers will not be reported. When I figure this out, I'll extend it to `fs.copy` and possibly `fs.move`.

Would appreciate early feedback, and it would be great if you could compare performance with workers=0 against workers=4 (for example).

**Comment by willmcgugan** [comment]
https://github.com/PyFilesystem/pyfilesystem2/pull/188

**Comment by willmcgugan** [comment]
`pip install fs==2.0.25a1` for the latest.

**Comment by geoffjukes** [comment]
@willmcgugan this is fantastic news, thank you! I have been away for a bit, but I'm catching up now. I should have the new code implemented tomorrow, and I'll let you know how it goes.

**Comment by willmcgugan** [comment]
That's in 2.0.25 (just released).

**Comment by geoffjukes** [comment]
@willmcgugan I have to say, this was a fantastic addition. 

My S3 file upload times were reduced by over 75% in most cases, and integrating it into my existing code means adding a single line (to specify the worker count). Genius.

**Comment by willmcgugan** [comment]
Marvellous :-) Does disabling strict mode help at all?

**Comment by geoffjukes** [comment]
@willmcgugan I didn't realize there was such an option :)

With a simple `?strict=0` change to the FS URL, I just shaved off another second :) Thanks for the hint!
