### ISSUE TITLE
Relax the six==1.10.0 requirement

### ISSUE THREAD

**Issue by limx0** [PyFilesystem/pyfilesystem2#159]
Is it possible to update six to >=1.10.0 ? Six has been updated to 1.11.0, but it would be nice to relax this assumption as pyfilesystem is likely to be used a library in other applications which may have a dependency clash. 

Actually in an ideal world we could potentially make this six > 1.0.0?

**Comment by althonos** [comment]
@limx0: 
> Is it possible to update six to >=1.10.0 ?

absolutely ! The `setuptools` requirements defined in `setup.py` actually enforce six `>=1.10.0, <2`. The `requirements.txt` file is actually not enforcing anything (maybe it could be removed ?)

> Actually in an ideal world we could potentially make this six > 1.0.0?

* `six.add_metaclass` was added in six `1.4.0`
* `six.python_2_unicode_compatible` was added in six `1.9.0`
* tests seem to work ok with six `1.9.0` installed

so we could probably go as far as `six ~=1.9`, but not below.

**Comment by limx0** [comment]
Thanks @althonos, that's understandable.  

I'm having some issues in environments where I have six==1.11.0 installed and then I try and add pyfs. I will investigate further and pinpoint the issue.

**Comment by althonos** [comment]
No problem ! The `~=` constraint is quite new, and has a different behaviour depending on the detailed version (`~=1.2` means `>=1.2, <2`, while `~=1.2.0` means `>=1.2.0, <1.3`, I find it quite confusing since it does not completely follow semver).
