### ISSUE TITLE
asyncio support

### ISSUE THREAD

**Issue by brycedrennan** [PyFilesystem/pyfilesystem2#163]
Would great to have filesystems compatible with asyncio!

**Comment by willmcgugan** [comment]
Agreed. Although it wouldn't be possible to take the current filesystems and make them work on asyncio. It might have to be a side project. In the meantime, you could run fs code in an executor.

**Comment by willmcgugan** [comment]
@brycedrennan I guess the major obstacle is that you can't have an async API that works just as well synchronously. It would essentially be a different interface. And PyFilesystem uses modules in the stdlib that aren't async and would need a new implementation; FTPFS for instance. Even OSFS would need a new implementation, as it is technically blocking.

Would be interested in any ideas you have ideas in this area.

**Comment by brycedrennan** [comment]
Thanks for the quick response. yeah that's what I expected.  Well I'm gonna go for it and see how it goes.  We have an internal existing library that's doing a lot of the same things as pyfilesystem, but works with asyncio.  Stinks to have that duplication of work.

My naive approach is going to be to make `AsyncFS`, which will have everything be async methods.  After that's working for S3, and osfs, I'll subclass that into `SyncFS`.  `SyncFS` will just wrap all the async methods and convert them to blocking methods.

Even if I get it working I imagine there would be a lot more to do regarding design and testing before anyone would consider it a good idea to combine with pyfilesystem.  I'll let you know how it goes though.

**Comment by willmcgugan** [comment]
I would be very interest in seeing how you get on with that!

**Comment by brycedrennan** [comment]
Well as would probably be expected, it was much more complicated than anticipated.  PyFilesystem handles so much more than I need.  So I'm back to a much more restricted but asyncio compatible library.  

Big fan of this library though!

**Comment by zviri** [comment]
Has there been any progress on this @willmcgugan? I'm having the same kind of thoughts as Bryce had 3 years ago. I love the *PyFilesystem* abstraction, but I have more and more use cases for the *async* case and I keep coming up with ad-hoc abstractions and it is becoming a PITA.

**Comment by willmcgugan** [comment]
Afraid not. I don't have enough bandwidth to tackle this. And I suspect the other maintainers don't either. It's no small job!
