### ISSUE TITLE
os.path.exists equivalent

### ISSUE THREAD

**Issue by geoffjukes** [PyFilesystem/pyfilesystem2#165]
Hi,

I have a file URL, and want to copy it if it exists, or execute a function if it does not. So 'normally' I would:

```
src = '/path/to/file.ext'
dst = '/new/path/to/file.ext'
if os.path.exists(src):
  shutil.copy(src, dst)
else:
  make_file_thing(src, dst)
```

What would be the equivalent of `os.path.exists` in PyFilesystem2?

Many thanks,

Geoff

**Comment by althonos** [comment]
All filesystems implement the `exists` method: https://docs.pyfilesystem.org/en/latest/reference/base.html#fs.base.FS.exists

**Comment by geoffjukes** [comment]
Thank you @althonos. I did see that, but I wasn’t sure on it’s usage. Would it be something like `fs.open_fs(fs_url).exists(‘file.ext’)`?

**Comment by althonos** [comment]
Indeed, although if you check multiple times you may want to keep the filesystem open, e.g.:
```
with fs.open_fs("/") as myfs:
   src = '/path/to/file.ext'
   dst = '/new/path/to/file.ext'
   if fs.exists(src):
      fs.copy(src, dst)
   else:
      make_file_thing(fs, src, dst)
```
