### ISSUE TITLE
`create` option not honored in `fs.ftpfs`

### ISSUE THREAD

**Issue by geoffjukes** [PyFilesystem/pyfilesystem2#169]
Hi,

The `create` option has no effect when opening a filesystem. It looks like it was never implemented - [same (now fixed) issue as fs.sshfs?](https://github.com/althonos/fs.sshfs/issues/10)

I had a kludge in place from when I reported the `fs.sshfs` issue, and forgot that I had extended it to `fs.ftpfs`. I just refactored my openers (now I have a better unsderstanding of the PyFilesystem2 API) and I dropped that kludge :-/

Kind regards,

Geoff

**Comment by willmcgugan** [comment]
Thanks for the PR.
