### ISSUE TITLE
i miss 'expose' functionality for fuse, sftp

### ISSUE THREAD

**Issue by alekibango** [PyFilesystem/pyfilesystem2#17]
Hi,
 i would like to write my custom filesystem, and i need to expose it over fuse,
sftp (maybe even ftps).  Are you planning to add those? 

i really miss 'expose' directory like the older version of this project had.

**Comment by willmcgugan** [comment]
Hi,

It will eventually be a separate package. So you can do `pip install fs.expose`.

**Comment by majidaldo** [comment]
is there any progress on this?

**Comment by earonesty** [comment]
basically, pyfilesystem2 is useless without it.   pyfilesystem is the thing.

**Comment by wgaylord** [comment]
@Liryna Not sure if you still do stuff with pyfs but if you could see how hard it would be to get dokany working here I would be thankful.

**Comment by Liryna** [comment]
@wgaylord I do not know pyfs2 😢 I can be guided, I would do the integration for dokan for pyfs2

**Comment by merlink01** [comment]
@Liryna got your code for dokan running on pyfilesystem 2.
https://github.com/PyFilesystem/pyfilesystem2/issues/115
