### ISSUE TITLE
Add Conda install to docs

### ISSUE THREAD

**Issue by martindurant** [PyFilesystem/pyfilesystem2#174]
This would greatly increase the appeal and adoption of pyfilesystem.
I recommend using conda-forge for the job.

**Comment by willmcgugan** [comment]
It's already on Conda.

https://github.com/conda-forge/fs-feedstock

**Comment by martindurant** [comment]
My apologies. It should be stated in https://docs.pyfilesystem.org/en/latest/introduction.html#installing

**Comment by willmcgugan** [comment]
It should, yeah. To be honest, I've never used Conda. Would be happy to accept a PR if you want to add that to the docs.
