### ISSUE TITLE
How to modify Info attributes

### ISSUE THREAD

**Issue by xandfury** [PyFilesystem/pyfilesystem2#178]
Hi there. Thanks for `pyfilesystem2`! 

We at [Conpot](https://github.com/mushorg/conpot/) are trying to create an effective sandbox system that could handle malware uploads. For the same, I need to fake changes in file owners/permissions etc. Wondering if that is possible using `fs`

For example:
```python
>>> test = tempfs.TempFS('')
>>> test.listdir('.')
[]
>>> test.settext('README.md', "Tetris clone")
>>> test.listdir('/')
['README.md']
>>> test.getinfo('./README.md', namespaces=['access']).get('access', 'user')
'test_user'
```
Now I want to change the `owner` of `README.md` file. [I read the docs](https://docs.pyfilesystem.org/en/latest/reference/base.html#fs.base.FS.setinfo) and this is what I have tried so far:

```python
>>> # trying to change the file owner to 'conpot'
>>> change_user = {'access': {'permissions': ['g_r', 'g_w', 'o_r', 'u_r', 'u_w'], 'uid': 1000, 'gid': 1000, 'group': 'conpot', 'user': 'conpot'}, 'basic': {'is_dir': False, 'name': 'README.md'}}
>>> test.setinfo('./README.md', change_user)
>>> # this doesn't work however.
>>> test.getinfo('./README.md', namespaces=['access']).get('access', 'user')
'test_user'


>>> # I have also tried
>>> resource_info = test.getinfo('.', namespaces=['details', 'access'])
>>> resource_info.user = 'conpot'
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: can't set attribute
```
How do I go about modifying file owner?

Navigating the code, I did come accross [this](https://github.com/PyFilesystem/pyfilesystem2/blob/95a2f5ae0ae42dfe9f0b7acb2ced58aa234fc0ae/fs/info.py#L133). Apparently there are `writeable` namespaces. Not sure if I can modify attributes though.

**Comment by willmcgugan** [comment]
> For the same, I need to fake changes in file owners/permissions etc.

Not sure what you mean re fake changes? Do you want PyFilesystem to report a different user than what the filesystem reports?

Changing the file owner for real isn't supported. Although it could be -- you might want to file an issue for that. In the meantime you can get a syspath and use `os.chown`.

**Comment by xandfury** [comment]
Thanks for reply Will :-)
> Not sure what you mean re fake changes? Do you want PyFilesystem to report a different user than what the filesystem reports?

Yes. Exactly. Since I am trying to sandbox, I won't be running any system calls (or atleast I don't want to).  I can afford these system calls only once - when the filesytem is being built. After that I maybe need to build and store state/context of each file.

I was thinking if it was possible to attach an `Info` instance to a subclass of OSFS. So instead of calling `os.*` calls, I can just edit those values. Suggestions?

**Comment by willmcgugan** [comment]
Have a look at `WrapFS` as an alternative to OSFS. You could customize `getinfo` there, but since its a proxy and not a subclass you could apply it to any filesystem.

**Comment by xandfury** [comment]
One final question. If I subclass `WrapFS` to create my `AbstractFS`(say). Then when I do `opendir`, the `SubFS` instance ***does not contain*** the attributes that I defined in `AbstractFS`.

```python
hello
SubFS(AbstractFS(OSFS('.')), '/ftp')
>>> hello.cwd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'SubFS' object has no attribute 'cwd'
```
How can I go about customizing this?

**Comment by willmcgugan** [comment]
The `SubFS` is a new object, so it won't have the same attributes as the class it wraps. If you need to modify your AbstractFS after it has been constructed, you will need to keep a reference to it.

**Comment by xandfury** [comment]
So if I want to add attributes to every `SubFS` instance I should subclass it as well, passing it as [`factory`](http://pyfilesystem2.readthedocs.io/en/latest/reference/base.html#fs.base.FS.opendir) parameter in `opendir` of my `AbstractFS`?

**Comment by xandfury** [comment]
Yup. Thanks for all the help :-)
