### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by geoffjukes** [PyFilesystem/pyfilesystem2#179]
Hi @willmcgugan 

Might you have time to cut a release? The Timeout option would be useful to me :)

**Comment by willmcgugan** [comment]
I did a release a few days ago. Should all be up to date. Maybe I should be announcing releases somewhere?

**Comment by willmcgugan** [comment]
Sorry, wrong project. Yes, I'll do a release shortly.

**Comment by willmcgugan** [comment]
v2.0.24 in Pypi!
