### ISSUE TITLE
[Documentation] FS.makedir has no return type

### ISSUE THREAD

**Issue by althonos** [PyFilesystem/pyfilesystem2#18]
Hi there !

After reading the documentation, I noticed that `FS.makedir` was not listed as returning anything, although your tests suggest that it shoudl return a `SubFS` rerooted to the path of said directory (and that builtin filesystems behave in that same way).

**Comment by willmcgugan** [comment]
Good spot, thanks.

**Comment by althonos** [comment]
Also, other question (I won't be opening an issue for every question, that'll get annoying): shouldn't `FS.makedir` raise `DestinationExists` instead of `DirectoryExists` if one of the components of the path is a file ?

**Comment by willmcgugan** [comment]
Can you give me some example code? `OSFS` raises `DirectoryExpected`.

Standardising exceptions has been tricky, so I wouldn't be surprised if there were some inconsistencies.

**Comment by althonos** [comment]
Well, my bad, the `DirectoryExpected` is actually raised when one of the elements of the path is a file, but `DirectoryExists` is raised when the path to the new directory itself is a file.

**Comment by althonos** [comment]
On a side note: I started to find some inconsistencies in the documentation (actually, between the behaviour stated in the documentation and the behaviour expected in the test module), would you prefer everything to stay in the same issue or should I open a new issue for each ?

**Comment by willmcgugan** [comment]
`DirectoryExpected` I think makes sense. It was expecting a directory for a give path component. `DirectoryExists` I would agree is not clear. Open to suggestions about what to the right thing to do there would be.

New issues would be great, to help me track them. Unless its a class of issue that might be worth being lumped together. Looking forward to seeing what you found!

**Comment by althonos** [comment]
The dropbox SDK (no, I'm absolutely not working on a DropboxFS :smile:) uses the following conventions everytime there's a conflict when trying to either write a file or create a folder (it's not really a Python exceptions scheme because the use Javaesque exceptions):
- `WriteConflict('file')` – There’s a file in the way (that would be `fs.errors.FileExists`)
- `WriteConflict('folder')` – There’s a folder in the way (that would be `fs.errors.DirectoryExists`)
- `WriteConflict('file_ancestor')` – There’s a file at an ancestor path, so we couldn’t create the required (that would be `fs.errors.DirectoryExpected`).

At least that resolves the aforementioned case and makes it clearer, although it's still not perfect since a folder creating function will raise a `FileExists` error.

**Comment by willmcgugan** [comment]
That makes sense. It would be nice to be more specific. Will need to think about that one...

**Comment by willmcgugan** [comment]
Going to close this and re-open a new issue, so I don't forget about it.
