### ISSUE TITLE
Adopt Black as code formatting tool

### ISSUE THREAD

**Issue by willmcgugan** [PyFilesystem/pyfilesystem2#187]
I've been using [black](https://pypi.org/project/black/) to format my Python code. Not being concerned about code formatting is surprisingly liberating, it's one less thing to think about when you are coding.

Unless there are any objections, at some point once I've cleared down a few PRs I would like to run black on the entire FS2 code base.

**Comment by willmcgugan** [comment]
@althonos Have you used black? Any objections? The code is fairly standardly formatted, so it wouldn't be a massive change.

**Comment by althonos** [comment]
I've not used it consistently, only tried on a few files to see what it does. I do not agree with *all* their design choices, but I can feel the huge benefit it can have on a collaborative project.  On a side note, I've been using `rustfmt` a lot to format Rust code, and although at first it felt weird, I found myself coding in the style of `rustfmt` in just a few weeks :smile:

**Comment by willmcgugan** [comment]
Cool. I felt the same way about black. Started liking it after some initial resistance.

Will do that in a single PR soon, so that it doesn't get mixed in with any features.

**Comment by willmcgugan** [comment]
Merged https://github.com/PyFilesystem/pyfilesystem2/pull/200

**Comment by willmcgugan** [comment]
Should have known it wouldn't go as smoothly as that. The type-checking broke due to the way Black formats comments. I've filed an issue: https://github.com/ambv/black/issues/424

It only occurred in 2 places, which I have manually fixed.
