### ISSUE TITLE
[Documentation] Improve doc for Essential Methods

### ISSUE THREAD

**Issue by althonos** [PyFilesystem/pyfilesystem2#19]
Since implementing a Filesystem actually requires a restricted set of methods, they should be well documented to state the expected behaviour. Currently, the following pieces of information are missing in the documentation:

## open()
* **Parameters**:
  - `encoding` states it defaults to `utf-9`
  - `**options` is not listed
  - the link to the [stdllib error-handler](https://docs.python.org/3/library/codecs.html#error-handlers) does not render well on RTD, why not use the ``` `name <link>`_ ``` format in the docstrings ?

## openbin()
* **Errors not listed**: 
  - raises `ValueError` when explictly given a text mode ('wt', 'rt', 'at'...) or an invalid mode ('h', 'z', ...)
  - raises `FileExpected` when path goes to a directory
  - raises `FileExists` when mode is 'x' or 'xb'
  - raises `ResourceNotFound` when mode is 'r' or 'rb'
* **Note**: 
  - maybe write somewhere that 'r', 'w', 'x', and 'a' are automatically coerced to their binary counterpart (this is a bit counterintuitive when compared with Python `open`)

## remove()
* **Error issues**:
  - is listed to raise `FileExpected` when given a directory whereas the test module expects `InvalidResource` to be raised (`FileExpected` makes more sense I think)

## removedir()
* **Errors not listed**:
  - raises `RemoveRootError` when attempting to remove the root of the fs

* **Error issues**:
  - is listed to raise `ParentDirectoryMissing` when one of the ancestors in the given path does not exist but this error does not exist

## setinfo()
* **Errors not listed**:
  - raises `ResourceNotFound` when the path does not exist

**Comment by willmcgugan** [comment]
Thanks. I'll have a look at those.

**Comment by willmcgugan** [comment]
> maybe write somewhere that 'r', 'w', 'x', and 'a' are automatically coerced to their binary counterpart (this is a bit counterintuitive when compared with Python open)

Is it that unintuitive? Give the method name is `openbin`? The alternative would be to raise an error if you don't add a `b` character, which feels like punishing the developer.

**Comment by willmcgugan** [comment]
Actually, I see what you mean. Those changes are in master. Thanks.

**Comment by althonos** [comment]
What I thought was that `openbin` was the low-level method, and that `open` would be used all the time, wrapping `openbin` for textual modes and directly returning the file handle for binary methods. But the note you added to the doc is clear enough now.
