### ISSUE TITLE
Case insensitive walk

### ISSUE THREAD

**Issue by geoffjukes** [PyFilesystem/pyfilesystem2#192]
Hi!,

I'm walking a case insensitive filesystem, with a filter: `fs.open_fs(SCAN).walk.files(filter=['*.wav']`

It doesn't return files ending `.WAV` because the filter is case-sensitive.

Is there an option to make that case insensitive? I'm happy to check the code and put in a PR if it doesn't already exist (I couldn't find anything in the docs)

**Comment by willmcgugan** [comment]
That *should* work. `walk` will call `fs.match` which will detect if the filesystem is case sensitive with the `case_sensitive` meta value. Although it may not be a very well tested mechanism.

What filesystem is it you are using?

**Comment by geoffjukes** [comment]
I’m using a case insensitive SMB share, mounted in a Linux host.

**Comment by willmcgugan** [comment]
I've just noticed a bug. The `fs.match` method references a meta value called `case_sensitive`, but it is `case_insensitive` that is used everywhere.

Feel free to tackle that one. Alternatively, you could do `filter=['*.wav', '*.WAV']` until I fix it...

**Comment by geoffjukes** [comment]
Good spot - I'm on it :)

**Comment by geoffjukes** [comment]
#193

**Comment by willmcgugan** [comment]
Should be fixed in 2.0.26.
