### ISSUE TITLE
Walking syntactical sugar

### ISSUE THREAD

**Issue by willmcgugan** [PyFilesystem/pyfilesystem2#195]
I've been thinking about adding some syntactical sugar to `fs.walk`.

Currently `fs.walk.files` returns an iterator of paths. You could use it to remove all your `.pyc` files as follows:

```
for path in fs.walk.files(filter=['*.pyc']):
    fs.remove(path)
```

Which is nice enough. But `files` could return a smarter iterable, that supported a bunch of operations. There could be `remove` operation for instance, that deleted all the files in the iterable.

So the above example would be:

```
fs.walk.files(filter=['*.pyc']).remove()
```

Which is bordering on magical, but I think at least as clear. 

Other operations could be `cat`, `compress`, `truncate` etc.

Open to debate if that is worth doing. Or if the maintenance is not worth the code it saves.

This would also pave the way for [glob](https://docs.python.org/2/library/glob.html) support, which could work in the same way.

**Comment by geoffjukes** [comment]
I have a use-case right now that involves cleaning up a directory tree. This functionality would reduce the code required, and make it more readable. 

Right now, I plan to use your first example, filtering for all the file types. 

But an easier-to-read version would use your second example, and walk for separate file types. 

But honestly, I’m more excited about the glob support. A big pain for my processes, it the OSX habit of creating ‘dotfiles’ everywhere. They really mess with automated file processing, if you don’t watch out for them :)

**Comment by willmcgugan** [comment]
Started work on globbing. https://github.com/PyFilesystem/pyfilesystem2/pull/209

**Comment by willmcgugan** [comment]
This is covered by the globbing feature in master.
