### ISSUE TITLE
Safe to use methods after implementing essential ones

### ISSUE THREAD

**Issue by xandfury** [PyFilesystem/pyfilesystem2#204]
Hi..
After discussion with Will, I was able to write a custom `fs` that overwrites the essential methods provided [here](http://pyfilesystem2.readthedocs.io/en/latest/implementers.html#essential-methods). It does exactly what I expect it to do and I am pretty happy with it. 
My question is :  **just after implementing** these methods, what all [non-essential methods](http://pyfilesystem2.readthedocs.io/en/latest/implementers.html#non-essential-methods) are safe to use?

**Comment by xandfury** [comment]
Thanks for clearing that up.

**Comment by xandfury** [comment]
I just noticed recently, `setbinfile` method used in `move` doesn't use my custom defined `openbin` method as can be observed [here](https://github.com/PyFilesystem/pyfilesystem2/blob/b2c0d96f55d4dfe777b4f9476676b77d01f36bf7/fs/base.py#L1280) and [here](https://github.com/PyFilesystem/pyfilesystem2/blob/b2c0d96f55d4dfe777b4f9476676b77d01f36bf7/fs/iotools.py#L196). 
My `openbin` returns a custom file object that has to go under a setup and teardown process. Rather than using the `openbin` method defined in my class,  `setbinfile` creates a new file object of type `io.TextIOWrapper`

To reproduce this, please check whether `openbin` is invoked during the call of [`move`](https://github.com/PyFilesystem/pyfilesystem2/blob/b2c0d96f55d4dfe777b4f9476676b77d01f36bf7/fs/base.py#L1046). I have added a custom `setbinfile` but I think we can chage this in it's implementation.

**Comment by willmcgugan** [comment]
`setbinfile` opens a file in binary mode, the default `open` calls  the `openbin` method if there is a `b` in the mode. 

If you think there is a bug in PyFilesystem, please try to identify what is going wrong (line number, traceback) etc. I'll need to know what I'm looking for before helping you debug...

Have you put a print statement in your `setbinfile` method? And is it return a *binary* file ?

**Comment by willmcgugan** [comment]
Please open a new issue if you identify a bug...
