### ISSUE TITLE
Error walking ftp filesystem

### ISSUE THREAD

**Issue by dhirschfeld** [PyFilesystem/pyfilesystem2#205]
When trying to walk an FTP sub-folder as shown below:

![image](https://user-images.githubusercontent.com/881019/43458119-5a4f05c0-950c-11e8-8a3c-da9a57d570ed.png)

The below code:
https://github.com/PyFilesystem/pyfilesystem2/blob/b2c0d96f55d4dfe777b4f9476676b77d01f36bf7/fs/ftpfs.py#L710-L724

...seems to give sensible results:
```python
In[2]: lines
Out[2]: 
['Type=cdir;Modify=20180731114724;UNIX.mode=0755; /tmp',
 'Type=pdir;Modify=20180731112024;UNIX.mode=0775; /',
 'Type=file;Size=331523;Modify=20180731112041;UNIX.mode=0644; a.csv',
 'Type=file;Size=368340;Modify=20180731112041;UNIX.mode=0644; b.csv']

In[4]: list(self._parse_mlsx(lines))
Out[4]: 
[{'basic': {'name': 'tmp', 'is_dir': True},
  'ftp': {'type': 'cdir', 'modify': '20180731114724', 'unix.mode': '0755'},
  'details': {'type': 1, 'size': 0, 'modified': 1533037644}},
 {'basic': {'name': '', 'is_dir': True},
  'ftp': {'type': 'pdir', 'modify': '20180731112024', 'unix.mode': '0775'},
  'details': {'type': 1, 'size': 0, 'modified': 1533036024}},
 {'basic': {'name': 'a.csv', 'is_dir': False},
  'ftp': {'type': 'file',
   'size': '331523',
   'modify': '20180731112041',
   'unix.mode': '0644'},
  'details': {'type': 2, 'size': 331523, 'modified': 1533036041}},
 {'basic': {'name': 'b.csv', 'is_dir': False},
  'ftp': {'type': 'file',
   'size': '368340',
   'modify': '20180731112041',
   'unix.mode': '0644'},
  'details': {'type': 2, 'size': 368340, 'modified': 1533036041}}]
```
i.e. the current dir, the parent dir and the two files are all correctly? listed.

However, in the [`Walker._walk_breadth`](https://github.com/PyFilesystem/pyfilesystem2/blob/master/fs/walk.py#L389-L415) method the current dir `tmp` is the first item yielded from `self._scan` which result in the `cdir` being joined to itself and the non-existent `/tmp/tmp` being pushed onto the deque:

![image](https://user-images.githubusercontent.com/881019/43458479-c5a7e3ea-950d-11e8-9dd4-d08ee34a5360.png)

...so it seems there's a :bug: there somewhere - I'm just not familiar enough with the codebase to say exactly where. Hopefully there's enough debug info there that the underlying issue is easy to spot. Happy to provide more info if required...

**Comment by willmcgugan** [comment]
Odd. It looks like the server is returning info for all resources, rather than the specify director.

What happens if you call `listdir('/')` and `listdir('/tmp')`?

Do you know what software the server is running?

**Comment by dhirschfeld** [comment]
If I try to *walk* the file system from the root folder I get into an infinite loop.
This makes sense since `join('', '') == ''`

i.e. the root folder is it's own identity under the `join` operator so it keeps being pushed back onto the deque

**Comment by dhirschfeld** [comment]
```
λ telnet <address> ftp
220 <address> NcFTPd Server (licensed copy) ready.
```

**Comment by dhirschfeld** [comment]
So the below patch fixes it for my usecase:
```python
if lines:
    for raw_info in self._parse_mlsx(lines):
        try:
            if raw_info['ftp']['type'] in ('cdir', 'pdir'):
                continue
        except KeyError as exc:
            pass
        yield Info(raw_info)
    return
```
It seems a bit ugly to special case it... but if it works ¯\_(ツ)_/¯

**Comment by dhirschfeld** [comment]
If I create another subfolder `tmp2`:
![image](https://user-images.githubusercontent.com/881019/43495253-4849bdde-957a-11e8-97df-6ead1e1d01da.png)

I can see that the type of a normal folder is given as `dir`:
```python
In[8]: {raw_info['basic']['name']: raw_info['ftp']['type'] for raw_info in self._parse_mlsx(lines)}
Out[8]: {'tmp': 'cdir', '': 'pdir', 'a.csv': 'file', 'b.csv': 'file', 'tmp2': 'dir'}
```
...so it should be safe to filter out the `cdir` and `pdir` folders.

**Comment by dhirschfeld** [comment]
Created PR #206 to discuss the proposed fix.

**Comment by willmcgugan** [comment]
Good sleuthing, thanks.
