### ISSUE TITLE
Hacking through WrapFS

### ISSUE THREAD

**Issue by xandfury** [PyFilesystem/pyfilesystem2#207]
**_Disclaimer_**: This might be long for something stupid or simple. Please be patient :-) 

-------------
As discussed in #204 - I am trying to write a custom FS that caches files and directories. For the same I needed a custom file wrapper that does setup and teardown stuff. This is how it looks like:
```python
class _custom_file_wrapper(object):
    """This is a custom file class that does some setup and teardown stuff.."""

    def __init__(self,
                 file_system,
                 parent_fs,
                 path,
                 mode,
                 buffering=-1,
                 encoding=None,
                 newline='',
                 line_buffering=False):
        print('We should see this message when a new file is created!!')
        self._file = parent_fs.openbin(path=path,
                                       mode=mode,
                                       buffering=buffering,
                                       encoding=encoding)

        # do some setUp stuff with _file.
        print('Filesystem: {}, Parent File system: {}'.format(file_system, parent_fs))

    def __enter__(self):
        return self._file

    def __exit__(self, exc_type, exc_value, traceback):
        self.close()
        return False

    def close(self):
        # do some tearDown stuff for the _file object.
        print('Closing File ....')
        self._file.close()

    def __getattr__(self, item):
        return getattr(self._file, item)
``` 

My `WrapFS` wraps an `OSFS` instance and overwrites functionality such as `open` and `openbin` to use the above `_custom_file_wrapper` object. **_This works fine when the essential methods are called but when non-essential methods such as `move` or `copy` are called, my `_custom_file_wrapper` is ignored._** Below is how my custom WrapFS instance looks like:

```python
class TestFileSystem(WrapFS):
    def __init__(self, path):
        super(TestFileSystem, self).__init__(open_fs(path))   # wrap osfs at path
        self._wrap_fs._meta['supports_rename'] = False
        # ^^^ not sure if this is required as a custom getmeta() is defined below.
        # But still - to be safe.

    def getmeta(self, namespace="standard"):
        """Defined so that os.rename is never used."""
        self.check()
        meta = self.delegate_fs().getmeta(namespace=namespace)
        meta['supports_rename'] = False
        return meta


    def openbin(self, path, mode="r", buffering=-1, **options):
        print('Inside openbin of TestFileSystem. This is a test!')
        return _custom_file_wrapper(parent_fs=self.delegate_fs(),
                                    file_system=self,
                                    path=path,
                                    mode=Mode(mode).to_platform_bin(),
                                    buffering=buffering)

    # NOTE: open() is similar. I omitted it's definition since  `move()`  uses move.move_file which would
    # neither use open() or openbin()
```

When run together, the following result is obtained ([Link to gist](https://gist.github.com/xandfury/f9cbd96879da65cc1b39633f6530fff2))

```shell
Starting FS test
Listing files/directories in cwd: ['another.py', 'test.py']
Rename is False. os.rename should not be used
Inside openbin of TestFileSystem. This is a test!
We should see this message when a new file is created!!
Filesystem: <osfs '/home/abhinav/demo'>, Parent File system: <osfs '/home/abhinav/demo'>
Closing File ....
------------- Start Move --------------
------------- Stop Move --------------
Stopping FS test
```

As seen from above output, my custom defined essesntial methods were not invoked during the call of `move()`. 

**_Problem_**:
The reason for this is that *all* methods defined in `WrapFS` call the underlying `OSFS` methods. 
I was hoping that in it's implementation, only essential methods would be allowed to do so.

**Comment by althonos** [comment]
So if I get it right, you hope to implement only the essential methods on your `_custom_file_wrapper` and have the resulting wrapper filesystem use the stub implementations from the base `FS` (e.g. have `open`, `move`, `copy`, etc. use `openbin`) ?

**Comment by willmcgugan** [comment]
If you think the issue is in `fs.move`, try putting some print statements in that method, to see what is going on. Specifically print the type of the filesystems, and trace what points in the code it reaches.

**Comment by xandfury** [comment]
@willmcgugan I am pretty sure that `fs.move` is invoked as per the underlying (not overwritten) `WrapFS.move`. I think this issue can be resolved if the `fs.move.copy_file` method accepts file descriptors instead of paths. 
But it's not just about `move` or `copy`, it's about the 30+ non essential methods that are required to be rewriten in order to make this work.

**Comment by willmcgugan** [comment]
That's exactly what happens @xandfury

Always happy to help, you may have missed something on a fundamental level, and I don't think you'll be able to progress unless you're willing to accept a bit of guidance on this.

**Comment by xandfury** [comment]
Sorry if may have brushed you in the wrong sense. I am always keen on accepting guidance :-) I'll check this and report back.

**Comment by althonos** [comment]
@xandfury: `fs.archive` is not "archived", it's my take on *archive* filesystems :wink:

**Comment by willmcgugan** [comment]
@xandfury When building a FS class you need only implement the essential methods. All other methods can be implemented with the essential methods.

The WrapFS is different, it needs all the methods because if is wrapping an FS object with a custom method, the wrapped class must use that custom method.

If the problem is that `move` isn't calling your `openbin` (but otherwising working) then that is probably because it is doing a os.rename within the `OSFS` class. If you want to discover why that is, try putting print statements in the base.py `FS.move`, as I suggested. 

If you can't point at a bit of code in PyFilesystem that isn't working as expected / advertised, then a Github issue may not be the best forum. I'd suggest the [mailing list](https://www.pyfilesystem.org/page/help/) for such things. Maybe start with explaining what you want to accomplish.
