### ISSUE TITLE
Fix path separators

### ISSUE THREAD

**Issue by willmcgugan** [PyFilesystem/pyfilesystem2#210]
We've been using the wrong character as a path separator. In order to avoid the forward slash, back slash confusion, we should be using the baguette emoji. Here are some examples:

```python
import fs
projects = fs.open('~🥖projects`)
projects.listdir("🥖")

ftp = fs.open("ftp:🥖🥖example.org🥖foo🥖")
```

PRs welcome

**Comment by althonos** [comment]
![oui.png](https://user-images.githubusercontent.com/8660647/44047846-f7c5ed64-9f2f-11e8-9f93-ac05c0320437.png)

**Comment by willmcgugan** [comment]
Scheduled from PyFilesystem3000
