### ISSUE TITLE
why FS.desc(path) checks that path exists?

### ISSUE THREAD

**Issue by anthrotype** [PyFilesystem/pyfilesystem2#220]
Hi,

I'd like to get a description of a path to a resource on a filesystem, even if that resource is not found. For example, I could use this description to print a meaningful error message to the user.

However, it seems that the `desc` method of FS objects first checks that the path exists, and if not it raises a ResourceNotFound:

https://github.com/PyFilesystem/pyfilesystem2/blob/5643bade04cf2f8e4af575f404d0dab7717505a6/fs/base.py#L445-L446

The `getsyspath` (at least the OSFS.getsyspath) seems to work for a non-existing path. So why is it that `desc` is asserting that the path exists before making the description?

**Comment by willmcgugan** [comment]
It's because some filesystems can not generate a meaningful description without mapping to an underlaying resource. MountFS for instance; there is no way of knowing what filesystem a path maps to if there is no file or directory there.
