### ISSUE TITLE
The Schrödinger memory resource

### ISSUE THREAD

**Issue by althonos** [PyFilesystem/pyfilesystem2#221]
Just for the record, a `MemoryFS` root can store text without raising any error ! 

```python
>>> import fs
>>> m = fs.open_fs('mem://')
>>> m.settext('/', "i'm a file")
>>> m.touch('nope')
>>> m.gettext('/')
"i'm a file"
>>> m.listdir('/')
['', 'nope']
```

Actually this creates an empty-named record right at the root but I found it quite funny because it makes the root behave like both a directory and a file :wink:

**Comment by willmcgugan** [comment]
Hmm. There must be some way we can spin this as a feature and not a bug.
