### ISSUE TITLE
Deprecation warning - import Mapping from collections.abc instead of collections for 3.8

### ISSUE THREAD

**Issue by rkhwaja** [PyFilesystem/pyfilesystem2#222]
I get the following running the test set on googledrivefs using fs 2.1.1:

`.../python3.7/site-packages/fs/error_tools.py:110: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(path_replace, collections.Mapping):`

 It looks like you can just import from collections.abc on everything >= python 3.3.

I also get the following:

`.../python3.7/site-packages/fs/test.py:1050: DeprecationWarning: Please use assertRaisesRegex instead.
  with self.assertRaisesRegexp(errors.ResourceNotFound, error_msg):
`

which I suppose is something from unittest

**Comment by willmcgugan** [comment]
Fixed in v2.1.2
