### ISSUE TITLE
Can't build wheel from sdist

### ISSUE THREAD

**Issue by televi** [PyFilesystem/pyfilesystem2#225]
Steps
------

In a python3.6 venv, simply run ```pip wheel bdist_wheel fs==2.1.1```

Expected results
-----------------

A wheel is build for fs.

Observed results
------------------

The build fails with the following output (snipped):

```
  running install_egg_info
  running egg_info
  writing fs.egg-info/PKG-INFO
  writing dependency_links to fs.egg-info/dependency_links.txt
  writing entry points to fs.egg-info/entry_points.txt
  writing requirements to fs.egg-info/requires.txt
  writing top-level names to fs.egg-info/top_level.txt
  reading manifest file 'fs.egg-info/SOURCES.txt'
  writing manifest file 'fs.egg-info/SOURCES.txt'
  Copying fs.egg-info to build/bdist.linux-x86_64/wheel/fs-2.1.1-py3.6.egg-info
  running install_scripts
  error: [Errno 2] No such file or directory: 'LICENSE'

  ----------------------------------------
  Failed building wheel for fs
```

Investigation
-------------

If I clone the repository and checkout v2.1.1, the following works: ```python3 setup.py bdist_wheel```.

That led me to believe that the published sdist was wrong.  If I download it from pypi.org and expand it, the file LICENSE is, in fact, missing but setup.cfg still references it which then causes wheel builds using the sdist to fail.

To test this, I added a file the the cloned repo named "MANIFEST.in" and simply added "include LICENSE" to it and the ran ```python3 setup.py sdist```.  If I then expand that source distribution, LICENSE is present and running ```python3 wheel bdist_wheel``` from that works as expected.

So it appears that the source distribution as published to pypi is incorrect in that it is missing the LICENSE file required by setup.cfg to build a wheel.

I can submit a patch to add a MANIFEST.in file with the line above if you'd like.

**Comment by willmcgugan** [comment]
Thanks for investigating. A PR would be fantastic.

**Comment by willmcgugan** [comment]
Fixed in https://github.com/PyFilesystem/pyfilesystem2/pull/226
