### ISSUE TITLE
no files/directories are listed

### ISSUE THREAD

**Issue by boumboum** [PyFilesystem/pyfilesystem2#230]
I'm thinking about replacing ftplib by fs but during my test I'm unable to even list the home directory once I'm connected to the server
Here is the code:
```
from fs.ftpfs import FTPFS
path = FTPFS('ftp.rmyserver.domain', user='myuser', passwd='mypwd')
print(path.listdir('/'))
[]
```
And I know there are folders under root because if I do that with ftplib, all the directories are listed:
```
from ftplib import FTP
ftp = FTP('ftp.rmyserver.domain', user='myuser', passwd='mypwd')
ftp.dir()
10-09-18  10:34AM       <DIR>          folder1
04-13-18  08:27AM       <DIR>          folder2
05-29-17  05:53PM       <DIR>          folder3
05-17-18  02:16PM       <DIR>          folder4
```

Why?

**Comment by willmcgugan** [comment]
There was an update very recently that added support for Windows NT FTP. If you could check out master, it should work. Or wait for an official release which should be out soon.

**Comment by willmcgugan** [comment]
Hopefuly fixed in v2.1.2, Please give it a try...

**Comment by boumboum** [comment]
Yep. It works. Great! :-)

May I ask how pyfilesystem2 is positioning itself against ftplib in terms of performance (and also can I have long running task with, as ftplib seems to close the connection after a short period of time (minutes))

Same question of performance against the builtin os based file handling.
Thanks

**Comment by willmcgugan** [comment]
Performance for FTPS will be the same as ftplib, but if you use `fs.copy` to copy files you will benefit from multiple connections, which can result in must faster copies. OSFS is a thin layer over standard os functions, so performance will be the same.

With regards to long running tasks, most ftp servers will kick you after a period of inactivity. I'm not sure how FTPFS would response to that, tbh. Your best approach may be to create FTPFS instances as required when you want to do something. I can't think of a reason to remain connected to a ftp server if you aren't actively using it...

**Comment by willmcgugan** [comment]
Fixed in v2.1.2

**Comment by boumboum** [comment]
Thanks for your answer.
Regarding long running tasks, unfortunately I have some tricky functions, where I have to download a quite big XML (500MB - 3M lines) file from the FTP site, process it and save to the database, then I have to move the file on an other FTP folder. So the process time between downloading and moving the file is over 1 hour.
Anyway, I can handle it somehow.

A last question if I may: Is it possible to use FS with a remote SMB share (with user authentication)? I didn't see that in the docs

**Comment by willmcgugan** [comment]
FTPFS will use a new connection per open file. So those aren't going to timeout. But there is a single connection for listing directories etc. That could in theory timeout. You could work around it by opening the server filesystem each time. Something like this...

```python
with open_fs("ftp://blah") as server:
    with server.openbin("file.xml") as fh:
        process_xml(fh)

with open_fs("ftp://blah") as server:
    server.move("file.xml", "/done/file.xml")
```

Failing that, it may be possible to detect a disconnect from within FTPFS and re-connect as required. If you think you might need that, please file an issue, or a PR if you want to tackle it yourself...

There is a third party [fs.smbs](https://pypi.org/project/fs.smbfs/) module. More information on supported filesystem on the [wiki](https://www.pyfilesystem.org/page/index-of-filesystems/)
