### ISSUE TITLE
Adding examples to repository.

### ISSUE THREAD

**Issue by bukowa** [PyFilesystem/pyfilesystem2#233]
Hello, thank you all for the awesome library 👍 It's strong! 🥇 
I am reading documentation - its great but there's lack of use-cases. Some simple and advanced examples could show potential users why this library is so strong. https://github.com/PyFilesystem/pyfilesystem2/issues/177

 What i have in mind:

1. Ex. download file from FTP to local system.
2. Ex. download file from URL to FTP.
3. Everything else that you do on a daily basis like working with clouds etc.
4. Maybe some advanced things you built?

We could have ``examples`` folder in the repository. What do you think?

Best Regards,
Mateusz

**Comment by willmcgugan** [comment]
An examples folder is a good idea!

I would also like to flesh out the [wiki](https://www.python.org) a bit.

**Comment by willmcgugan** [comment]
Added an `examples/` directory.
