### ISSUE TITLE
Feature Request: Passing SubFS to removetree

### ISSUE THREAD

**Issue by JakeSummers** [PyFilesystem/pyfilesystem2#237]
Good Afternoon,

Currently this is the contract of remove tree: 

```
    def removetree(self, dir_path):
        # type: (Text) -> None
        """Recursively remove the contents of a directory.

        This method is similar to `~fs.base.removedir`, but will
        remove the contents of the directory if it is not empty.

        Arguments:
            dir_path (str): Path to a directory on the filesystem.

        """
```

If this were updated to take a dir_path OR a SubFS this would make the API cleaner.  

Example usage: 

```
root_fs: FS = ...
sub_path: str = ...
sub_fs: SubFS = root_fs.makedir(sub_path)
...
```
Currently, I have to remove the dir like this: 
```
root_fs.removetree(sub_fs.delegate_path())
```

It would be more concise, if I could remove the SubFS directly, like this: 

``` 
root_fs.removetree(sub_fs)
```

**Comment by willmcgugan** [comment]
Sorry of the delay.

I concur it would be more concise, but it introduces a few problems. The behaviour would be unclear if you were to call it with a filesystem that isn't a SubFS, or is not a directory in the parent. It also doesn't conform to the requirement we have that all arguments must be simple types (this is to facilitate network based interfaces to filesystems).

I'm afraid this will have to be a wontfix. Best I can suggest is to define a `remove_subtree` function in your code...
