### ISSUE TITLE
FTP problems with proftp server

### ISSUE THREAD

**Issue by gpcimino** [PyFilesystem/pyfilesystem2#24]
Hi all!

I discovered some issue with proftp server and pyfilesystems2.

This is my setup:

- Client: pyfilesystem2 (branch fix-ftp) on python 3.5.1 32bin Windows 7
- Server: proftp as docker container on redhat linux.

The client code is:
```
from fs.copy import copy_fs

addr = <docker host machine ip>
usr = “username”
psw = "password "
ftproot = "/data/"

try:
    ftpurl = 'ftp://' + usr + ":" + psw + "@" + addr + ftproot
    print("copy files between ftp "+ftpurl+" an local filesystems... ", end='')
    
    copy_fs(ftpurl, 'osfs://d:/tmp2/target/')
    print("OK")
except Exception as ex:
    print("FAILS")  
```

To run the server you need docker. The command is:

```docker run -d  -p 21:21 -p 20:20  -e USERNAME=username -e PASSWORD=password -v /ftproot:/ftp andrewvos/docker-proftpd```

After some debugging I noticed that the code fails on line 606 in ftpfs.py:

self.ftp.retrlines(_encode("MLSD {}".format(_path)), lines.append)

Any idea? May be some incompatibility of the data returned by list dir of proftp?

Did you consider implementing a ftpfs using a more advanced lib than the plain ftplib of python standard lib? I can recommend http://ftputil.sschwarzer.net/trac. I used in some production scenarios with different ftp servers (both windows and linux) and it did pretty good! 

Ciao
GP

**Comment by willmcgugan** [comment]
I haven't checked, but it could be this issue https://github.com/PyFilesystem/pyfilesystem2/issues/11

> Did you consider implementing a ftpfs using a more advanced lib than the plain ftplib of python standard lib? I can recommend http://ftputil.sschwarzer.net/trac. 

Actually, yes. But I found ftputil to have a few flaws, and it was difficult to wrap in an FS interface. I also have this self-imposed restriction of only using the standard library for built in filesystems.

**Comment by willmcgugan** [comment]
I've just made a change to ftpfs which may fix this. Would you mind trying the master branch and let me know how you get on? If that doesn't fix it, I'll try and replicate your environment and look more closely...

**Comment by gpcimino** [comment]
Good morning,

below is the output of my testing session.
First is the conenction with command line ftp client to prove the ftp server works.
After is the execution of the script using pyfilesystem2 as reported in the first post of this thread.
Unfortunately there is still a problem around line 606 of ftpfs.py. I didn' t have time to debug properly.
Thanks
GP

Note that i just add the following two lines inside the except block:

```
    print(ex)
    traceback.print_exc()
```


Here is the ouput:

```
(pyfs_test) d:\python\pyfilesystem2\tests>ftp 172.21.160.35
Connected to 172.21.160.35.
220 ProFTPD 1.3.5rc3 Server (proftpd) [::ffff:172.17.0.6]
User (172.21.160.35:(none)): username
331 Password required for username
Password:
230 User username logged in
ftp> cd data
250 CWD command successful
ftp> ls
200 PORT command successful
150 Opening ASCII mode data connection for file list
39Mb_textfile.txt
3Byte_textfile.txt
image.jpg
226 Transfer complete
ftp: 50 bytes received in 0.00Seconds 16.67Kbytes/sec.
ftp> bin
200 Type set to I
ftp> lcd d:\tmp
Local directory now d:\tmp.
ftp> mget *
200 Type set to I
mget image.jpg? y
200 PORT command successful
150 Opening BINARY mode data connection for image.jpg (32612 bytes)
226 Transfer complete
ftp: 32612 bytes received in 0.00Seconds 32612000.00Kbytes/sec.
mget 3Byte_textfile.txt? y
200 PORT command successful
150 Opening BINARY mode data connection for 3Byte_textfile.txt (3 bytes)
226 Transfer complete
ftp: 3 bytes received in 0.00Seconds 3000.00Kbytes/sec.
mget 39Mb_textfile.txt? y
200 PORT command successful
150 Opening BINARY mode data connection for 39Mb_textfile.txt (40582338 bytes)
226 Transfer complete
ftp: 40582338 bytes received in 0.79Seconds 51565.87Kbytes/sec.
ftp> bye
221 Goodbye.




(pyfs_test) d:\python\pyfilesystem2\tests>python proftp.py
copy files between ftp ftp://username:password@172.21.160.35/data/ an local filesystems... *resp* '220 ProFTPD 1.3.5rc3 Server (proftpd) [::ffff:172.17.0.6]'
*cmd* 'USER username'
*resp* '331 Password required for username'
*cmd* 'PASS ********'
*resp* '230 User username logged in'
*welcome* '220 ProFTPD 1.3.5rc3 Server (proftpd) [::ffff:172.17.0.6]'
*cmd* 'FEAT'
*resp* '211-Features:\n MFMT\n SIZE\n MFF modify;UNIX.group;UNIX.mode;\n REST STREAM\n MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.mode*;UNIX.owner*;\n UTF8\n LANG en-US*\n EPRT\n EPSV\n MDTM\n TVFS\n211 End'
*cmd* 'MLST /data'
*resp* '250-Start of list for /data\n modify=20170208135538;perm=flcdmpe;type=dir;unique=FD02U20000097;UNIX.group=1000;UNIX.mode=0777;UNIX.owner=1000; /data\n250 End of list'
*cmd* 'TYPE A'
*resp* '200 Type set to A'
*cmd* 'PASV'
FAILS
unable to connect to 172.21.160.35
Traceback (most recent call last):
  File "d:\python\pyfilesystem2\fs\ftpfs.py", line 42, in ftp_errors
    yield
  File "d:\python\pyfilesystem2\fs\ftpfs.py", line 606, in _scandir
    _encode("MLSD {}".format(_path)), lines.append
  File "d:\Users\<user_name>\AppData\Local\Programs\Python\Python35-32\Lib\ftplib.py", line 467, in retrlines
    with self.transfercmd(cmd) as conn, \
  File "d:\Users\<user_name>\AppData\Local\Programs\Python\Python35-32\Lib\ftplib.py", line 398, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "d:\Users\<user_name>\AppData\Local\Programs\Python\Python35-32\Lib\ftplib.py", line 358, in ntransfercmd
    host, port = self.makepasv()
  File "d:\Users\<user_name>\AppData\Local\Programs\Python\Python35-32\Lib\ftplib.py", line 336, in makepasv
    host, port = parse227(self.sendcmd('PASV'))
  File "d:\Users\<user_name>\AppData\Local\Programs\Python\Python35-32\Lib\ftplib.py", line 272, in sendcmd
    return self.getresp()
  File "d:\Users\<user_name>\AppData\Local\Programs\Python\Python35-32\Lib\ftplib.py", line 235, in getresp
    resp = self.getmultiline()
  File "d:\Users\<user_name>\AppData\Local\Programs\Python\Python35-32\Lib\ftplib.py", line 221, in getmultiline
    line = self.getline()
  File "d:\Users\<user_name>\AppData\Local\Programs\Python\Python35-32\Lib\ftplib.py", line 203, in getline
    line = self.file.readline(self.maxline + 1)
  File "d:\Users\<user_name>\AppData\Local\Programs\Python\Python35-32\Lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "proftp.py", line 13, in <module>
    copy_fs(ftpurl, 'osfs://d:/tmp2/target/')
  File "d:\python\pyfilesystem2\fs\copy.py", line 34, in copy_fs
    copy_dir(src_fs, '/', dst_fs, '/', walker=walker)
  File "d:\python\pyfilesystem2\fs\copy.py", line 115, in copy_dir
    for dir_path, dirs, files in walker.walk(src_fs, _src_path):
  File "d:\python\pyfilesystem2\fs\walk.py", line 293, in _walk_breadth
    for info in self._scan(fs, dir_path, namespaces=namespaces):
  File "d:\python\pyfilesystem2\fs\wrapfs.py", line 166, in scandir
    page=page):
  File "d:\python\pyfilesystem2\fs\ftpfs.py", line 611, in _scandir
    raise # pragma: no cover
  File "d:\Users\<user_name>\AppData\Local\Programs\Python\Python35-32\Lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "d:\python\pyfilesystem2\fs\ftpfs.py", line 45, in ftp_errors
    msg='unable to connect to {}'.format(fs.host)
fs.errors.RemoteConnectionError: unable to connect to 172.21.160.35

```

**Comment by gpcimino** [comment]
Will,

i am playing with ftpfs module and the Docker ProFTP instance.
Surprisingly, (o may be not ;-) ) the error reported above happens only on Windows7.
I executed the same test on a linux (actually a second Docker container with just Python 3.5.2) and it works just fine!
Then a found this:

https://support.microsoft.com/en-us/help/981344/an-application-may-receive-the-10054-error-when-the-application-receives-data-from-a-connection-on-a-computer-that-is-running-windows-7-or-windows-server-2008-r2-if-a-tdi-filter-driver-is-installed

Have you got any feedback on similar problems from poor Windows 7 users?!?
Thanks
Ciao

**Comment by willmcgugan** [comment]
That's interesting. I haven't had any feedback re ftp bugs so far. Do you think there is a Python level workaround? 

There have been so many fudges to workaround servers that don't conform to the spec, that I don't want to be thwarted by an OS bug now!

**Comment by gpcimino** [comment]
I am thinking more to OS level workaround (see link in my post).
I will try from another workstation, I still not 100% sure. 
I will let you know.
GP

**Comment by gpcimino** [comment]
BTW when do you plan to close PR #22 ?

**Comment by willmcgugan** [comment]
Just had a quick look. There are a few failing tests from Travis CI. Do you have permissions to view this? https://travis-ci.org/PyFilesystem/pyfilesystem2/builds/213765384

In general though, I was happy with the changes. Good contribution.

**Comment by gpcimino** [comment]
Yes, I noted the failing tests as well.
However it looks a bit strange to me: with py3.3 tests are green, with the other python versions tests are red (included py3.5).
On my work station (py3.5) all tests are ok. Strange right?
I have no experience at all with travis. 
Do you have any suggestion?
GP

**Comment by willmcgugan** [comment]
There is an error on Py2.7 that should be a quick fix. The `exist_ok` parameter on `os.makerdirs' was introduced in Python3.

The other error...

```
Traceback (most recent call last):
  File "/home/travis/build/PyFilesystem/pyfilesystem2/tests/test_copy.py", line 163, in test_copy_fs_if_newer_dst_older
    self.assertEqual(copied, ["/file1.txt"])
AssertionError: Lists differ: [] != ['/file1.txt']
Second list contains 1 additional elements.
First extra element 0:
'/file1.txt'
```

Is more puzzling. I haven't looked in to it. But I suspect its a problem with timing in your code to test timestamps. Maybe a difference in timestamp granularity in the containers that Travis uses?

**Comment by gpcimino** [comment]
I can fix exist_ok parameter on `os.makerdirs'.

For the second error, i had the same thought, that's why i inserted the time.sleep() call in the test methods few commit ago, do you remeamber? 

I can try to reintroduce the sleep() even if i don't like it, tests should be fast.
Otherwise, is there any option to debug on trevis (e.g. write a log file a can check later)?
GP

PS: we should switch to the PR forum thread! ;-)
