### ISSUE TITLE
BulkCopy in Mirror does not raise on failures

### ISSUE THREAD

**Issue by geoffjukes** [PyFilesystem/pyfilesystem2#240]
Hi,

There is a bug in the `mirror` code when using the `workers` parameter and FTP targets, whereby copy failures do not bubble up properly, and the overall process appears to be 'successful'

I haven't had time to do any debugging yet (that will come tomorrow) and so I cannot be 100% sure if this is an issue with FTPFS, or the `mirror` code.

Setting the `workers` value to anything other than 0, results in an incomplete mirror, with no exception thrown. I have seen the issue on several different FTP servers

I use the `mirror` function inside an Nameko service, which makes use of Eventlet. I don't think that is related to the issue of exceptions not causing the `mirror` to throw an exception (as I would have expected). However, I do wonder if the FTP connections are being prematurely terminated because something in the worker pool is blocking the event loop.

I'll dig more in the morning, but wanted to get this out there as quickly as possible.

Many thanks, 

Geoff

**Comment by willmcgugan** [comment]
Hi Geoff,

What *should* happen is that if a copy fails, the `Copier` context manager in _bulk.py with throw a `BulkCopyFailed` exception if there are any copy related errors.

If that's broken, it would certainly explain what you have seen. So I'd probably start there with the debugging. Maybe errors are getting swallowed somehow.

Good luck with the debugging. Let me know if I can assist.

Will

**Comment by geoffjukes** [comment]
@willmcgugan I have managed to get the `Copier` to throw a `BulkCopyFailed` 3 times. but it's certainly not consistent. I have a lot more digging to do. The codeblock that threw the `BulkCopyFailed` is the same one that I know was not throwing. So I am starting to lean towards it being an issue in FTPS, or the upstream FTP.

I use CrushFTP as a gateway, and this is what it shows for a 'bad' (but not failed, apparently) File transfer:

```
SESSION|12/16/2018 17:17:01.453|[FTP:lookup:21][168365] Accepting connection from: 172.16.10.74:52120
SESSION|12/16/2018 17:17:01.454|[FTP:168365::172.16.10.74] READ : *USER auto.ftp*
SESSION|12/16/2018 17:17:01.457|[FTP:168365:auto.ftp:172.16.10.74] WROTE: *331 Username OK.  Need password.*
SESSION|12/16/2018 17:17:01.457|[FTP:168365:auto.ftp:172.16.10.74] READ : *PASS*
SESSION|12/16/2018 17:17:01.510|[FTP:168365:auto.ftp:172.16.10.74] WROTE: *230 Password OK.  Connected. logged in*
SESSION|12/16/2018 17:17:01.511|[FTP:168365:auto.ftp:172.16.10.74] READ : *FEAT *
SESSION|12/16/2018 17:17:01.511|[FTP:168365:auto.ftp:172.16.10.74] WROTE: *211-Extensions supported:*
SESSION|12/16/2018 17:17:01.511|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * SSCN*
SESSION|12/16/2018 17:17:01.511|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * PBSZ*
SESSION|12/16/2018 17:17:01.511|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * PROT*
SESSION|12/16/2018 17:17:01.511|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * CCC*
SESSION|12/16/2018 17:17:01.511|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * CLNT*
SESSION|12/16/2018 17:17:01.511|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * EPSV*
SESSION|12/16/2018 17:17:01.511|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * EPRT*
SESSION|12/16/2018 17:17:01.511|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * MDTM*
SESSION|12/16/2018 17:17:01.511|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * MDTM YYYYMMDDHHMMSS[+-TZ];filename*
SESSION|12/16/2018 17:17:01.512|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * MFMT*
SESSION|12/16/2018 17:17:01.512|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * SIZE*
SESSION|12/16/2018 17:17:01.512|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * REST STREAM*
SESSION|12/16/2018 17:17:01.512|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * MODE Z*
SESSION|12/16/2018 17:17:01.512|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * LIST -Q*
SESSION|12/16/2018 17:17:01.512|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * SITE UTIME*
SESSION|12/16/2018 17:17:01.512|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * SITE MD5*
SESSION|12/16/2018 17:17:01.512|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * XMD5*
SESSION|12/16/2018 17:17:01.512|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * SITE MD5s*
SESSION|12/16/2018 17:17:01.512|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * SITE RANDOMACCESS*
SESSION|12/16/2018 17:17:01.512|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * MLST Type*;Size*;Modify*;Perm*;UNIX.owner*;UNIX.group*;*
SESSION|12/16/2018 17:17:01.512|[FTP:168365:auto.ftp:172.16.10.74] WROTE: * UTF8*
SESSION|12/16/2018 17:17:01.512|[FTP:168365:auto.ftp:172.16.10.74] WROTE: *211 END*
SESSION|12/16/2018 17:17:01.552|[FTP:168365:auto.ftp:172.16.10.74] READ : *TYPE I*
SESSION|12/16/2018 17:17:01.553|[FTP:168365:auto.ftp:172.16.10.74] WROTE: *200 Command ok : Binary type selected.*
SESSION|12/16/2018 17:17:17.450|[FTP:168365:auto.ftp:172.16.10.74] READ : *PASV *
SESSION|12/16/2018 17:17:17.450|[FTP:168365:auto.ftp:172.16.10.74] WROTE: *227 Entering Passive Mode (172,16,10,11,166,162)*
SESSION|12/16/2018 17:17:17.452|[FTP:168365:auto.ftp:172.16.10.74] READ : *REST 0*
SESSION|12/16/2018 17:17:17.452|[FTP:168365:auto.ftp:172.16.10.74] WROTE: *350 Restarting at 0. Send STORE or RETRIEVE to initiate transfer.*
SESSION|12/16/2018 17:17:17.453|[FTP:168365:auto.ftp:172.16.10.74] READ : *STOR /outgoing/storage/audio/9781538535141-Mission_Entrepreneur/9781538535141_45-45.mp3*
SESSION|12/16/2018 17:17:21.454|[FTP:168365:auto.ftp:172.16.10.74] WROTE: *150 Opening BINARY mode data connection.  Ready to write file /outgoing/storage/audio/9781538535141-Mission_Entrepreneur/9781538535141_45-45.mp3. "/outgoing/storage/audio/9781538535141-Mission_Entrepreneur/9781538535141_45-45.mp3") S T O R*
SESSION|12/16/2018 17:17:26.777|[FTP:168365:auto.ftp:172.16.10.74] READ : *QUIT *
SESSION|12/16/2018 17:17:31.981|[FTP:168365:auto.ftp:172.16.10.74] WROTE: *221 Goodbye.*
SESSION|12/16/2018 17:17:31.982|[168365:auto.ftp:172.16.10.74] WROTE: Error with files (path):/outgoing/naxos/audio/9781538535141-Mission_Entrepreneur/
SESSION|12/16/2018 17:17:31.982|[168365:auto.ftp:172.16.10.74] WROTE: Error with files (name):9781538535141_45-45.mp3
SESSION|12/16/2018 17:17:32.415|[FTP:168365:auto.ftp:172.16.10.74] *Disconnected.*
```
I'm going to open a ticket with their support, see if they have any thoughts.

**Comment by geoffjukes** [comment]
@willmcgugan I wonder if you can help. I've been puzzling over why the `workers=0` copy processes throw errors properly for me, and I can see the following:

https://github.com/PyFilesystem/pyfilesystem2/blob/335e40b0594df0ecb87107250a39be6d7e5f7d7b/fs/_bulk.py#L129 is where you make the split. No workers, and you call `copy.copy_file_internal` - which ultimately calls `setbinfile` on the dst_fs instance (at least in my use-case) ihttps://github.com/PyFilesystem/pyfilesystem2/blob/335e40b0594df0ecb87107250a39be6d7e5f7d7b/fs/copy.py#L177 This method works for me - it either completes 100%, or it throws an error. 

However, if there are workers (and therefore a queue) you add a `CopyTask` which uses `tools.copyfiledata` with a chunk size https://github.com/PyFilesystem/pyfilesystem2/blob/335e40b0594df0ecb87107250a39be6d7e5f7d7b/fs/_bulk.py#L66 which itself uses the `read` and `write` methods on the src and dst fs instances https://github.com/PyFilesystem/pyfilesystem2/blob/335e40b0594df0ecb87107250a39be6d7e5f7d7b/fs/tools.py#L52 This method appears to NOT work for me. It results in random incomplete files with no exceptions thrown. 

I'm curious as to why you use the different methods. Ultimately, for FTP transfers,  it boils down to:
```
ftp.storbinary( str("STOR ") + _encode(_path, self.ftp.encoding), file)
```
vs
```
self.ftp.transfercmd( str("STOR ") + _encode(self.path, self.ftp.encoding), self.pos)
```
and, it would seem that the last chunk sometimes fails to write, but PyFilesystem has already closed the connection and considera it successful. This is a quirk (I guess) of how my FTP proxy works, but I know `storbinary` only succeeds if the whole file is written. 

On the surface, it looks like using `storbinary` would solve my issues with failures not being detected. 

Thoughts? (apologies for any typos - typed on my phone)

**Comment by willmcgugan** [comment]
Thanks for sleuthing.

The reason there is a different copy method is that `FS.copy` is an atomic operation (i.e. its surrounded by a thread lock). If that is used in a bulk copy, then it would be limited to copying a single file at a time.

Opening two files and doing a simple file copy can be done concurrently, which is why its used for multi-threaded copies.

The `copy_file_data` should in theory do pretty much the same thing as ftplib does in `storbinary`. So I compared FTPFS with the [cpython code](https://github.com/python/cpython/blob/master/Lib/ftplib.py#L488) and I think I have an explanation. Ftplib calls `self.voidresp()` immediately after writing data, but FTPFS doesn't. So FTPFS might be disconnecting before the server has acknowledged it got the data. Which I think is what you have seen. 

Could you try calling `self.ftp.voidresp()` immediately before the return in `FTPFile.write`?

**Comment by geoffjukes** [comment]
@willmcgugan Progress... self.ftp.voidresp()  https://github.com/geoffjukes/pyfilesystem2/blob/eeea70fa6bb8b86e3b71aa42e4eac33fffc038f1/fs/ftpfs.py#L272
Now I get `BulkCopyFailed` errors, because every file is 1,048,576 bytes big 😁

**Comment by geoffjukes** [comment]
If I move the `voidresp()` call to the `FTPFile.close` method, the files write correctly, but it still throws `BulkCopyFailed` errors.

https://github.com/geoffjukes/pyfilesystem2/blob/25225ccdff6f1f5bc4b1d8d95d0b49260acc0dd7/fs/ftpfs.py#L193

**Comment by geoffjukes** [comment]
@willmcgugan I moved `self.ftp.voidresp()` to the `FTPFile.close` method, which seems to have done the trick. PR incoming

**Comment by geoffjukes** [comment]
I have confirmed that a `mirror` process with multiple workers will either complete successfully OR raise a `BulkCopyFailed` exception.

Copy errors are now only caused by remote connectivity issues, rather than a premature `quit` command. I have been able to confirm this via an interim/proxy FTP server.

**Comment by willmcgugan** [comment]
Fix is in v.2.1.3, just released. Merry xmas!
