### ISSUE TITLE
How to approach size limiting

### ISSUE THREAD

**Issue by mplebanski** [PyFilesystem/pyfilesystem2#251]
As in the title. I'm looking for advice on how to implement size limiting e.g. TempFS I want to make sure that I do not exceed preset limit of 1GB.

**Comment by willmcgugan** [comment]
Have a look at [fs.wrapfs](https://github.com/PyFilesystem/pyfilesystem2/blob/master/fs/wrapfs.py). This will allow you to take an existing filesystem and add in checks for the total size. I guess you would wrap any methods which could increase the amount of data stored, and throw an exception if it exceeds that size.

**Comment by mplebanski** [comment]
Thanks
