### ISSUE TITLE
importing a module from FTP..possible?

### ISSUE THREAD

**Issue by humblerme** [PyFilesystem/pyfilesystem2#254]
I can't seem to make it work. Is this feature inherently unimplemented?
Regardless my deep appreciation for this wonderful utility, thank you.

**Comment by willmcgugan** [comment]
FTP should work fine. Can you give me an example of what you have tried so far?

**Comment by willmcgugan** [comment]
Going to close this ticket. But feel free to add a comment if you're still having issues...
