### ISSUE TITLE
AttributeError: 'OSFS' object has no attribute 'readtext'

### ISSUE THREAD

**Issue by versaille** [PyFilesystem/pyfilesystem2#255]
as title, error out if run 
home_fs = OSFS("~/")
home_fs.readtext(u'somefile.txt', encoding=u'utf-8')

**Comment by willmcgugan** [comment]
I suspect you're not running the latest version. gettext was renamed to readtext in 2.2.0

**Comment by versaille** [comment]
Thanks a lot, you are right, it works by changing the version.
