### ISSUE TITLE
ZipFS (Writing Mode) Error on Windows

### ISSUE THREAD

**Issue by merlink01** [PyFilesystem/pyfilesystem2#256]
Python 35 (32Bit)
Pyfilesystem: 2.2.1

Testcode:
```
from fs import zipfs
testfs = zipfs.ZipFS('test.zip',write=True)
testfile = testfs.open('testfile.txt','w')
testfile.write('Hello World')
testfile.close()
testfs.close()
```

Result: An empty ZipFile is created.

After looking in the code I saw a Try,Finally around 
self.write_zip() (zipfs.py:239)

This is really bad, because here a Silent Error + Data Loss happened.

After disabling the Try Finally I got this Error:

```
Traceback (most recent call last):
  File "error.py", line 7, in <module>
    testfs.close()
  File "C:\Python35-32\lib\site-packages\fs\zipfs.py", line 239, in close
    self.write_zip()
  File "C:\Python35-32\lib\site-packages\fs\zipfs.py", line 271, in write_zip
    encoding=encoding or self.encoding,
  File "C:\Python35-32\lib\site-packages\fs\compress.py", line 61, in write_zip
    for path, info in gen_walk:
  File "C:\Python35-32\lib\site-packages\fs\walk.py", line 385, in info
    for _path, info in _walk:
  File "C:\Python35-32\lib\site-packages\fs\walk.py", line 405, in _walk_breadth
    for info in self._scan(fs, dir_path, namespaces=namespaces):
  File "C:\Python35-32\lib\site-packages\fs\walk.py", line 277, in _scan
    for info in fs.scandir(dir_path, namespaces=namespaces):
  File "C:\Python35-32\lib\site-packages\fs\osfs.py", line 459, in _scandir
    for dir_entry in scandir(sys_path):
TypeError: os.scandir() doesn't support bytes path on Windows, use Unicode instead
```

Any Idea what I can do to get a zipfile created?

**Comment by merlink01** [comment]
OK, Tested on Python 37 (32Bit) and it works.

**Comment by willmcgugan** [comment]
Not sure why the try/finally would hide any errors there.

I think the issue boils down to this section I found in the docs:

> On Unix, path can be of type str or bytes (use fsencode() and fsdecode() to encode and decode bytes paths). On Windows, path must be of type str. On both systems, the type of the name and path attributes of each DirEntry will be of the same type as path.

So it looks like Windows may need a special case there.

I've tagged this as a bug. In the short term, you could try a 'pip uninstall scandir'.

**Comment by willmcgugan** [comment]
> OK, Tested on Python 37 (32Bit) and it works.

Curious. Maybe the issue is in the backport of scandir.

**Comment by merlink01** [comment]
This could be, so I'll simply switch to python 37.
But the "Try Finally" should be changed to not hide Errors in writing :-)

**Comment by willmcgugan** [comment]
> But the "Try Finally" should be changed to not hide Errors in writing :-)

try/finally shouldn't mask exceptions, so I'm at a loss to explain the behaviour you have seen.

**Comment by merlink01** [comment]
Hmmm, strange... now I get the Exception.
Seems fine-
