### ISSUE TITLE
OSFS.movedir() did not work 

### ISSUE THREAD

**Issue by versaille** [PyFilesystem/pyfilesystem2#257]
after this operation osfs.movedir(u'/dir1/dir2', u'/') there was no u'/dir2' , didn't I use it right or this method doesn't work? Thanks!

**Comment by willmcgugan** [comment]
Think of the movedir method as moving the contents in to the destination. So your code above would move the contents of dir2 in to the root.

I'm guessing you need something like the following: 

```python
movedir('/dir1/dir2', '/dir2', create=True)
```

The create switch is required if dir2 doesn't exist.
