### ISSUE TITLE
[License] Old license in setup.py

### ISSUE THREAD

**Issue by althonos** [PyFilesystem/pyfilesystem2#26]
Hi Will,
just so you know, the license stated in setup.py (and therefore displayed on PyPI) is the one from the old Pyfilesystem (BSD) and not the current one (MIT).

**Comment by willmcgugan** [comment]
Thanks. fixed.

**Comment by althonos** [comment]
@willmcgugan : actually not, you changed the PyPI classifier but not the actual `license` parameter in the `setup.py` 😄

**Comment by willmcgugan** [comment]
fixed in master
