### ISSUE TITLE
Disable Sandboxing?

### ISSUE THREAD

**Issue by kmader** [PyFilesystem/pyfilesystem2#260]
Is there a way to disable sandboxing (`IllegalBackReference`) so files in parent directories can be accessed? The way I currently setup projects the notebooks are 
```bash
.
  |-data
  |  |-data_1.csv
...
  |-notebooks
  |  |-analysis_1.ipynb
  |  |-analysis_2.py
```

And like this they cannot be accessed since the path would be `../data/data_1.csv` from the analysis script. I am using FS more for the versatility of backends like ZipFS than for the security model.

**Comment by willmcgugan** [comment]
With an OSFS you *could* work around it by getting the syspath, but I wouldn't advise it.

The simplest solution may be to pass in a separate FS object for your `data` and `notebooks` directory.

Alternatively you might want to look at a [MountFS](https://docs.pyfilesystem.org/en/latest/reference/mountfs.html). You could create a single virtual filesystem with your data directory mounted on `/data` and notebookes mounted on `/notebooks`.

**Comment by kmader** [comment]
Thanks for the quick response! 

By the syspath, did you mean trying to `os.path.abspath` for whatever reason that caused the file not to be found any more. 

Unfortunately the second solution isn't really an option because OSFS is deeply integrated into another tool we are using and reimplementing it is probably too much work.

**Comment by willmcgugan** [comment]
If you call [syspath](https://docs.pyfilesystem.org/en/latest/concepts.html#system-paths) that will give you the local path to the root of the filesystem. You could then use that to open another OSFS. Something like `OSFS(os.path.join(sys_path, ".../data"))`.

Generally I wouldn't reccomend that because you are restricting your code to only working with the local filesystem. It will likely break if the project you are working with gives you anything other than an OSFS.

**Comment by kmader** [comment]
So I tried that and get 
```py
from fs.osfs import OSFS
import os
home_fs = OSFS('.')
loc = '../data/my_file.pth'
loc_full_path = os.path.join(home_fs.getsyspath(''), loc)
home_fs.open(loc_full_path, 'rb')
```

and get 
```bash
ResourceNotFound: resource '/Users/kmader/Documents/fs_proj/notebooks/../my_file.pth' not found
```

while running
```py
with open(loc_full_path, 'rb') as test_file:
    print(test_file)
```

works fine

**Comment by willmcgugan** [comment]
The OSFS constructor takes the top level directory that you want to manage. So when you do `OSFS('.')` you create a filesystem that can manage files under the current working directory. If you want to manage a files relative to that root but not under it, you can construct a new OSFS with the derived path.

Something like the following should do what you need...

```python
from fs.osfs import OSFS
import os
home_fs = OSFS('.')
loc = '../data/'
loc_full_path = os.path.join(home_fs.getsyspath('/'), loc)
data_fs = OSFS(loc_full_path)  # <-- Constructed with a directory path
data_fs.tree()
with data_fs.open('/my_file.pth') as test_file:  # <-- All paths are now treated as relative to loc_full_path
    print(test_file)
```

**Comment by kmader** [comment]
Thanks, this has cleared it up!
