### ISSUE TITLE
New Filesystem GithubFS

### ISSUE THREAD

**Issue by merlink01** [PyFilesystem/pyfilesystem2#261]
https://github.com/merlink01/fs.github

For editing files directly in Github. (early Stage)

**Comment by zopyx** [comment]
Exactly the thing that I intended to develop on my own :)

**Comment by merlink01** [comment]
Hi @zopix,
the groundwork is done... 
listdir+getinfo is running, next step is open. Some help is always welcome ;-)
Also its not easy to test, there is no possibility to create a github testaccount.

**Comment by willmcgugan** [comment]
@merlink01 I think you have a few people excited about this one.

Going to close the issue. Could you keep us updated re progress on the mailing list?

**Comment by willmcgugan** [comment]
@jayvdb ☝️

**Comment by jayvdb** [comment]
Awesome. My use case is readonly access , but i need at least gitlab support also, and ideally 'git' support
