### ISSUE TITLE
non-ascii characters not accepted in filenames

### ISSUE THREAD

**Issue by simonm3** [PyFilesystem/pyfilesystem2#262]
The following copy_file fails. Same with copy_dir if a filename contains non-ascii characters.

`copy_file(s3, "job-data/job-453/13 – Marked Register.pdf", local, "job-data/job-453/13 – Marked Register.pdf")
`
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-13-c5d4e6cd8643> in <module>
----> 1 copy_file(s3, "job-data/job-453/13 – Marked Register.pdf", local, "job-data/job-453/13 – Marked Register.pdf")

/anaconda3/lib/python3.6/site-packages/fs/copy.py in copy_file(src_fs, src_path, dst_fs, dst_path)
    138                 with _src_fs.lock(), _dst_fs.lock():
    139                     if _dst_fs.hassyspath(dst_path):
--> 140                         with _dst_fs.openbin(dst_path, "w") as write_file:
    141                             _src_fs.getfile(src_path, write_file)
    142                     else:

/anaconda3/lib/python3.6/site-packages/fs/osfs.py in openbin(self, path, mode, buffering, **options)
    320         self.check()
    321         _path = self.validatepath(path)
--> 322         sys_path = self._to_sys_path(_path)
    323         with convert_os_errors("openbin", path):
    324             if six.PY2 and _mode.exclusive and self.exists(path):

/anaconda3/lib/python3.6/site-packages/fs/osfs.py in _to_sys_path(self, path)
    164         """
    165         sys_path = fsencode(
--> 166             os.path.join(self._root_path, path.lstrip("/").replace("/", os.sep))
    167         )
    168         return sys_path

/anaconda3/lib/python3.6/os.py in fsencode(filename)
    800         filename = fspath(filename)  # Does type-checking of `filename`.
    801         if isinstance(filename, str):
--> 802             return filename.encode(encoding, errors)
    803         else:
    804             return filename

UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 24: ordinal not in range(128)

**Comment by willmcgugan** [comment]
Hi,

For some reason it's failing to encoding the mdash character in the filename. What is strange is that it is encoding it as ascii. 

What platform is this on?

Could you try the following and let me know what the result is:

```python
>>> import sys
>>> sys.getfilesystemencoding()
```

Could you also let me know what is in your environment:

```python
>>> import os
>>> os.environ
```

**Comment by simonm3** [comment]
getfilesystemencoding returns ascii. environ as below. it is a docker
container based on ubuntu linux.

environ({'LS_COLORS':
'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:',
'HOSTNAME': '8d7f07854cd0', 'LUIGI_CONFIG_PATH':
'/root/worker/config/luigi.cfg', 'PWD': '/', 'HOME': '/root', 'CONDA':
'/anaconda3', 'TERM': 'xterm', 'REGISTR_CONFIG': '/root/worker/config',
'SHLVL': '1', 'PYTHONPATH': ':/root/worker', 'PATH':
'/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
'JUPYTER_CONFIG_DIR': '/root/worker/config/.jupyter', '_':
'/anaconda3/bin/python', 'OLDPWD': '/root'})

**Comment by willmcgugan** [comment]
Ah. I think ultimately the encoding issue is because you are missing the `LANG` env variable, which for me is set to 'en_GB.UTF-8'. You'll probably file you'll get the same encoding issues on any Python code that reads or writes non-ascii filenames, not just PyFilesystem.

**Comment by simonm3** [comment]
Yes just found this. Seems I need to explicitly set LANG="C.UTF-8"

https://stackoverflow.com/questions/44344458/why-does-locale-getpreferredencoding-return-ansi-x3-4-1968-instead-of-utf-8
