### ISSUE TITLE
ZipFS(io.StringIO()...) -> TypeError

### ISSUE THREAD

**Issue by zopyx** [PyFilesystem/pyfilesystem2#264]
fs 2.2.1
Python 3.6

The following code used to work with Python 2.7, fs 0.5:

```

            zip_fp = StringIO()
            ZF = fs.zipfs.ZipFS(zip_fp, 'w')
            for name in os.listdir(workdir):
                with ZF.open(name, 'wb') as fp_out:
                    fp_out.write(
                        open(os.path.join(workdir, name), 'rb').read())
            ZF.close()

```

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 128, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 276, in publish_module
  Module ZPublisher.WSGIPublisher, line 210, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 57, in call_object
  Module onkopedia.policy.browser.onkopedia_view, line 722, in generate_pdf
  Module onkopedia.policy.browser.onkopedia_view, line 829, in _generate_pdf
  Module fs.zipfs, line 239, in close
  Module fs.zipfs, line 271, in write_zip
  Module fs.compress, line 105, in write_zip
  Module zipfile, line 1174, in __exit__
  Module zipfile, line 1704, in close
  Module zipfile, line 1808, in _write_end_record
TypeError: string argument expected, got 'bytes'

According to the docs I should be able to use  `io.StringIO` hier

**Comment by willmcgugan** [comment]
In Python3, StringIO creates unicode strings, in Python2 it creates byte strings.

Try replacing your `StringIO` with a `io.BytesIO`

**Comment by zopyx** [comment]
You're right
