### ISSUE TITLE
Minor typo on website

### ISSUE THREAD

**Issue by lurch** [PyFilesystem/pyfilesystem2#271]
On https://www.pyfilesystem.org/page/index-of-filesystems/ it says `fs.dnla A filesystem for accessing accessing DLNA Servers.`. The link target is correct, it's just the link description that is wrong - it should be `fs.dlna`. Also, you probably don't need the word `accessing` twice :wink:

**Comment by willmcgugan** [comment]
Thanks @lurch Fixed. :)

**Comment by lurch** [comment]
I really must find time to have another look at pyfilesystem some time - it's been too long! :slightly_smiling_face:

**Comment by willmcgugan** [comment]
We can always use your eye for detail!
