### ISSUE TITLE
Unittesting with PyFilesystem requires tracking a filesystem object

### ISSUE THREAD

**Issue by davidparks21** [PyFilesystem/pyfilesystem2#273]
Arguably one of the best features of PyFilesystem is improved unittesting over code that reads/writes to files, especially across multiple filesystems. However, realizing that benefit means not using `open_fs()` and instead holding onto (and accepting) a filesystem object so that a unittest can easily override the filesystem in use.

It seems like an elegant addition would be to allow the unittest code to offer a global factory method  that allows it to inject its own filesystem when a call to `open_fs()` would trigger the creation of the filesystem, without the target code needing any specific instrumentation to achieve this (which is currently required). 

There are probably a few different ways to achieve this goal, my point is not to suggest a particular implementation, rather to bring to light to the idea that the unittest use case could benefit from such a feature.

**Comment by willmcgugan** [comment]
That is somewhat doable at the moment. There is a registry object which maps schemes on to `Opener` objects which return a filesystem instance. That could be monkey patched with a little effort.

It is a good idea, and might be worth adding an explicit interface, or at least documenting a best practice.

@althonos May have some suggestions here.

**Comment by willmcgugan** [comment]
I think mocking `open_fs` is possible a good a solution as any for unit testing.

Closing this issue for now, but I'm open to revisiting this.
