### ISSUE TITLE
I'm wondering the whether the 'expose' will be ever implemented

### ISSUE THREAD

**Issue by NyaMisty** [PyFilesystem/pyfilesystem2#274]
In #17, we've discussed the expose functionality, and it's said that it would be implemented in a separate package. But it already half past a year now, and dokan support is still under development. Recently, the fs.expose repo was even archived by the owner @althonos.
Would you implement these features in the near future?

**Comment by willmcgugan** [comment]
I'm sure you'll appreciate that it is a fair amount of work to build and maintain a package such as `fs.expose`, especially if its done in dev's free time. Personally I would like to work on it, but can't allocate the time, and that's not likely to change any time soon. 

I do work freelance, so could offer you commercial support if you're interested. @althonos may be in a similar position...

**Comment by NyaMisty** [comment]
Oh I did't mean to push you! Sorry for my poor English vocabulary.
I'm just wondering whether it will developed officially, if not then I'll start to port it myself ;)

**Comment by NyaMisty** [comment]
Also, if I do want to work on the fs.expose module, how should I do? Will you open an official repo under this account?

**Comment by willmcgugan** [comment]
It would be great if you want to tackle it. I'd go ahead with a repos under your account. I can add it to the wiki when you're ready, and perhaps even link to it in the docs.

Could you call it `fs-<something>`? I'd like to reserve `fs.` for namespace packages. And you might want to break it in to individual packages. Perhaps `fs-fuse` for linux, `fs-dokan` for Windows, etc...

**Comment by NyaMisty** [comment]
Okay I'll pick up the dokan as I'm more familiar with Windows, also there's already others work. I'll try to debug the merlink01's fork first :)

**Comment by althonos** [comment]
The `fs.expose` repo is archived but it doesn't mean you can't using as a starting point. The two main things that did prevent me from making any progress were that:

* I don't have a Windows development platform I can use, so I can't work on `fs.dokan`
* The `fusepy` library I used for `fs.fuse` was *extremely* unstable and not so well documented, so whenever I had some trial and error to do most of the time my computer would just crash and I'd have to restart everything, making the code/test/refactor loop 10 times longer.

**Comment by merlink01** [comment]
Hi @ all,
Im also testing a little bit.
First, it would be nice to split the expose package to different parts like filesystems do. An Idea is to create a meta package lie fs.expose . so we can create subpackages like fs.expose.dokan fs.expose.http ... 
The fs.expose meta package could also be part of pyfilesystem itsself?

**Comment by NyaMisty** [comment]
Hi @merlink01,
that's the decision long before, but it seems that it would be a separated package.
Also I've tested your dokan port for pyfs2, and it works like a charm. I've fixed some minor bug and I'll try to separate it into dedicated package after some more tests and make it support dokan 1.2

**Comment by merlink01** [comment]
Hi @NyaMisty,
that would be great, do you already have a repository for this?

**Comment by NyaMisty** [comment]
Sorry I'm still testing locally and it's still crashing from time to time :(

**Comment by merlink01** [comment]
OK, simply write if you are ready :-)

**Comment by Liryna** [comment]
Looking forward into this. Will update the link on dokan wiki.

**Comment by JuniorJPDJ** [comment]
http://www.secfs.net/winfsp/ - This is faster than dokan!
Also I can provide Windows virtual machine if you need one.
There are also free windows preinstalled vms to download for developers if it will satisty you: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by CMCDragonkai** [comment]
Wondering why this issue is closed. I would like to see this as well.
