### ISSUE TITLE
Request: RClone backend?

### ISSUE THREAD

**Issue by Jwink3101** [PyFilesystem/pyfilesystem2#277]
I recognize that RClone as a backend is an abstraction on something of an abstraction. But since rclone supports a *ton* of object storage systems, it would be great to see that as a backend opening up a lot of additional cloud storage providers.

I may take a shot at it myself but it may be faster for someone who is more familiar with the details

**Comment by willmcgugan** [comment]
I'm not familiar with RClone, but it sounds like a fantastic idea. I won't have the time to work on it, but if you want to tackle it yourself, I would be happy to advise!

**Comment by willmcgugan** [comment]
Going to close this for now. If you do decide to tackle it, let me know if you need any assistance.
