### ISSUE TITLE
FS.setfile was removed without a deprecation

### ISSUE THREAD

**Issue by hkethi002** [PyFilesystem/pyfilesystem2#278]
All of the other functions in [this change](https://github.com/PyFilesystem/pyfilesystem2/commit/d6cf403d0b6d7a56f0acf22eec3a05d945f6c161#diff-3320961fe7bc890ab68b6043e4de3c39) seemed to have remained (aliased to the new functions) with deprecation warnings, I was wondering if this was missed for setfile? The name change for this function is also missing from the Change log.

**Comment by willmcgugan** [comment]
That was an oversight. `setfile` has been renamed to `writefile`. I'll look in to retroactively implementing the deprecation warning.

**Comment by willmcgugan** [comment]
Fixed in v2.4.5
