### ISSUE TITLE
Bug in OSFS Init Path conversion

### ISSUE THREAD

**Issue by merlink01** [PyFilesystem/pyfilesystem2#279]
Original Path to access:
Windows Path: T:\\$tmp

After Adding some Prints to osfs.py [120]:
```
        print(_drive, _root_path)
        _root_path = _drive + (_root_path or "/") if _drive else _root_path
        print(_root_path)
        _root_path = os.path.expanduser(os.path.expandvars(_root_path))
        print(_root_path)
        _root_path = os.path.normpath(os.path.abspath(_root_path))
        print(_root_path)
```

We can see what happenes to my path:
```
T: \$tmp\
T:\$tmp\
T:\C:\Users\userdir~1\AppData\Local\Temp\
T:\C:\Users\userdir~1\AppData\Local\Temp
```

So it seems: 
os.path.expanduser should only be called if there is no abspath (or drive on windows) given?

**Comment by lurch** [comment]
Nope, looks like it's https://docs.python.org/3.5/library/os.path.html#os.path.expandvars that's "messing things up", rather than `os.path.expanduser`. Seems like Python interprets `T:\$tmp` on Windows as identical to `T:\%TMP%`

P.S. Could you put backticks around your output please, to stop GitHub mistakenly adding strike-through formatting?

**Comment by merlink01** [comment]
@lurch , yes you are right.

**Comment by willmcgugan** [comment]
I'm not sure what the correct change is here, if any.

@merlink01 I'm guessing you wanted the expansion of `$tmp` to occur, and the env var was just set wrong?

Oddly `os.expandvars` doesn't support any escape mechanism, so if you wanted a literal `$` in your path, I don't think you could do it.

@lurch thoughts?

**Comment by merlink01** [comment]
Hi @willmcgugan, in this case the path comes from a wx folder open dialog, so I know there is an absolut path given that doesnt need any conversion.
So it would be nice to have a parameter opening the osfs disabling this expandvars function.

**Comment by willmcgugan** [comment]
I've added a flag to disable env var expansion (https://github.com/PyFilesystem/pyfilesystem2/pull/293)
