### ISSUE TITLE
ModuleNotFoundError: No module named 'fs.tarfs'

### ISSUE THREAD

**Issue by fbigun** [PyFilesystem/pyfilesystem2#28]
system:   windows10 bash

alabaster==0.7.9
appdirs==1.4.0
argh==0.26.2
Babel==2.3.4
docutils==0.13.1
enum34==1.1.6
fs==2.0.0
imagesize==0.7.1
Jinja2==2.9.5
MarkupSafe==0.23
packaging==16.8
pathtools==0.1.2
Pygments==2.2.0
pyparsing==2.1.10
pytz==2016.10
PyYAML==3.12
requests==2.13.0
scandir==1.5
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.5.2
sphinx-rtd-theme==0.1.9
watchdog==0.8.3

**Comment by fbigun** [comment]
After the upgrade version has been successfully resolved

**Comment by willmcgugan** [comment]
It's a recent addition... :+1:
