### ISSUE TITLE
FTPFS: too many connections when using upload()?

### ISSUE THREAD

**Issue by nuschk** [PyFilesystem/pyfilesystem2#283]
It looks to me, as if `upload()` will always open up a new connection to the target server, when, in theory, it could re-use the existing one. Is this intentional? 

If yes, how can we circumvent it? I guess `open()`, then `write()` should do it, no?

We're using FTPFS to upload quite a few files to other parties' servers and we've got a few complaints on the number of connections we're using for this.

Thanks!

**Comment by willmcgugan** [comment]
FTPFS keeps a connection open for directory listing, and `upload` will open a new connection for each upload (but close it afterwards). So you should have only 2 connections open at any given time. If you use `open()` and `write()` it will open a connection for every file object.

It's not normally an issue for FTP servers to make multiple requests like this. Do you know why it is a problem for other parties' server?

There's no way to make FTPFS re-use connections for uploads at the moment, but it would be possible to implement. It's just a bit of work, so I'd want to be sure there is a strong use case for it...

**Comment by nuschk** [comment]
Well, I don't know if it's a *strong* usecase. But, we upload many files, and, sometimes, the opening a new connection will fail because the receiving server can't handle it, I guess (?). Seems like that's the most sensitive part regarding robustness. And, we really had someone on the receiving end complain about those connections. I don't understand what's causing their pain. I guess, as always in the FTP world, they just work with ancient stuff...

If it's not fixed (which I'd understand), I will add a retry. If the connection error isn't persistent, this should at least get our uploads to work consistently.

**Comment by willmcgugan** [comment]
Ah I see. Sounds like retrying would generally fix things.

I am open to the idea of reusing a connection to upload many files--new connections do incur a fraction of a second delay.

Let me know how the retry mechanism works out...

**Comment by nuschk** [comment]
Retry works. 

Given that I don't really know if connection re-use would really improve the situation (I still *think* it would), and given it's nothing we can't work around (using a retry), I'll close the issue.

If it continues to bug us (i.e., complaints from receiving parties), I will look into it again and try to put together a pull request. Thanks!
