### ISSUE TITLE
FTPFS: EOFError in listdir

### ISSUE THREAD

**Issue by efuce** [PyFilesystem/pyfilesystem2#292]
Hello,

I am new to pyfilesystem, so please excuse if i might have missed something. From what i can understand from the documentation pyfilesystem2 translates exceptions from the underlying filesystem into a common set of exceptions.

There seems to be a corner case for ftpfs where it might raise EOFError in listdir if the server forcefully closes the connection during the operation. This exception seems to be coming from the underlying ftplib.

**Comment by willmcgugan** [comment]
PyFilesystem methods should translate all exceptions to the common exceptions.

So if listdir is throwing an EOFError, that would be considered a bug. If you have a traceback I could have a look at it, or a PR is always welcome.

**Comment by efuce** [comment]
Traceback:

```python
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    fs.listdir('.')
  File "/usr/lib/python3.7/site-packages/fs/wrapfs.py", line 152, in listdir
    dir_list = _fs.listdir(_path)
  File "/usr/lib/python3.7/site-packages/fs/ftpfs.py", line 628, in listdir
    dir_list = [info.name for info in self.scandir(_path)]
  File "/usr/lib/python3.7/site-packages/fs/ftpfs.py", line 628, in <listcomp>
    dir_list = [info.name for info in self.scandir(_path)]
  File "/usr/lib/python3.7/site-packages/fs/ftpfs.py", line 721, in _scandir
    lambda l: lines.append(_decode(l, self.ftp.encoding)),
  File "/usr/lib/python3.7/ftplib.py", line 467, in retrlines
    resp = self.sendcmd('TYPE A')
  File "/usr/lib/python3.7/ftplib.py", line 273, in sendcmd
    return self.getresp()
  File "/usr/lib/python3.7/ftplib.py", line 236, in getresp
    resp = self.getmultiline()
  File "/usr/lib/python3.7/ftplib.py", line 222, in getmultiline
    line = self.getline()
  File "/usr/lib/python3.7/ftplib.py", line 210, in getline
    raise EOFError
EOFError
```

**Comment by lurch** [comment]
Looks like that's coming from https://github.com/python/cpython/blob/master/Lib/ftplib.py#L210

There appears to be a mismatch as the [ftplib docs](https://docs.python.org/3/library/ftplib.html#ftplib.all_errors) say "This set includes the four exceptions listed above as well as OSError." but the [ftplib code](https://github.com/python/cpython/blob/master/Lib/ftplib.py#L66) says `all_errors = (Error, OSError, EOFError)` :frowning_face:

**Comment by dargueta** [comment]
`Error` is a superclass of the four exceptions so the documentation is correct. However, it looks like we're not catching two of those exceptions, nor `OSError`.

I've tried catching `OSError` but this seems to cause some trouble because it's the superclass of `socket.error` and for some reason changing the order of the except statements isn't working for me.

**Comment by lurch** [comment]
> There appears to be a mismatch...

https://github.com/python/cpython/pull/15026
:grin:
