### ISSUE TITLE
copydir is missing from WrapFS

### ISSUE THREAD

**Issue by rkhwaja** [PyFilesystem/pyfilesystem2#294]
As discussed [here](https://github.com/PyFilesystem/pyfilesystem2/issues/207#issuecomment-409894399), WrapFS has to implement all of methods in order to delegate to it's wrapped filesystem.

copydir and movedir are missing, possibly others in the list of [non-essential methods](https://docs.pyfilesystem.org/en/latest/implementers.html#non-essential-methods)

**Comment by rkhwaja** [comment]
Also missing: movedir, removetree and download (although upload is there!)

**Comment by willmcgugan** [comment]
Fixed in v2.4.9
