### ISSUE TITLE
Incomplete documentation?

### ISSUE THREAD

**Issue by lurch** [PyFilesystem/pyfilesystem2#295]
https://pyfilesystem2.readthedocs.io/en/latest/interface.html says "The following is a complete list of methods on PyFilesystem objects...." and yet it doesn't seem to include e.g. `isdir` or `islink` that https://pyfilesystem2.readthedocs.io/en/latest/reference/base.html does?? (there may be others, I didn't do an exhaustive check)

Should they also be included in the list of https://pyfilesystem2.readthedocs.io/en/latest/implementers.html#non-essential-methods ?

**Comment by willmcgugan** [comment]
Thanks. Fixed in master.
