### ISSUE TITLE
s3fs and azurefs

### ISSUE THREAD

**Issue by sdementen** [PyFilesystem/pyfilesystem2#3]
I see in the previous version you has a s3fs and i was wondering if it was still available but also if there was some azure blob storage fs.

**Comment by willmcgugan** [comment]
S3FS isn't supported yet, but it is on the todo list. S3 is supported in the original PyFilesystem, which will be maintained for some time.

I have no immediate plans to implement Azure blog storage. But it would be a good addition.

**Comment by hevy-CC4477** [comment]
Is S3FS in dev ? if not, If I do it, would you accept it in a PR ?

**Comment by willmcgugan** [comment]
S3FS is currently in beta. See https://github.com/PyFilesystem/s3fs

**Comment by hevy-CC4477** [comment]
Will you merge S3FS in pyfilesystem2 ?

**Comment by willmcgugan** [comment]
No, its indented to be an external package, to keep the dependancies of the core library as lean as possible.

**Comment by bachsh** [comment]
Any news on `azurefs`? we're migrating to Azure blob storage and this could really help us out.

**Comment by willmcgugan** [comment]
@bachsh Looks like there are some third-party options for Azure now https://github.com/PyFilesystem/pyfilesystem2/issues/372

**Comment by bachsh** [comment]
There are two such options for Azure Datalake, and we're using Blob Storage. From what I understood these are not the same, but perhaps we should consider using the datalake instead
