### ISSUE TITLE
Add a method to create a link

### ISSUE THREAD

**Issue by rkhwaja** [PyFilesystem/pyfilesystem2#301]
Google Drive allows a file or folder to have multiple parents and I would like to add a method to fs.googledrivefs that allows adding a new parent to a file and/or create the file with 2 parents in the first place.

I can make a non-pyfilesystem method to do this, of course, and I probably will, but I thought I'd ask if you have any plans for adding support for this - obviously this feature is supported in lots of other filesystems.

**Comment by lurch** [comment]
> obviously this feature is supported in lots of other filesystems.

Hmmmm, I can't think of any other filesystems where a file can have "multiple parents"??
Obviously you can have `dir1/fileA` and a `dir2/linkB -> ../dir1/fileA` symlink, but I don't think that's quite the same as what you're describing here?  (or is it...? I've never used Google Drive.)

**Comment by willmcgugan** [comment]
If we were to add a method to base, it would have to have to be generally supported in other filesystems. 

If you could propose an interface to a new method, with a suggested implementation that works in the existing filesystems, then it's definitely worth considering. From the sound of it though, it suspect it might be too exotic a feature to have an equivalence in the other filesystems.

**Comment by rkhwaja** [comment]
Thinking about it a bit more, Google Drive "hard links" are different from osfs ones in that the filename for the 2 links have to be the same so I'll just do a custom method in googledrivefs
