### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by alan-cugler** [PyFilesystem/pyfilesystem2#302]
### My questions:
 - Can pyfilesystem2 work using python3.7? 
   - A couple issues from 2018 had directly said python3.7 wasnt supported yet because of dependencies.
   - peaking at the `requirements.txt` file I see several dependencies demanding earlier version of python.
 - Is `conda install fs` not the same as `conda install fs -c conda-forge`?
    - `conda search fs` gives me results like: `git-lfs, s3fs, r-sfsmisc, python-hdfs, python-crfsuite, libhdfs3`, etc.

I apologize if these questions are horrible, the docs and other internet material are frying my brain a bit on such fundamental questions.

**Comment by lurch** [comment]
https://github.com/PyFilesystem/pyfilesystem2/blob/master/.travis.yml
https://github.com/PyFilesystem/pyfilesystem2/blob/master/setup.py
https://github.com/PyFilesystem/pyfilesystem2/blob/master/tox.ini
https://github.com/PyFilesystem/pyfilesystem2/blob/master/README.md
all seem to indicate that Python3.7 is supported :smiley: 

I _think_ `typing==3.6.4 ; python_version < '3.5'` in `requirements.txt` is saying "if the python_version is less than 3.5, then the typing module (version 3.6.4) is also required".

I dunno anything about `conda`, I suspect @willmcgugan will need to answer that.

**Comment by willmcgugan** [comment]
Yep, Python 3.7 is supported. 

I'm afraid I'm not a conda user. I think it was @ReimarBauer that set up Conda.

I sometimes regret naming the module `fs`. Sure, its memorable and easy to type in code, but it's not very searchable.

**Comment by lurch** [comment]
I just did a quick search, and it looks like https://stackoverflow.com/questions/39857289/should-conda-or-conda-forge-be-used-for-python-environments contains some useful answers? Specifically "There are packages on the conda-forge channel that aren't available from defaults".

**Comment by alan-cugler** [comment]
@lurch @willmcgugan Thanks for the clarifications. 
From the stackoverflow question I think I will download from the conda-forge. 

Thanks for your help, I will close this ticket but leave my notifications on for it if @ReimarBauer has something to add or clarify from setting up the conda packaging.

**Comment by ReimarBauer** [comment]
Hi @alan-cugler  conda-forge is a [github community](http://conda-forge.org/) and provides packages and also the build infrastructure for all platforms. We have there also some build processes which got triggered by new releases and prepare a new package. I decided in 2016 to add the MSS project to conda-forge because in the 700 available package at that time, qt and some others where there available for all platforms and I could do thx to the sponsors the same with MSS. Later I and a lot others added all projects needed. We have now > 7K packages there.
