### ISSUE TITLE
fs.path not available

### ISSUE THREAD

**Issue by simonm3** [PyFilesystem/pyfilesystem2#304]
In the docs it says fs.path provides operations on generic pyfilesystem filepaths. However it is not available until a filesystem has been opened.

For example I want to carry out a path operation before opening a filesystem but this is not possible. Says "module fs has no attribute path". Once I open a filesystem it works fine.

```
import fs
fs.path
```

**Comment by willmcgugan** [comment]
That did used to work. In the meantime you could do `import fs.path`, but I imagine you figured that out already.

**Comment by dargueta** [comment]
Is there a reason we don't import `path` in the `__init__`?

**Comment by willmcgugan** [comment]
Fixed in master.
