### ISSUE TITLE
Running file from virtual file system

### ISSUE THREAD

**Issue by TheSph1nx** [PyFilesystem/pyfilesystem2#305]
Hello there, I was wondering if it might be possibile running a file such as a binary from inside the virtual file system.

Thank you guys!

**Comment by lurch** [comment]
I'm not sure if this is within the remit of pyfilesystem?
Maybe what you want to do as a workaround is create a TempFS, copy the binary (and any supporting files it might need) from your virtual FS to the TempFS, get the syspath for the binary in the TempFS, and then execute that using standard Python library functions?

**Comment by TheSph1nx** [comment]
Yes actually this was the intent. So executing the binary without touching the disk.

**Comment by willmcgugan** [comment]
I'm afraid it's only likely to work if the binary is already on the OS filesystem, or you copy it there (as @lurch suggested).

Operating systems don't generally permit running binaries from memory, and even if they were to execute, they wouldn't be aware of any software defined filesystem (provided by PyFilesystem).

**Comment by lurch** [comment]
Depending on what OS you're using, maybe you could use some kind of RamDisk solution? But again that'd be outside the functionality of pyfilesystem.

**Comment by JuniorJPDJ** [comment]
Theoretically you could fork your python and replace whole process memory with your executable.

**Comment by JuniorJPDJ** [comment]
PS. just use expose, It'll be easier
