### ISSUE TITLE
Quicker path to docs?

### ISSUE THREAD

**Issue by lurch** [PyFilesystem/pyfilesystem2#306]
If I go to https://www.pyfilesystem.org/ there's a link to "Documentation". If I click it that then goes  to _another_ [page](https://www.pyfilesystem.org/page/documentation/), which finally offers me a link to http://docs.pyfilesystem.org/ (which is where the actual documentation is!)

Could / should this middle step be removed?
Would it make sense for `README.md` to also point to `http://docs.pyfilesystem.org/` instead of `https://pyfilesystem2.readthedocs.io/en/latest/` ?

**Comment by willmcgugan** [comment]
Yeah it probably should. It's just my wiki software lists some promoted pages there and there is currently no way to inject arbitrary links.

> Would it make sense for README.md to also point to http://docs.pyfilesystem.org/ instead of https://pyfilesystem2.readthedocs.io/en/latest/ ?

yes, definitely, I'll change that.

**Comment by willmcgugan** [comment]
Updated the readme

Filed an issue on the [wiki repos](https://github.com/PyFilesystem/pyfilesystem.org/issues/3) for the docs link. TBH though feels like low priority, and I don't know when I'll get to it!

**Comment by lurch** [comment]
> It's just my wiki software lists some promoted pages there and there is currently no way to inject arbitrary links.

Ah, fair enough. From now on I'll just have to remember to access the docs from the GH README, rather than clicking through to pyfilesystem.org :wink: 

Or given that https://www.pyfilesystem.org/page/help/ also contains the link I want, maybe "Help" could be re-titled to "Help / Documentation" and then the "Documentation" page could be removed from the "promoted" list?

BTW I just noticed that the email address listed on https://www.pyfilesystem.org/page/commercial-support/ is slightly different to the one on https://www.pyfilesystem.org/page/contact/ :email: :eyes:
