### ISSUE TITLE
Free memory on MemoryFS.close

### ISSUE THREAD

**Issue by mostafa** [PyFilesystem/pyfilesystem2#308]
Steps to reproduce:

1. Run this piece of code in your favorite REPL.
```python
from fs.memoryfs import MemoryFS

mem_fs = MemoryFS()
with open('large_binary_file', 'rb') as f:
	mem_fs.upload('/large_binary_file', f)
mem_fs.close()
```
2. Watch python process before and after running this script.
3. The memory is there and the files are not removed.
4. Run `del mem_fs` and it immediately claims back the memory.

**Comment by willmcgugan** [comment]
The close method isn't obliged to free up memory when called. Only destruction of the object can guarantee that. That said, freeing up memory on close is probably good idea.

**Comment by mostafa** [comment]
Since you now longer have access to that part of the memory, freeing it up would help reduce memory footprint of some applications.
