### ISSUE TITLE
Expose SubFS factory

### ISSUE THREAD

**Issue by rkhwaja** [PyFilesystem/pyfilesystem2#309]
There are some custom methods (i.e. not overrides) on GoogleFS and OneDriveFS to expose specific features of those filesystems.

My problem is that makedir(s) returns a SubFS which then doesn't support those custom methods so you can't use it transparently (e.g. in the tests)
I see that opendir has a factory parameter so that you can customize the return type, but that's missing from the other SubFS-returning functions.
I'd suggest that we could add the same factory parameter to makedir(s), except that it seems to me that it shouldn't be specified by the user but by the filesystem developer - maybe in the _meta dictionary?
I suppose that another way to do it would be to use the custom factory if the user specifies one but if factory is None, use the GoogleFS-specified one.

What do you think?

**Comment by willmcgugan** [comment]
It could be a class attribute, in the same way that we have a `walker_class`.

In `FS` base there could be: 

```python
subfs_class = SubFS
```

And the SubFS methods would use that value by default.

Would that solve your use case?

**Comment by lurch** [comment]
Looking at the class-hierarchy, does this problem affect WrapFS too, and not just SubFS?

**Comment by rkhwaja** [comment]
> It could be a class attribute, in the same way that we have a `walker_class`.
> 
> In `FS` base there could be:
> 
> ```python
> subfs_class = SubFS
> ```
> 
> And the SubFS methods would use that value by default.
> 
> Would that solve your use case?

Yes - thanks.

**Comment by willmcgugan** [comment]
I've tagged this one to do. Not sure when I'll get to it. Happy to accept a PR if you would like to tackle it.

**Comment by rkhwaja** [comment]
I'll have a shufti
