### ISSUE TITLE
Documentation on ZipFS missing

### ISSUE THREAD

**Issue by edermi** [PyFilesystem/pyfilesystem2#31]
The [Builtin Filesystems](https://pyfilesystem2.readthedocs.io/en/latest/builtin.html) page does not contain ZipFS and I was not able to find any other location with documentation apart from the source (which is fine for me since its very well documented).

**Comment by willmcgugan** [comment]
Thanks. Will fix.

**Comment by willmcgugan** [comment]
https://pyfilesystem2.readthedocs.io/en/latest/reference/zipfs.html
