### ISSUE TITLE
Just learnt the pyfs2 does not support(like) windows path?

### ISSUE THREAD

**Issue by chfw** [PyFilesystem/pyfilesystem2#312]
Hi

Thanks for writing this nice library. I am [evaluating the move to replace os with fs](https://github.com/moremoban/moban/pull/302).

Here is my new findings:

`fs.errors.InvalidCharsInPath: path 'tests\fixtures\simple.yaml' contains invalid characters`

and above path is generated using `os.path.join('tests', 'fixtures', 'simple.yaml')`

Here is our failed build:
https://dev.azure.com/moremoban/moban/_build/results?buildId=491

If the design decision is to drop windows path, what would you recommend we use? unix file path on windows?

Cheers

**Comment by lurch** [comment]
Have a read of https://docs.pyfilesystem.org/en/latest/concepts.html and consider replacing `os.path.join` with [fs.path.join](https://docs.pyfilesystem.org/en/latest/reference/path.html#fs.path.join) :slightly_smiling_face:

**Comment by chfw** [comment]
Thanks for prompt answer!
