### ISSUE TITLE
removedir got an unexpected keyword argument 'force'

### ISSUE THREAD

**Issue by anthrotype** [PyFilesystem/pyfilesystem2#32]
Hello!

How am I supposed to remove a non empty directory with `fs`?
The documentation still says that one can pass `force=True` to `removedir` method:

https://github.com/PyFilesystem/pyfilesystem2/blob/de3e3a9b7a52049275e8b635cb03ae0e000934d0/fs/base.py#L173

However, the signature of the method only takes one `path` argument.

**Comment by anthrotype** [comment]
I see that this `force` argument was originally present in the old pyfilesystem, but has been removed from the API with pyfilesystem2.
So what is the current way to remove non-empty directories if one wishes to use the new pyfilesystem2 API?

**Comment by willmcgugan** [comment]
Have a look at http://docs.pyfilesystem.org/en/latest/reference/base.html?highlight=removetree#fs.base.FS.removetree

**Comment by anthrotype** [comment]
Thanks! 👍
