### ISSUE TITLE
Typo in a recent commit?

### ISSUE THREAD

**Issue by lurch** [PyFilesystem/pyfilesystem2#322]
https://github.com/PyFilesystem/pyfilesystem2/commit/f274b325fac8e47df6d45260111d6517abddde7e adds:
```
    def copydir(self, src_path, dst_path, create=False):
        # stuff
            move_dir(src_fs, _src_path, dst_fs, _dst_path)
```
and also
```
    def copydir(self, src_path, dst_path, create=False):
        # stuff
            copy_dir(src_fs, _src_path, dst_fs, _dst_path)
```

Should the first `def copydir` actually have been `def movedir` ?

**Comment by willmcgugan** [comment]
Good spot, thanks. I'll have a think about better tests for wrapfs.
