### ISSUE TITLE
error on opening directory with `@` symbol

### ISSUE THREAD

**Issue by cmalbrec** [PyFilesystem/pyfilesystem2#324]
Hi `pyfilesystem2`-team:

I came across the following issue when opening a directory in the Linux filesystem tree:

Suppose I create a directory like this:
```Bash
mkdir /tmp/test@mymail.com
```
Executing
```Python
import fs
fs.open_fs(u'/tmp/test@mymail.com/')
```
fails with `CreateFailed: root path does not exist`, while
```Python
import os
os.path.isdir(u'/tmp/test@mymail.com/')
```
returns `True`.

I suspect the path-massaging code https://github.com/PyFilesystem/pyfilesystem2/blob/a57ef8b799c3c63dee43e5f3528de77ba9a9cb83/fs/osfs.py#L119-L127 screws things up. Adding a debug statement to https://github.com/PyFilesystem/pyfilesystem2/blob/a57ef8b799c3c63dee43e5f3528de77ba9a9cb83/fs/osfs.py#L139-L140 tells me that `_root_path` gets modified to become a concatenation of the current directory where the Python code is executed and the piece of the path specified after the `@` symbol.

E.g. if I am executing in `/home/myuser`, `_root_path` turns into `/home/myuser/mymail.com`.

I am using Python `3.5.2` and `pyfilesystem2` version `2.4.10`.

Pls let me know in case I am incorrectly using the `fs.open_fs()` function with special characters. Otherwise, it would be great if that bug could be fixed.

**Comment by cmalbrec** [comment]
*update*: Looks like the path modification happens before the code I quoted above from `OSFS.__init__()`

**Comment by dargueta** [comment]
Try using `osfs:///tmp/test@mymail.com/`, see if that works.

**Comment by cmalbrec** [comment]
nope:
```
$ ~ > ipython
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import fs

In [2]: !ls /tmp/|grep test
test@mail.com

In [3]: fs.open_fs('osfs:///tmp/test@mymail.com/')
---------------------------------------------------------------------------
CreateFailed                              Traceback (most recent call last)
<ipython-input-3-db3cb989ee7a> in <module>()
----> 1 fs.open_fs('osfs:///tmp/test@mymail.com/')

~/software/python/local-python-3/lib/python3.5/site-packages/fs/opener/registry.py in open_fs(self, fs_url, writeable, create, cwd, default_protocol)
    226                 create=create,
    227                 cwd=cwd,
--> 228                 default_protocol=default_protocol,
    229             )
    230         return _fs

~/software/python/local-python-3/lib/python3.5/site-packages/fs/opener/registry.py in open(self, fs_url, writeable, create, cwd, default_protocol)
    187         opener = self.get_opener(protocol)
    188 
--> 189         open_fs = opener.open_fs(fs_url, parse_result, writeable, create, cwd)
    190         return open_fs, open_path
    191 

~/software/python/local-python-3/lib/python3.5/site-packages/fs/opener/osfs.py in open_fs(self, fs_url, parse_result, writeable, create, cwd)
     39         _path = abspath(join(cwd, expanduser(parse_result.resource)))
     40         path = normpath(_path)
---> 41         osfs = OSFS(path, create=create)
     42         return osfs

~/software/python/local-python-3/lib/python3.5/site-packages/fs/osfs.py in __init__(self, root_path, create, create_mode, expand_vars)
    138         else:
    139             if not os.path.isdir(_root_path):
--> 140                 raise errors.CreateFailed("root path does not exist")
    141 
    142         _meta = self._meta = {

CreateFailed: root path does not exist
```

**Comment by cmalbrec** [comment]
*update*: I can of course fool the parser:
```
$ ~ > ipython
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import fs

In [2]: fs.__version__
Out[2]: '2.4.10'

In [3]: path2Load = '/tmp/test2@mymail.org'

In [4]: try:
   ...:     fs.open_fs('osfs://'+path2Load)
   ...: except:
   ...:     print('Did not work!')
   ...:     myFS = fs.open_fs('osfs://:@'+path2Load+'?')
   ...:     
Did not work!

In [5]: myFS
Out[5]: OSFS('/tmp/test2@mymail.org')
```

**Comment by lurch** [comment]
@willmcgugan might have other answers, but I found two workarounds:

1. Use the `OSFS` constructor directly
```python
from fs.osfs import OSFS
myFS = OSFS(u'/tmp/test@mymail.com/')
```

2. URL-encode the path
```python
import fs
myFS = fs.open_fs(u'/tmp/test%40mymail.com/')
```
https://www.google.com/search?q=urlencode+python

**Comment by althonos** [comment]
An FS URL defaults to `file://`, so you should always urlencode special characters.

**Comment by cmalbrec** [comment]
Hi everyone:

I am good with the solution 1. of https://github.com/PyFilesystem/pyfilesystem2/issues/324#issuecomment-516358535 . You decide to which extend you want or do not want to adapt the code regarding `fs.open_fs()`. Perhaps it is worth adding a comment to the documentation of `fs.open_fs()` that reflects our discussion here. Thx for the `fs` module, it is useful to me. Feel free to close this issue.

**Comment by lurch** [comment]
Yeah, IMHO this counts as a documentation issue.

**Comment by willmcgugan** [comment]
Thanks @cmalbrec @lurch @althonos . I think percent encoding is the way to go.

It is covered [here](https://docs.pyfilesystem.org/en/latest/openers.html), specifically there is a note box re the percent encoding. Happy to update the docs if anyone has any suggestions how to make it clearer, in the meantime I'll close this one.

**Comment by lurch** [comment]
Perhaps the "Note" could be expanded to also mention that the `resource` field also needs to be percent-encoded? And maybe all the places where FS URLs are mentioned (e.g. https://docs.pyfilesystem.org/en/latest/reference/opener.html#fs.opener.registry.Registry.open_fs ) should also have a link to that page?

P.S. On a side-note, why does `open` default to `writeable=True` but `open_fs` defaults to `writeable=False` ???

**Comment by cmalbrec** [comment]
Hi @willmcgugan :

I believe newcomers to `fs` (like I am) would appreciate a clue from `help(fs.open_fs)`. An additional *Note* box in https://docs.pyfilesystem.org/en/latest/guide.html won't hurt.
