### ISSUE TITLE
Test on windows

### ISSUE THREAD

**Issue by chfw** [PyFilesystem/pyfilesystem2#325]
Hi pyfileystem2 team:

Thanks for this nice library and I am porting my library to use it.

While I am doing the porting, I am finding that there are quite [many issues on python3 in windows](https://dev.azure.com/moremoban/moban/_build/results?buildId=598). Yes, I will make PR later once my porting work is done.

Before that, could I suggest to your team to use either appveyor or azure pipeline where ci build on windows os is possible? I can contribute to such an effort but both ci system requires the owner of open source project to do initial setup: i.e. permissions et el. I am not sure if you would consider a windows build to complement your vision.

Thanks

**Comment by willmcgugan** [comment]
We do have appveyor set up for Python3.6 and Python 3.7. The tests are passing. If you are seeing test fails in moban on Windows it _could_ be related to mixing system paths (i.e. back slashes) and fs paths (forward slashes).

Of course, if you do identify bugs we would be keen to fix them.

**Comment by chfw** [comment]
That’s good then. I will add one more test case.


Do you mind display your appveyor icon like the following? I only find Travis icon. That’s why I jumped to conclusion.
![E024A128-9278-4B42-A426-36B4335F75B9](https://user-images.githubusercontent.com/4280312/62146382-32c0cc00-b2ed-11e9-915b-846bcd2886b9.jpeg)

**Comment by chfw** [comment]
Sorry for the large icon. Used my phone to do screenshot.
