### ISSUE TITLE
ResourceType not properly linked in docs

### ISSUE THREAD

**Issue by lurch** [PyFilesystem/pyfilesystem2#326]
https://docs.pyfilesystem.org/en/latest/info.html#details-namespace says:
Resource type, one of the values defined in `ResourceType`.

Is the `ResourceType` supposed to link to https://docs.pyfilesystem.org/en/latest/reference/enums.html#fs.enums.ResourceType ?

And see also https://docs.pyfilesystem.org/en/latest/reference/info_objects.html#fs.info.Info.type and https://docs.pyfilesystem.org/en/latest/reference/base.html#fs.base.FS.gettype

**Comment by willmcgugan** [comment]
Yep, thanks. Should be fixed now.
