### ISSUE TITLE
Switch to pytest?

### ISSUE THREAD

**Issue by dargueta** [PyFilesystem/pyfilesystem2#327]
`nose` is no longer maintained (last release was in 2015) so I think we should consider moving on to a different testing framework. `pytest` gets us a lot of things like simplified argument parametrization and a *lot* of plugins we can install. It works with `unittest` so I don't think the move will require an overhaul.

**Comment by lurch** [comment]
https://nose.readthedocs.io/en/latest/#note-to-users

**Comment by willmcgugan** [comment]
Yeah, pytest seems to be the dominant framework these days. I use it in other projects. I'm not sure what's involved in switching, hope I don't have to individually edit the tests.

**Comment by dargueta** [comment]
> hope I don't have to individually edit the tests.

Aside from removing references to `nose`-specific stuff, no

**Comment by dargueta** [comment]
Working on it in #337, may need help fixing Appveyor since I've never used it before.

**Comment by dargueta** [comment]
I added a plugin to randomize test execution order and it looks like we have some hidden test interdependencies I can't figure out. Help would be most welcome.
