### ISSUE TITLE
Enforce mypy typechecking in CI

### ISSUE THREAD

**Issue by chfw** [PyFilesystem/pyfilesystem2#332]
Hi all,

This project's PR template reads very interesting:

` I accept that @willmcgugan may be pedantic in the code review.`

I wondered if adding flake8 check to such a cool project would support the word: 'pedantic', strongly. Is there a good reason not to have flake8?

Here is what flake8 tells about the files:
```
...
tests/test_path.py:183:22: F405 'iswildcard' may be undefined, or defined from star imports: fs.path
tests/test_path.py:184:22: F405 'iswildcard' may be undefined, or defined from star imports: fs.path
tests/test_path.py:185:22: F405 'iswildcard' may be undefined, or defined from star imports: fs.path
tests/test_path.py:186:26: F405 'iswildcard' may be undefined, or defined from star imports: fs.path
tests/test_path.py:187:26: F405 'iswildcard' may be undefined, or defined from star imports: fs.path
tests/test_path.py:188:26: F405 'iswildcard' may be undefined, or defined from star imports: fs.path
tests/test_path.py:204:30: F405 'relativefrom' may be undefined, or defined from star imports: fs.path
...
```

**Comment by willmcgugan** [comment]
I've found flake8 to have too may false positives as it only has a superficial understanding of the code. We do have typechecking in the project with mypy, which is far better at detecting issues in my experience. For instance mypy would know the difference between a star import and undefined symbol.

We don't have the mypy check in the CI though, and we really should. A few mypy errors have crept in since I last checked, so that needs to be addressed.

@chfw I'm going to accept this issue, but change the title...

**Comment by willmcgugan** [comment]
Mypy issues fixed in master.

**Comment by chfw** [comment]
Thanks for accepting my issue. Yes, mypy definitely will help enforce the type check and help reducing runtime erros. 👍 

With your attention, please allow me to explain a bit on the positive side of flake8. I am pleased already and I am not going to push like a nut :). That's only me so I would not like to push everyone.

My emacs or pycharm will flag up lines to indicate potential problems. Normally, you would like to have no red lines at a glance. Take tools.py as an example, the IDE tells it has some problems: imported but not used.

![Screenshot 2019-08-04 at 20 25 00](https://user-images.githubusercontent.com/4280312/62428167-7012c880-b6f6-11e9-8cc5-47a2098ecb11.png)

Yet again, let's stress that my thanks for accepting my feedback. I am pleased that you took further action. It is appreciated!

**Comment by willmcgugan** [comment]
I'm all for linting in the development environment. I use pylint in VSCode, which for some reason isn't picking up unused imports.
