### ISSUE TITLE
[Question] What is the _meta class attribute of FS ?

### ISSUE THREAD

**Issue by glenfant** [PyFilesystem/pyfilesystem2#335]
Hi,

I am actually adding a new Azure Dalalake backend to FS2.

https://github.com/glenfant/fs.datalake

Hacking the code, of OTB and 3rd party backends for FS2, I notice that the various FS subclasses have a "_meta" class duct attribute. But I did not find (or searched unsuccessfully documentation or hints about the various keys of this dict.

Any help is welcome. And many thanks in advance.

**Comment by willmcgugan** [comment]
The `_meta` attribute stores the [standard meta namespace](https://docs.pyfilesystem.org/en/latest/reference/base.html#fs.base.FS.getmeta) for some filesystems. It's an implementation detail not guaranteed to exist, so you shouldn't rely on it.

A Datalake filesystem is exciting. Would you like me to add it to https://www.pyfilesystem.org/page/index-of-filesystems/ ?

**Comment by glenfant** [comment]
@willmcgugan : Yes of course ! But as rou can read, it is just a project bootstrap today. I'll file a new issue here at the first alpha release.

There's still a lot of work planned on it. And other questions like : "Is it supposed to support Python 2.7 when there is a question about its future support in FS2?". Playing with "six" and too old Python 3 versions will be a hassle.

Thanks again for your help.

**Comment by willmcgugan** [comment]
Done. 

We're abandoning Python2.7 soon. Hopefully before the 2020 end of life. I'd go for Python3 only unless you have a particular need for Python2.7
