### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by willmcgugan** [PyFilesystem/pyfilesystem2#349]
requirements.txt was removed in https://github.com/PyFilesystem/pyfilesystem2/pull/337 Turns out that readthedocs needs it, so it needs to be restored before we push a new version.

**Comment by dargueta** [comment]
Ooops. Why does readthedocs need it?

**Comment by willmcgugan** [comment]
It builds the docs in a virtual environment, and installs dependencies from
the requirements.txt

**Comment by chfw** [comment]
readdocs can load custom requirements.txt when it is only for readdocs, not for development.

**Comment by dargueta** [comment]
Oh, I see. To avoid putting requirements in multiple places do you thing putting

```
# Do not remove, required by RTD
-e.
```

as the only thing in the requirements file would work?
