### ISSUE TITLE
Non recursive walk

### ISSUE THREAD

**Issue by aliabbasjp** [PyFilesystem/pyfilesystem2#35]
How can we walk non recursively using the walk method? currently it does recursively

How can we specify depth option say recurse only upto depth of 2.

**Comment by willmcgugan** [comment]
It doesn't actually use recursion. Have a look at the [implementation](https://github.com/PyFilesystem/pyfilesystem2/blob/master/fs/walk.py).

There's no maximum depth argument, but that would be a nice addition. I would accept a PR for that, if done well and with tests...

**Comment by aliabbasjp** [comment]
@willmcgugan  on doing  a `spec_fs.walk.dirs()` it does recursively list all the sub directories. I only need the top directories, earlier there used to be a listdir() but is no longer available?

**Comment by willmcgugan** [comment]
I thought you were referring to code recursion. Listdir [still exists](https://pyfilesystem2.readthedocs.io/en/latest/reference/base.html#fs.base.FS.listdir), see also https://pyfilesystem2.readthedocs.io/en/latest/guide.html#directory-information
