### ISSUE TITLE
fs.path.forcedir would add '/' after filepath？

### ISSUE THREAD

**Issue by Arstead** [PyFilesystem/pyfilesystem2#353]
I check up source code of function 'fs.path.forcedir'
```
def forcedir(path):
    # type: (Text) -> Text
    """Ensure the path ends with a trailing forward slash.

    Arguments:
        path (str): A PyFilesytem path.

    Returns:
        str: The path, ending with a slash.

    Example:
        >>> forcedir("foo/bar")
        'foo/bar/'
        >>> forcedir("foo/bar/")
        'foo/bar/'
        >>> forcedir("foo/spam.txt")
        'foo/spam.txt'

    """
    if not path.endswith("/"):
        return path + "/"
    return path
```
if we just append '/' after path. forcedir("foo/spam.txt") will retrun "foo/spam.txt/", not "foo/spam.txt".

Is that a bug?

**Comment by willmcgugan** [comment]
Yeah. It adds a / to the path if it doesn't already exist.

**Comment by willmcgugan** [comment]
Ah, that's an error in the docstring. I'll correct that.

**Comment by willmcgugan** [comment]
Fixed in master

**Comment by Arstead** [comment]
Thank you for answer.
I wonder if you will modify the code to implement the function mentioned in the docstring？

**Comment by willmcgugan** [comment]
That was never the intent of it. You can't really guess from the filename. `foo` could be a file, and `span.txt` could be a directory.

**Comment by Arstead** [comment]
You are right. 

But there will lead to another problem in the s3fs.
https://github.com/PyFilesystem/s3fs/blob/master/fs_s3fs/_s3fs.py#L328

Line 328 involes function 'forcedir'. 
If i delivery a path likes 'foo/spam.txt' to member function 'getinfo',  the member function will call another function '_path_to_dir_key' which will return 'foo/spam.txt/', and i can't get s3 Object of 'foo/spam.txt'.

**Comment by willmcgugan** [comment]
@Arstead That method in s3fs get a path to a directory. I don't how getinfo could be broken, it calls that method to check if the directory exists. 

If you can identify a bug, please file it in the s3fs issues. Some example code would be great.
