### ISSUE TITLE
Documentation for listing shared network printers.

### ISSUE THREAD

**Issue by jonfen** [PyFilesystem/pyfilesystem2#358]
Listing the shared files is cut and dry, but how do you list the shared printer names of a given computer?

Also asked here:
https://github.com/althonos/fs.smbfs/issues/5

**Comment by althonos** [comment]
This is not something you can do with Pyfilesystem, you only have abstraction over filesystems, so naturally this is not something you can do with `fs.smbfs` either.

**Comment by lurch** [comment]
There's a reason this project is called PyFileSystem and not PyPrintSystem :laughing:

**Comment by jonfen** [comment]
> This is not something you can do with Pyfilesystem, you only have abstraction over filesystems, so naturally this is not something you can do with `fs.smbfs` either.

I was hopeful since it listed out:

- ADMIN$
- C$
- PRINT

But PRINT didn't have everything I needed.  I am looking for an MIT license package that provides a list of printers, similar to the GPL one here that can list files AND printers:

https://github.com/jonfen/pysmbc/commit/84943a183688a68ec59fdab16aa268ff5a2a7a66

**Comment by lurch** [comment]
Maybe https://pypi.org/search/?q=samba will prove useful? :man_shrugging:

**Comment by jonfen** [comment]
> Maybe https://pypi.org/search/?q=samba will prove useful?

That and other keywords are how I can across fs.smbfs, I will keep going down the list.
