### ISSUE TITLE
Default validatepath always returns an error on python 2

### ISSUE THREAD

**Issue by chibill** [PyFilesystem/pyfilesystem2#36]
It always errors with. (Ignore the fact it's running on an IPad. As this is not the cause of the error)
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/mobile/Containers/Shared/AppGroup/918D6D37-F227-4306-AB10-79DD50290D29/Pythonista3/Documents/site-packages/fs/osfs.py", line 233, in listdir
    _path = self.validatepath(path)
  File "/private/var/mobile/Containers/Shared/AppGroup/918D6D37-F227-4306-AB10-79DD50290D29/Pythonista3/Documents/site-packages/fs/base.py", line 1122, in validatepath
    raise ValueError('path must not be bytes')
ValueError: path must not be bytes`

Because in python2 a sting is an instance of bytes. 
In python2 isinstance("hello",bytes) returns true.
While in python3 isinstance("hello",bytes) returns false.

FS version is 2.0.2

**Comment by willmcgugan** [comment]
Paths should be unicode on Python2.7 Please see docs... https://pyfilesystem2.readthedocs.io/en/latest/concepts.html#paths

**Comment by chibill** [comment]
So that is one of the breaking changes between pyfs and pyfs2?

**Comment by chibill** [comment]
Also how can we write code that works for both py2 and py3 if they have to be casted to different types?

**Comment by willmcgugan** [comment]
The unicode type does exist in Python 2. Its just named `str` now.

Prefix your strings with a `u`, or add `from __future__ import unicode_literals` to the top of your Python files.

**Comment by chibill** [comment]
I guess that mostly works. For string I type at least... need to make python specific code if I ever call str as that does not follow the future import. :( maybe I should install six and use its functions that handle this. (Which is odd that py fs does not)

**Comment by chibill** [comment]
That works. I found another work around for when I need to use str at the top of my files also I can set str = unicode
