### ISSUE TITLE
Have `open_fs(fs)` return a copy of the passed `fs`

### ISSUE THREAD

**Issue by trendelkampschroer** [PyFilesystem/pyfilesystem2#363]
First of all thanks a lot for the great project!

I'm wondering whether it would make sence to have `open_fs` return a copy of a passed in `fs` instance instead of returning the instance. Consider the following example

```python

from fs import open_fs
from fs.base import FS
from fs.tempfs import TempFS

def foo(target: Union[str, FS]) -> None:
    """Create the empty file 'foo.bar' at `target`.

    Args:
        target (path, url or filesystem instance): The target for ressource at which to create file 'foo.bar'.

    """
    with open_fs(target) as fs:
        fs.touch("foo.bar")

with TempFS() as fs:
    foo(fs)
    print(fs.exists("foo.bar"))  # raises `FilesystemClosed`

with TempFS() as fs:
   foo(fs.getsyspath(""))
   print(fs.exists("foo.bar"))

>>> True  

```

I think that it would be good if `open_fs` could be made to return a copy of a passed in `FS` instance, because it should be as simple as possible for someone creating `foo`-like function to ensure that all function local ressources are appropriately closed without affecting a filesystem instance that is passed from the outside.

Otherwise user will be tempted to implement the above functionality as

```python

def foo(target: Union[str, FS]):
    fs = open_fs(target)
    fs.touch("foo.bar")

```
Here the function local ressource `fs` will not be closed, if `target` is a path or url, in order to avoid closing an externally managed `FS` instance

or 

```python

def foo(target: Union[str, FS):
    if isinstance(target, FS):
         target.touch("foo.bar")
    else:
        with open_fs(target) as fs:
            fs.touch("foo.bar")

```

which defies the purpose of duck typing and needs to be repeatedly performed to 'work' around an undesired/unexpected (in this situation) behaviour of `open_fs`.

**Comment by lurch** [comment]
I'm not sure what it is that you're trying to do? It feels like wanting `target` to be `(path, url or filesystem instance)` isn't "in the spirit" of PyFilesystem? (I'd expect `foo` to always take only an already-opened FS object, and to then not try re-opening it)

With the wide variety of filesystems supported by pyfs, I'm not even sure that "a copy of a passed in fs instance" makes sense for all of them?

**Comment by willmcgugan** [comment]
Glad you like PyFilesystem.

I can see the utility in that, but it's a 👎 from me.

There's the edge case that if you use a FS as a context manager it will close the filesystem -- which you probably don't want.

Generally speaking, I find having a union of unrelated types can make for difficult to debug code. Even if it seems like a convenience on some scale.

That said, there is a method that does pretty much that (see [manage_fs](https://docs.pyfilesystem.org/en/latest/reference/opener.html#fs.opener.registry.Registry.manage_fs)). It's not an internal method, but I wouldn't say it is recommended for general use. I'd concur with @lurch that you are better off accepting FS arguments only.

**Comment by trendelkampschroer** [comment]
Perfect, `manage_fs` seems to be the way to go here. As for the unrelated types that's a very valid point, but 

"The interface wants, what the interface wants ..." :-)
