### ISSUE TITLE
Datastore FS - a new filesystem for Google Cloud Firestore in Datastore mode

### ISSUE THREAD

**Issue by mikespub** [PyFilesystem/pyfilesystem2#367]
See README at https://github.com/mikespub-org/mp-fs-wsgidav

Most of the basic functionality is available, including listing, walking, downloading, uploading etc.

Some of the more detailed file operations like appendbytes, seek & truncate fail because, well, it's really not a filesystem in the back-end, and we use a simple io.BytesIO between the FS and Datastore.

And since I've been investigating Firestore in native mode for WsgiDAV as well, I'll probably throw in a Firestore FS for PyFilesytem2 too ;-)

**Comment by willmcgugan** [comment]
Added. Sorry for the delay.
