### ISSUE TITLE
Request function to file name validation like validatepath(path)

### ISSUE THREAD

**Issue by 12edge** [PyFilesystem/pyfilesystem2#369]
There is an existing function to validate the syntax of a path "validatepath(path)". I would like to have a function to validate the syntax of a file name. This is exactly what the package pathvalidate does in the function is_valid_filename().  This would allow my programs to validate a file name without having to import yet another package. It would allow my programs to validate input without doing a request to the operating system.  (Also, stem would be nice. Is there any thoughts of merging pyfilesystem with pathlib?)
example of what needs to be done now
```
import pathlib
from pathvalidate import is_valid_filename
if is_valid_filename (sys.argv[0]):
    output_file = PurePath(sys.argv[0]).stem + '.out'
else:
    progname = 'unknown.out'

```

**Comment by lurch** [comment]
> Is there any thoughts of merging pyfilesystem with pathlib?

See #238

**Comment by lurch** [comment]
> I would like to have a function to validate the syntax of a file name.

I'm not sure that's even possible for PyFilesystem? Since different filesystems may have different ideas about what a "valid filename" is? ping @willmcgugan

**Comment by althonos** [comment]
Every PyFilesystem has a `validatepath` function that is used in most of the other functions to check the paths given as input. Filesystems can have differents requirements for those. The default base implementation will check if the path contains `invalid_path_chars` as defined in the filesystem metadata returned by `FS.getmeta`, and if the path does not exceed the maximum length.

**Comment by 12edge** [comment]
Since PyFilesystem is a generalized interface, and not designed to be a replacement for pathlib perhaps the README.md should be updated to included a sentence saying this. Thank you for the wonderful software.
