### ISSUE TITLE
Third Party FS - a new filesystem for Azure Datalake

### ISSUE THREAD

**Issue by nivm** [PyFilesystem/pyfilesystem2#372]
Adding more implementation to the INDEX OF FILESYSTEMS: [Third Party section ](https://www.pyfilesystem.org/page/index-of-filesystems/).

We have created a pyfilesystem plugin to support [Azure Datalake](https://docs.microsoft.com/en-us/azure/data-lake-store/) and are using it in production for the past year.

A link to the repository: https://github.com/emedgene/fs_dlk

I can see there is another implementation called 
[fs.datalake Azure Datalake Storage filesystem (work in progress).](https://github.com/glenfant/fs.datalake)

**Comment by willmcgugan** [comment]
Thanks!
