### ISSUE TITLE
Third Party FS - a new filesystem for Illumina Basespace

### ISSUE THREAD

**Issue by nivm** [PyFilesystem/pyfilesystem2#373]
Adding more implementation to the INDEX OF FILESYSTEMS: [Third Party section](https://www.pyfilesystem.org/page/index-of-filesystems/) .

We have created a pyfilesystem plugin to support [Illumina Basespace](https://basespace.illumina.com/) and are using it in production for the past year.

A link to the repository: https://github.com/emedgene/fs_basespace

**Comment by willmcgugan** [comment]
Nice. WIll do that soon.

**Comment by nivm** [comment]
Thanks!
@willmcgugan - any update on this?

**Comment by willmcgugan** [comment]
Thanks for the prompt--it's there now.
