### ISSUE TITLE
Is there a way to open zipfile inside another filesystem as ZipFS

### ISSUE THREAD

**Issue by torviolento** [PyFilesystem/pyfilesystem2#377]
In this case the first filesystem is just OSFS, so I can just get the path to the zip file, but it would be nice to later use some other FS like in-memory filesystem instead. 

I tried to look into docs and searched around, but couldn't find any way to do that.
I tried using this_filesystem.open_dir with passing zipfs as constructor, but it only works with directories.

It would be nice to have a function like open_fs to open filesystems inside another filesystems, but I understand it might be hard to implement.

**Comment by torviolento** [comment]
I just noticed that there is fs.archive that works in my usecase at least

**Comment by willmcgugan** [comment]
You can construct a ZipFS with a file-like object.

```python
with my_osfs.openbin("test.zip") as zip_file:
    with ZipFS(zip_file) as zip_fs:
        zip_fs.tree()
```
