### ISSUE TITLE
raising wrong exception type - OSError's.

### ISSUE THREAD

**Issue by spacebat777** [PyFilesystem/pyfilesystem2#378]
memoryfs.py:131:178:(maybe more) - Not raising the appropriate fs.errors type - instead raising built-in type IOError which is a subclass of the built-in OSError type.

Would a better type be OperationFailed("File not open for reading."), or PermissionDenied("File not open for reading.") ?

Or do we need to create some new types of error to cover the cases where the fs modules resort to raising OSError types?

Something else to consider - doing away with a custom `fs.errors` tree and simply using the built-in `OSError` tree.  It seems like `fs.errors` is just reinventing the wheel in this respect..

Also, if raising an OSError type, please set the errno field to the appropriate number if possible.

**Comment by willmcgugan** [comment]
Those errors are from a file object, which conforms to the file interface. File objects raise IOErrors.

Filesystem objects have their own exception hierarchy to cover the gamut of error conditions, many of which don't translate to OS errors.
