### ISSUE TITLE
listdir() should return a lazy iterator.

### ISSUE THREAD

**Issue by spacebat777** [PyFilesystem/pyfilesystem2#379]
for modules like `fs.ftpfs`, the `listdir()` method can be horrendously slow because it blocks until it's retrieved all the list items. It's so slow in some cases as to make using the fs module as a solution for ftp impractical.

IMO, it would be better if this method returned a lazy iterator that doesn't retrieve everything before it returns. It could retrieve in smaller blocks of filenames, or single file names at a time when it's iterated over. Maybe this would require threading or async, but doesn't have to.

**Comment by willmcgugan** [comment]
See https://docs.pyfilesystem.org/en/latest/reference/base.html#fs.base.FS.scandir
