### ISSUE TITLE
Incorrect docstring

### ISSUE THREAD

**Issue by lurch** [PyFilesystem/pyfilesystem2#382]
The docstring for [Mode.to_platform](https://github.com/PyFilesystem/pyfilesystem2/blob/master/fs/mode.py#L73) contains "Currently, this just removes the 'x' on PY2 because PY2 doesn't support exclusive mode." which seems to be correct. However that same snippet is also included in the docstring for  [Mode.to_platform_bin](https://github.com/PyFilesystem/pyfilesystem2/blob/master/fs/mode.py#L83) where it appears to be incorrect.

**Comment by althonos** [comment]
Good catch!
