### ISSUE TITLE
fs.dropboxfs missing in list of Third Party filesystems

### ISSUE THREAD

**Issue by jensens** [PyFilesystem/pyfilesystem2#383]
Is there any reason why the the very useful and pretty well working [fs.dropboxfs ](https://pypi.org/project/fs.dropboxfs/) by @zopyx is not listed at https://www.pyfilesystem.org/page/index-of-filesystems/ under external Third Party there?

**Comment by zopyx** [comment]
I thought it would be listed there...will care about it

**Comment by zopyx** [comment]
https://github.com/PyFilesystem/pyfilesystem.org/issues/4

**Comment by zopyx** [comment]
it's now official listed as official driver
