### ISSUE TITLE
Unpack a within in-memory fs

### ISSUE THREAD

**Issue by Make42** [PyFilesystem/pyfilesystem2#385]
Is there a way to unpack a zip, somewhat like [shutil.unpack_archive](https://docs.python.org/3/library/shutil.html#shutil.unpack_archive), but within the in-memory fs? So what I would do is, I would copy the zip into the in-memory fs and then unpack it there.

**Comment by lurch** [comment]
I guess you just need to create a zipfs and a memoryfs and then copy from one to the other?
See e.g. #377

**Comment by althonos** [comment]
what @lurch said, and then `copy_fs` is your friend;

```python
with fs.open_fs("mem://") as memfs:
    with fs.open_fs("zip://...") as zipfs:
        fs.copy.copy_fs(zipfs, memfs)
```

**Comment by Make42** [comment]
@lurch @althonos I want to unpack the zip **within** the in-memory fs, not **into** the in-memory fs, as "I would copy the zip into the in-memory fs and then unpack it there". So what I have been doing is
```
import fs.osfs
memfs = fs.open_fs("mem://")
osfs = fs.open_fs(r'path/to/zip/')
memfs.writebytes('src.zip', decrypt(osfs.getbytes('src.zip')))
```
but what do I do now? As you can see, I am doing something with the zip beforehand (here decrypting).

I would also be happy to directly unzip the bytes into memory as in this imaginary non-working code

```
memfs = fs.open_fs("mem://")
osfs = fs.open_fs(r'path/to/zip/')
zipfs = memfs.open_fs("zip://path")
zipfile = decrypt(osfs.getbytes('src.zip'))
zipfs.unzip(zipfile, '/')
```

**Comment by lurch** [comment]
Have a look again at #377 
For the sort of stuff you're doing, I think you'd be much better of using the FS constructors directly rather than relying on the `open_fs` "helper method".  Also, I believe each MemoryFS is entirely independent, so there's nothing stopping you having multiple separate MemoryFSes open at once :slightly_smiling_face:

**Comment by Make42** [comment]
@lurch Boah, thanks! I was getting really frustrated, but the fault was all mine: I should have read more carefully. Thanks to your pointer I was able to get this working solution:

```
import os
import fs.zipfs
import fs.copy

src_zip = "/path/to/file.zip"

def decrypt(byte_file):
    return byte_file

fs_mem = fs.open_fs("mem://")

with fs.open_fs("mem://") as fs_mem_zip:
    with fs.open_fs(os.path.dirname(src_zip)) as fs_os:
        fs_mem_zip.writebytes('src.zip', decrypt(fs_os.getbytes('src.zip')))
    file_zip = fs_mem_zip.openbin('src.zip')
    fs_zip = fs.zipfs.ZipFS(file_zip)
    print(fs_zip.tree())
    fs.copy.copy_fs(fs_zip, fs_mem)

fs_mem.listdir('/')
fs_mem.tree()
```
