### ISSUE TITLE
Documentation website appears to be down

### ISSUE THREAD

**Issue by nwh** [PyFilesystem/pyfilesystem2#390]
Here is what I see:

<img width="840" alt="Screen Shot 2020-05-01 at 13 44 50" src="https://user-images.githubusercontent.com/525247/80840399-13273e80-8bb2-11ea-9832-488ef89183af.png">

**Comment by willmcgugan** [comment]
Not sure what's going on there. In the meantime, you can still access docs via https://pyfilesystem.readthedocs.io/en/latest/

**Comment by willmcgugan** [comment]
readthedocs.io changed something with the certs. I think it will resolve itself soon. Will check tomorrow. Thanks for letting me know about this.

**Comment by lurch** [comment]
Seems to be okay again now?

**Comment by willmcgugan** [comment]
Yep
