### ISSUE TITLE
splitext removes a forward slash from url

### ISSUE THREAD

**Issue by simonm3** [PyFilesystem/pyfilesystem2#398]
Why does fs.path.splitext(url) remove one of the forward slashes?
```
url = 's3://simonm3/_testdata/file1.pkl'
fs.path.splitext(url), os.path.splitext(url)
```
(('s3:/simonm3/_testdata/file1', '.pkl'),
 ('s3://simonm3/_testdata/file1', '.pkl'))

Also what is the purpose of the second forward slash? The standard format of a url is that // denotes the start what urllib.urlparse calls "netloc" and includes username etc..  The pyfilesystem url instead uses // as part of the filesystem. Why not have "s3:/somefolder/somefile" rather than "s3://somefolder/somefile" ?

https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Generic_syntax

**Comment by willmcgugan** [comment]
fs.path functions aren’t intended for URLs, they operate on FS paths. https://docs.pyfilesystem.org/en/latest/concepts.html

**Comment by simonm3** [comment]
IMO this is a somewhat artifiicial distinction. I am using urls as a path
as it seems convenient. Anyway seems a bit odd that splitext would do
anything other than split on ".". Removing forward slashes is not an
obvious thing it should be doing.

**Comment by willmcgugan** [comment]
Double slashes don't have any meaning in a FS path. In other words "//foo/bar" references the same resource as "/foo/bar". FS path functions normalize the result so that that paths referencing the same resource will always compare equal.

They may look similar in many ways, but FS paths aren't URLs. Conflating the two will likely result in subtle breakage, you're better off sticking to the stdlib for parsing URLs.

**Comment by lurch** [comment]
> IMO this is a somewhat artifiicial distinction. I am using urls as a path as it seems convenient.

That reminds me of the "I am using bytes as a string as it seems convenient" approach taken by Python2 :laughing: 

I agree with @willmcgugan that you need to keep these three things conceptually distinct: URLs, system paths, pyfilesystem fspaths. Anything else will just lead to a world of pain and confusion later on.
If you're not careful, you might end up parsing `C:/Program Files/Python/` as a URL! :stuck_out_tongue_winking_eye:

**Comment by simonm3** [comment]
Well there is a specification for urls and file paths are included. This is a valid url:

`urlparse("file:c:/simonm3/_testdata")`
`ParseResult(scheme='file', netloc='', path='c:/simonm3/_testdata', params='', query='', fragment='')`

This is an invalid url. Firstly s3 is not a scheme. Secondly simonm3 is a folder not a username/password/host/port (which is what the // suggests it is.

`urlparse("s3://simonm3/_testdata")`
`ParseResult(scheme='s3', netloc='simonm3', path='/_testdata', params='', query='', fragment='')`

Of course it may be reasonable for pyfilesystem to drop the "file://" for convenience as it is only dealing with files anyway. However there is nothing wrong with treating file paths as urls - it is part of the standard.

**Comment by lurch** [comment]
Okay, then I guess there's actually 4 distinct things then - genuine URLs (e.g. `https://github.com/PyFilesystem/pyfilesystem2`), the fs-URLs used by PyFilesystem (e.g. your `s3://simonm3/_testdata/file1.pkl` example),  pyfilesystem fspaths (e.g. `/simonm3/_testdata`) and system paths (e.g. `c:/simonm3/_testdata` or `c:\\simonm3\\_testdata` (or `/home/simonm3/_testdata` on Linux)). From the pyfilesystem PoV, I guess a "file://" URL is actually analogous to a system-path, rather than a fspath.

Yes I realise these are fairly subtle distinctions, but if you can maintain these distinctions in your code (and only using the appropriate functions for parsing / converting between them) it'll make it much easier for you to figure things out if/when you run into problems later on.

**Comment by chfw** [comment]
As fs user, by reading fs.path.splitext, we assumed the return of ('s3://simonm3/_testdata/file1', '.pkl')), well without reading the manual, so did not expect fs touch the first element and take a forward slash out, and make it only useful to `fs`. 

URL, as universal resource locator, was created to, in my opinion, provide a consistent locator for all resources. However, [File URI scheme](https://en.wikipedia.org/wiki/File_URI_scheme), especially on Windows is badly implemented, see [issue 343](https://github.com/PyFilesystem/pyfilesystem2/issues/343).

I am circling back to myself now. I would suggest to make a note on fs.path.splitext, as user will get a surprise.

**Comment by lurch** [comment]
> well without reading the manual

I don't mean to sound harsh, but if you didn't read the manual then you shouldn't be surprised if things don't do what you "expect" them to?!?

https://docs.pyfilesystem.org/en/latest/concepts.html explains the difference between pyfs paths and 
system paths. https://docs.pyfilesystem.org/en/latest/openers.html explains how pyfs URLs are _similar_ to regular URLs (it doesn't claim that they're identical).
https://docs.pyfilesystem.org/en/latest/reference/path.html#fs.path.splitext is documented as operating on _paths_ not on _urls_ .
Would you expect [os.path.dirname()](https://docs.python.org/3/library/os.path.html#os.path.dirname) (which is also documented as working on _paths_) to do something sensible if given a URL? :wink: 

This may be a place where we need to respectfully agree to disagree? :slightly_smiling_face:

**Comment by chfw** [comment]
Surely, we are having open minded discussions. 

If you do not mind, I would submit a PR to append the 'exception' case from this issue:
```
>>> splitext('baz.txt')
('baz', '.txt')
>>> splitext('foo/bar/baz.txt')
('foo/bar/baz', '.txt')
>>> splitext('foo/bar/.foo')
('foo/bar/.foo', '')
>>> splittext('s3://simonm3/_testdata/file1.pkl')
('s3:/simonm3/_testdata/file1', '.pkl')
```

**Comment by lurch** [comment]
> Surely, we are having open minded discussions.

Indeed :slightly_smiling_face: 

You're free to submit a PR, but it's entirely up to @willmcgugan whether he accepts it or not :wink: 
(my personal opinion is it's still very odd to give a _url_ to a function expecting a _path_, but meh)

As an example of where the 'normalization' that splitext does is useful:
```python3
>>> splitext('foo/./bar/moo/../baz.txt')
('foo/bar/baz', '.txt')
```

**Comment by chfw** [comment]
This following is another surprise.
```
>>> splitext('http://www.google.com')
('http:/www.google', '.com')
```

**Comment by willmcgugan** [comment]
Opened minded discussions are great. I've come to many a revelation when discussing design decisions. It can only lead to improvements.

But I don't think there is much more to be said on this particular issue. `fs.path` should only be use for FS paths, never URLs. Nothing in fs.path is aware of URLs. @lurch has some good examples of problems that may occur if you mix them. 

Normalizing returned paths is generally good thing. Without it you would have to explicitly normalize paths before you compare them.

I do think it's a fair point that `splitext` isn't documented as returning a normalized path, and that's probably the root of the issue. @chfw is probably on the right track, but I'll make further comments on the PR.

I'll leave this issue open for now, so nobody feels they are being silenced. But please don't rehash things unless there are new arguments for or against.

**Comment by simonm3** [comment]
> Normalizing returned paths is generally good thing

Agree but shouldn't this explicit? A function called "splitext" should do exactly that and nothing more. Even more so when there is a standard library function with the same name that does exactly that and nothing more.  Normalising paths is not required nor expected - seems unlikely anyone would be doing comparisons after a splitext anyway!

**Comment by lurch** [comment]
> Even more so when there is a standard library function with the same name that does exactly that and nothing more.

Then stick to using the standard library function? :wink: 

> Normalising paths is not required nor expected

Says who? IMHO there's nothing that says pyfilesystem has to follow the same "rules" as the standard library, and if @willmcgugan wants to adopt his own set of "standard conventions" for pyfilesystem functions that operate on its "fspaths" then that's entirely up to him? (provided of course that those conventions are adequately documented :wink: )

As I mentioned earlier, I think you need to be careful not to conflate "fspaths" (as used within pyfilesystem) with system-paths (as used within the python standard libraries) or URLs.

P.S. Sorry if this comes across as overly-defensive.

**Comment by simonm3** [comment]
> Says who?

Zen of python - "explicit is better than implicit".....plus it is accepted
good practice for a function to do what it says on the tin......No problem
with breaking with convention if there is good reason but there isn't here.

I actually have my own wrapper that uses urls because it is simpler than
trying to make a distinction between urls, paths, pyfs urls, and pyfs
paths. Works quite well most of the time until I get surprised by functions
doing unexpected things😁

**Comment by lurch** [comment]
> my own wrapper that uses urls because it is simpler than trying to make a distinction between urls, paths, pyfs urls, and pyfs paths.

That might work short-term for very simple things, but IMHO that's never going to work long-term because each of those things is different by nature.
All IMVHO of course!

**Comment by willmcgugan** [comment]
Closing this now. It's a matter of expectations not matching the implementation. I will clarify in the docs, but I think the implementation is fine as is.

> is simpler than trying to make a distinction between urls, paths, pyfs urls, and pyfs
paths

This will likely bite you even if you weren't using PyFilesystem. 

Thanks all.
