### ISSUE TITLE
Minor error in "Testing Filesystems" documentation

### ISSUE THREAD

**Issue by mjpieters** [PyFilesystem/pyfilesystem2#407]
The [_Implementing Filesystems -> Testing Filesystems_ section](https://docs.pyfilesystem.org/en/latest/implementers.html#testing-filesystems) has a minor error in the example:

```python
from fs.test import FSTestCases

class TestMyFS(FSTestCases):

    def make_fs(self):
        # Return an instance of your FS object here
        return MyFS()
```

`FSTestCases` is a plain class without anything more than `object` as a base class, yet it's methods expect `unittest.TestCase` to be a base, so the above won't work. It's missing an additional base class:

```python
import unittest 
from fs.test import FSTestCases

class TestMyFS(FSTestCases, unittest.TestCase):

    def make_fs(self):
        # Return an instance of your FS object here
        return MyFS()
```

**Comment by lurch** [comment]
Looks like you're right :)
https://github.com/PyFilesystem/pyfilesystem2/search?q=FSTestCases&type=Code
