### ISSUE TITLE
'SubFS' object has no attribute 'writetext'

### ISSUE THREAD

**Issue by geoffjukes** [PyFilesystem/pyfilesystem2#408]
Hi @willmcgugan 

The subject says it all I think: 'SubFS' object has no attribute 'writetext'

`settext` works just fine, but I know it's been deprecated

Geoff

**Comment by althonos** [comment]
@geoffjukes : are you sure you are using the latest version of Pyfilesystem2? I checked `fs.SubFS` and it does have `writetext`. `writetext` is normally supported since `v2.2.0`.

**Comment by geoffjukes** [comment]
@althonos Yup, using 2.4.11

**Comment by althonos** [comment]
Can you give me some code to reproduce? Trying to call `writetext` on a `SubFS` works without issue on `v2.4.11` as far as I can tell:
```python
import fs
print(fs.__version__)   # v2.4.11

with fs.open_fs("temp://") as tmp:
    sub = tmp.makedir("subdir")
    print(type(sub))   # <class 'fs.subfs.SubFS'>
  
    sub.writetext("test", "this is a test")
    print(sub.readtext("test"))  # this is a test
```

**Comment by geoffjukes** [comment]
@althonos It took a while to locate the project that I had the issue in, and then the Git history for the requirements.txt and the problematic file.

It looks like, at the time of writing the ticket, the impacted project was running v2.1.0. I updated to 2.4.11 after reporting the issue, which (as you pointed out) is now fixed.

Apologies for the wild goose chase!

**Comment by althonos** [comment]
No problem!
