### ISSUE TITLE
WriteTarFs temp_fs arg type error

### ISSUE THREAD

**Issue by SF-300** [PyFilesystem/pyfilesystem2#410]
Hi!

`temp_fs` argument in `WriteTarFs.__init__ ` is annotated as `Text`, but should be `Union[FS, Text]` as it's directly forwarded to `open_fs`.

**Comment by lurch** [comment]
Hmmm?
https://github.com/PyFilesystem/pyfilesystem2/blob/master/fs/tarfs.py#L66 says "temp_fs (str): An FS URL for the temporary filesystem used to store data prior to tarring." and https://github.com/PyFilesystem/pyfilesystem2/blob/master/fs/opener/base.py#L32 also says "fs_url (str): A filesystem URL." :man_shrugging:

**Comment by SF-300** [comment]
`fs.opener.registry.Registry.open_fs`, not `fs.opener.base.Opener.open_fs`. Didn't see that there are a couple of them =)

**Comment by lurch** [comment]
> `fs.opener.registry.Registry.open_fs`, not `fs.opener.base.Opener.open_fs`.

Ah yes: https://github.com/PyFilesystem/pyfilesystem2/blob/master/fs/opener/__init__.py#L17

> Didn't see that there are a couple of them =)

Oh! Neither did I :laughing: 

Does that mean https://github.com/PyFilesystem/pyfilesystem2/blob/master/fs/opener/registry.py#L202 ought to be updated too?

**Comment by althonos** [comment]
`temp_fs` parameter of `WriteTarFs.__init__ ` and `WriteZipFS.__init__` has been marked to accept a `FS` instance in addition to `Text`.
