### ISSUE TITLE
Is there a way to save/load MemoryFS to/from a single binary?

### ISSUE THREAD

**Issue by samtatasurya** [PyFilesystem/pyfilesystem2#412]
I wonder if there exists a way / API to save the current state of `MemoryFS` to a single binary file, so that at a later time we can create a new `MemoryFS` instance, load the data from that single binary file, and essentially continuing from the last-saved state?

I know that there exists `fs.copy.copy_fs()` and `fs.move.move_fs()` as suggested from this link: [https://stackoverflow.com/a/51508921/4879957](url), but it is not exactly what I want in my use case.

**Comment by lurch** [comment]
What's wrong with copying the MemoryFS into a TarFS?

**Comment by samtatasurya** [comment]
Hi Andrew,

Thank you for pointing me to `TarFS`. Yes copying filesystem from `MemoryFS` to `TarFS` works for the case I mentioned.

Here's my test code in case anyone has the same question can refer to later on.

```
import fs

from fs.copy import copy_fs
from fs.memoryfs import MemoryFS
from fs.tarfs import TarFS


def save():
    """ Save in-memory fs as tar fs. """
    mem_fs = MemoryFS()

    # Populate in-memory fs
    mem_fs.makedir("foo")
    fobj = mem_fs.openbin("foo/bar.txt", mode="w+")
    fobj.write(b"hello world")

    print(mem_fs.listdir("."))  # should return ["foo"]
    print(mem_fs.listdir("foo"))  # should return ["bar.txt"]
    fobj.seek(0)
    print(fobj.read())  # should return b"hello world"

    with TarFS("tmp.tar", write=True) as tar_fs:
        copy_fs(mem_fs, tar_fs)


def load():
    """ Load tar fs to memory. """
    mem_fs = MemoryFS()
    with TarFS("tmp.tar") as tar_fs:
        copy_fs(tar_fs, mem_fs)

    # Confirm the contents of fs
    print(mem_fs.listdir("."))  # should return ["foo"]
    print(mem_fs.listdir("foo"))  # should return ["bar.txt"]
    fobj = mem_fs.openbin("foo/bar.txt", mode="r")
    print(fobj.read())  # should return b"hello world"


def main():
    save()
    load()


if __name__ == "__main__":
    main()
```
