### ISSUE TITLE
FTP connection with proxy

### ISSUE THREAD

**Issue by Zujiry** [PyFilesystem/pyfilesystem2#419]
Hello, so I want to open a FTP filesystem via a proxy like this:
```
ftp = ftp://user@server:password@proxy_server/path
with open_fs(ftp) as fs:
                fs_list = fs.listdir()
```
The same in FTP:
```
with FTP("proxy_server") as ftp:
                ftp.login(user='user@server', passwd='password')
                prop = ftp.dir('/path')
```
works for me. Is that an error in the parsing of the address?

**Comment by dargueta** [comment]
The syntax for a URL is `ftp://user:password@server/path`. I think that might be your problem?

**Comment by althonos** [comment]
Yes, the proxy has to be percent-encoded and passed as a parameter, so:
```python
ftp = "ftp://user@server:password/path?proxy=proxy_server"
fs = open_fs(ftp)
```

**Comment by Zujiry** [comment]
> The syntax for a URL is `ftp://user:password@server/path`. I think that might be your problem?

Normally it would be, but the problem was, that I did not know how to add a proxy, which is done with user@proxy:password in some cases.

Thanks for your answer althonos!

**Comment by lurch** [comment]
@althonos Should that be added to https://docs.pyfilesystem.org/en/latest/openers.html ?

@Zujiry For future reference, I think you normally get more control by constructing the filesystem directly (e.g. https://docs.pyfilesystem.org/en/latest/reference/ftpfs.html ) rather than using the `open_fs` wrapper?

**Comment by althonos** [comment]
@lurch : this is something done on a case-per-case basis by openers (some external filesystems may not support passing arguments via URL parameters), so I'll add it to the `FTPFS` doc instead.

**Comment by althonos** [comment]
Reopening to remind me to update the documentation.

**Comment by Zujiry** [comment]
Sorry, just wanted to ask, if there is a possibility to have the port also specified in 
`ftp = "ftp://user@server:password/path?proxy=proxy_server"`

**Comment by althonos** [comment]
If you mean the port of the server, then yeah:
```
 ftp = "ftp://user:password@server:port/path?proxy=proxy_server"
```
However I don't think one can change the proxy server port.

**Comment by Zujiry** [comment]
Thanks a bunch! I did not think, the structure (user@server -> user:password@server) would have to be changed.

**Comment by althonos** [comment]
I added these examples to the docstring of `FTPFS` so its hopefully cleared on how to use a proxy server.
