### ISSUE TITLE
Reference to fs.webdav in the docs

### ISSUE THREAD

**Issue by zopyx** [PyFilesystem/pyfilesystem2#42]
Please add a reference to 

https://pypi.python.org/pypi/fs.webdavfs

in the official docs.

**Comment by willmcgugan** [comment]
Will do

**Comment by willmcgugan** [comment]
I've added https://github.com/PyFilesystem/pyfilesystem2/blob/master/docs/source/external.rst

Feel free to edit that, if you want to supply more information.
