### ISSUE TITLE
Example for TempFS looks wrong

### ISSUE THREAD

**Issue by BrendanSimon** [PyFilesystem/pyfilesystem2#423]
Example in TempFS documentation looks wrong. 

https://docs.pyfilesystem.org/en/latest/reference/tempfs.html

It uses `OSFS` and there is no sign of `TempFS` !!

```python
with OSFS('~/Desktop') as desktop_fs:
```

Also, what is the URI/URL for TempFS?  Is it `tmpfs://` or `tempfs://` or something else?

**Comment by BrendanSimon** [comment]
Well I cloned the repo to dig further and it looks like the URI/URL for TempFS is `tempfs://`

**Comment by althonos** [comment]
It's because the documentation for the method you see is actually inherited from `OSFS.close`, since `TempFS` is actually an `OSFS` subclass that handles a temporary folder for you.

**Comment by BrendanSimon** [comment]
Ok, I see that the docs for other classes have the same code examples.  I'm not sure how helpful it is to describe a class but give code example for a different class.  It might be the main point of the example given is to show how to use a context manager, however it would add more value if it was using the actual class the documentation is describing.

The `TempFS` documentation still seems to be missing the basic usage example and the FS URL that is displayed on other pages.
e.g. https://docs.pyfilesystem.org/en/latest/reference/memoryfs.html

**Comment by althonos** [comment]
`TempFS` now has examples on how to open it with the constructor or with a FS URL. `TempFS.close` now shows an example specific to `TempFS`, and explicitly mentions the `auto_clean` argument.
