### ISSUE TITLE
Callbacks?

### ISSUE THREAD

**Issue by jw** [PyFilesystem/pyfilesystem2#432]
Hello guys,

Maybe a weird question, but why are there no callback methods in the fs?
Or am I missing them?

If I am correct, are there plans to add them in?

I just created my own callback for the download command.

In base.py:
```
         with self._lock:
+            callback = options.pop("callback", None)
             with self.openbin(path, **options) as read_file:
-                tools.copy_file_data(read_file, file, chunk_size=chunk_size)
+                tools.copy_file_data(read_file, file, chunk_size=chunk_size, callback=callback)
```

and in tools.py

```
-        write(chunk)
+        bytes = write(chunk)
+        if callback:
+            callback(bytes)
```

What do you think about it?

**Comment by althonos** [comment]
As discussed in #433 , callbacks are not possible to guarantee for all filesystems (in particular external ones) so you are encouraged to write your own file-handle-based routines when needed :smiley:
