### ISSUE TITLE
open_fs(".", writeable=False) returns an FS object which can write

### ISSUE THREAD

**Issue by mezhaka** [PyFilesystem/pyfilesystem2#441]
I'd like to have read-only FS, however I am able to do
```python
from fs.opener import open_fs
with open_fs(".", writeable=False) as fs_:
    fs_.writetext("spam", "vikings")
```
I'd expect it to fail, like the
```python
from fs.wrap import read_only, WrapReadOnly
r = read_only(fs_)
r.writetext("spam", "vikings")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/disks/repo/bin/miniconda3/envs/deeplearning/lib/python3.8/site-packages/fs/wrap.py", line 221, in writetext
    raise ResourceReadOnly(path)
fs.errors.ResourceReadOnly: resource 'spam' is read only
```

**Comment by lurch** [comment]
I've had a quick search through the code-base, and it looks like most "openers" simply ignore the `writeable` parameter, and it seems to be only e.g. tarfs and zipfs where the same "FS" can't be both read-and-write-at-the-same-time that actually use the `writeable` parameter.

As you've seen, you **can** achieve what you want with the `read_only` WrapFS, so maybe this is just a documentation issue?

**Comment by willmcgugan** [comment]
This is what the docs say...

```
writeable (bool, optional) – True if the filesystem must be writeable.
```

So if `writable=True` the filesystem will be writable, but the inverse isn't necessarily true. i.e. `writable=False` means it doesn't need to be writable (but it could be). A documentation issue perhaps. Open to adding something to clarify.

**Comment by althonos** [comment]
I updated the documentation for `fs.open_fs` with a section specifically about this. It now says:
```
Caution:
        The ``writeable`` parameter only controls whether the
        filesystem *needs* to be writable, which is relevant for
        some archive filesystems. Passing ``writeable=False`` will
        **not** make the return filesystem read-only. For this,
        consider using `fs.wrap.read_only` to wrap the returned
        instance.
```
