### ISSUE TITLE
Missing build instructions

### ISSUE THREAD

**Issue by ToddG** [PyFilesystem/pyfilesystem2#444]
**WHAT**
There are no build and test instructions in the readme here, or in sf3fs.

**WHY**
This is important to get other developers interested in contributing.

**HOW**
Personally, I use `poetry` and `pyenv` to structure my Python projects. I also like `make` and tend to surface my projects in exactly the same way as in this project. With one exception. I typically provide some sort of environment configuration task to download all the various bits needed to build/test/doc etc. With that said, I find using `poetry` and `noxfiles` vastly simplifies these things. Here's what would make this project much easier to contribute to...in increasing order of effort:

* Dependencies : document all the deps I need to install to build and test thes repos (incl. s3fs)
* Makefile : add a task to download and install all the goodies needed
* Or move beyond Makefiles and tox and upgrade to `poetry`, `nox`, etc.

Just adding documentation would be enough. Extending this to the Makefiles would be great. Upgrading to `poetry` and `nox` would be awesome.

Here are some links for context as to what I'm suggesting:

* cjolowicz's [hypermodern-python post](https://cjolowicz.github.io/posts/hypermodern-python-01-setup/)
* [my take on hypyermodern-python](https://github.com/ToddG/hypermodern-python-seed)

**Comment by althonos** [comment]
Hi @ToddG ,

It's true that we are lacking documentation in this area, I'll make sure to add something about this to the `README.md`. The one issue with `make` is that it is not entirely cross-platform, but most of what we do is already covered very simple and standard commands.

### Tests

Although you can run tests without it, the easiest way to test Pyfilesystem2 is with `tox`. Make sure you have it installed, and run it in the project directory: it will install dependencies and run tests for every installed Python versions in a sandboxed environment.

### Docs

For the docs, you need Sphinx and `sphinx-rtd-theme`. Then run `python setup.py build_sphinx`, and open `build/sphinx/html/index.html` when the build is complete to have the documentation.
