### ISSUE TITLE
ZipFS, TarFS don't call self.write_zip(), self.write_tar() when program exits

### ISSUE THREAD

**Issue by krysopath** [PyFilesystem/pyfilesystem2#45]
I may be doing something wrong, but it seems to me, that I have to call it myself on exit.

```
class MyFS:
    def __init__(self):
        self.osfs = OSFS(__DIR__)

        self.memoryfs = MemoryFS()
        self.archivefs = TarFS(
            __WALLETDIR__ + "container.tbz",
            write=True,
            compression="bz2"
        )

        self.fs = MountFS()
        self.fs.mount('ram', self.memoryfs)
        self.fs.mount('archive', self.archivefs)
        self.fs.mount('os', self.osfs)

wallet = WalletFS()
wallet.fs.settext('archive/testfile1.txt', "this is content")
wallet.archivefs.close()
```

If I do not call `wallet.archivefs.close()`, 'archive/testfile1.txt' does not get written to the archive. It is the same with ZipFS for that matter. So I ask here, what am I doing wrong? Or how do I  ensure that files will be written, without invoking `.close()` myself?

ps.: In the latest build I got via pip, there is a leftover debug print statement in tarfs.py on line 154. It bugs the hell out of me :)

**Comment by krysopath** [comment]
Aha, I just missed the relevant part in the doc.
implicit calling of .close() is only done when using context managers.

**Comment by willmcgugan** [comment]
Removed that print statement. Sorry about that!

**Comment by krysopath** [comment]
A small thing is leftover print is when compared to the usefulness of this module. Thx!
