### ISSUE TITLE
original timestamp (ctime, mtime) cannot survive a copy_fs or mirror

### ISSUE THREAD

**Issue by mo-han** [PyFilesystem/pyfilesystem2#450]
as long as there's actual "copy" operation from one fs to another, then those "touched" files will lost their original ctime or mtime, which would be updated to the time when that copy operation happened.
this is not expected feature. though calling it "critical bug" might be too harsh but still it's much better if it could be fixed.

**Comment by althonos** [comment]
One thing we could do would be a `preserve_timestamp` keyword argument to `fs.copy` method, and maybe to `fs.base.FS.copy` as well, that basically attempts to update the `(ctime, mtime)` after copying.

**Comment by mo-han** [comment]
> 
> 
> One thing we could do would be a `preserve_timestamp` keyword argument ...

Maybe make that default? At least make it defaut for `mirror`.
