### ISSUE TITLE
FTPFS does not list certain folders

### ISSUE THREAD

**Issue by bgruening** [PyFilesystem/pyfilesystem2#451]
It seems that the pub folder is not listed and igrnoed. ftplib does show the folder. This is with python 3.8.

```python
import fs
fs.__version__

# 2.4.12

from fs.ftpfs import FTPFS
a = FTP(host='ftp.ensemblgenomes.org', user="anonymous", passwd="")
a.dir()

""""
drwxr-sr-x   72 ftp      ftp          8192 Feb 16 02:00 pub
-rw-r--r--    1 ftp      ftp            25 Jan 06 22:41 robots.txt
""""

from ftplib import FTP
a = FTPFS(host='ftp.ensemblgenomes.org')
a.listdir('.')

# ['robots.txt']
```

**Comment by althonos** [comment]
Hmm, could be an issue with the #439, which changed the FTP list parsing. I'll have a look when I can.

**Comment by bgruening** [comment]
Thanks @althonos!

**Comment by althonos** [comment]
Hi @bgruening , this was indeed an issue with the FTP parser. It was fixed in #473 , and will be patched in `v2.4.13`.

**Comment by bgruening** [comment]
Oh awesome. You rock @althonos!

**Comment by althonos** [comment]
@bgruening : `v2.4.13` is out, so you should be able to update without issue now!
