### ISSUE TITLE
convert_os_errors error when converting errno.ENAMETOOLONG to PathError

### ISSUE THREAD

**Issue by isaacHuh** [PyFilesystem/pyfilesystem2#453]
Using convert_os_errors to convert errno.ENAMETOOLONG to PathError results in unexpected keyword arguement 'exc' error. Seems that [this line](https://github.com/PyFilesystem/pyfilesystem2/blob/8784fd61797fac654511f16fd50c38c8a1675f16/fs/error_tools.py#L89) will set exc=exc_value however PathError does not take in exc parameter.

The following example code:
```
import errno
from fs.error_tools import convert_os_errors
from fs import errors as fserrors

try:
	from fs import open_fs
	f = open_fs('/tmp')
	f.open('x'*500, mode='w')
except OSError as e:
    with convert_os_errors("foo", "test"):
        raise e
```
results in: TypeError: __init__() got an unexpected keyword argument 'exc'

**Comment by althonos** [comment]
Thanks! I've updated `PathError` so that it can be passed an exception. The fix will be available in the next release (`v2.4.13`).
