### ISSUE TITLE
Watch Feature?

### ISSUE THREAD

**Issue by Zujiry** [PyFilesystem/pyfilesystem2#476]
I saw that watch was a feature in pyfilesystem, does pyfilesystem2 feature a watch() functionality in any way? I did not find anything in the documentation therefore I guess it does not exist anymore?

**Comment by althonos** [comment]
Hi @Zujiry ,

PyFilesystem2 does not support `watch`, but it could be feasible to create a `WrapFS` with the same kind of functionality should you need it.

**Comment by Zujiry** [comment]
Thank you althonos, but I have to wriggle myself through this idea.
So you mean to wrap a directory as a virtual filesystem, then watch changes in the filesystem? Or is there a way to get events in the virtual filesystem and then react to them via a thread?

**Comment by atollk** [comment]
For people who are not familiar with pyfilesystem, can you explain what exactly you expect from a "watch functionality"?

**Comment by Zujiry** [comment]
Of course. The idea is, that you have fs.watch() the filesystem fs. Now, whenever something changes in the filesystem (e.g. a file is created in a directory) an event is triggered that can be caught and reacted upon with a function. E.g. if you have fs.watch(function_to_trigger, args) the function_to_trigger(args) would trigger on each event.
 
A linux variant would be [inotify](https://www.man7.org/linux/man-pages/man7/inotify.7.html).

**Comment by atollk** [comment]
I see. If you're watching for external changes, then I feel like a manual solution (e.g. via a wrapper class) using a thread to manually check changes is your best bet. Tools like inotify are (imo) too platform specific and start to be unreliable as soon as the file resources can be accessed from other sources than the OS which inotify is running on, so it wouldn't make sense to use them in a general purpose tool such as PyFs.

**Comment by Zujiry** [comment]
Thank you atollk, what you are saying makes sense to me.
I will close this thread with your thought :)
