### ISSUE TITLE
fs.path.join removes a / from a FS_URL

### ISSUE THREAD

**Issue by ReimarBauer** [PyFilesystem/pyfilesystem2#482]
I've not seen in the documentation that this should happen

```
>>> fs.path.join('osfs://~/', 'ddd')
'osfs:/~/ddd'
````
in difference to

```
>>> fs.path.combine('osfs://~/', 'ddd')
'osfs://~/ddd'
```

**Comment by lurch** [comment]
You're using FS URLs with fs.path functions - I think that's undefined behaviour? Typically you'd build your FS object (possibly from an FS URL), do whatever manipulations you needed, and then call `myfs.geturl(path, purpose="fs")` to get another FS URL back out? https://docs.pyfilesystem.org/en/latest/_modules/fs/osfs.html#OSFS.geturl

@althonos Should `purpose="fs"` be documented [here](https://docs.pyfilesystem.org/en/latest/reference/base.html#fs.base.FS.geturl) ?

**Comment by althonos** [comment]
@lurch : indeed, with a link to the [FS URLs](https://docs.pyfilesystem.org/en/latest/openers.html) page as well to disambiguate.
