### ISSUE TITLE
why do i need to restart after installing fs_s3fs on colab

### ISSUE THREAD

**Issue by simonm3** [PyFilesystem/pyfilesystem2#485]
If I pip install fs_s3fs on colab then try to access s3 it says "Unsupported protocol "s3" is not supported". I restart the runtime and it works. On windows the restart is not required. I know colab requires a restart after existing packages are upgraded but they always post a warning message.

Is it possible to register the s3 driver on colab without a restart? If not then I suggest add a warning message.

versions fs=1.1.1 fs_s3fs=2.4.13

**Comment by lurch** [comment]
I'd never heard of "colab" before, but I did a quick search and I guess you're talking about https://research.google.com/colaboratory/faq.html ?

Does it work if you use the "constructor" method rather than the "FS URL" method? https://github.com/PyFilesystem/s3fs#opening-a-s3fs

**Comment by willmcgugan** [comment]
It’s basically Google’s version of Jupyter notebooks. I suspect the way it imports packages is circumventing the installation of protocols via namespace packages.

Suspect this is a Colab problem. I doubt there Is any way we could even add warning message.

**Comment by simonm3** [comment]
Yes it works with the constructor method. However even after doing that successfully you cannot use open_fs until a restart. 
Colab provides free gpus but restricted to access via a notebook - still a free gpu is a big help for machine learning.

If it is a colab problem then it probably won't get fixed. Just wondered if there was a way to avoid it as it is unexpected to have to restart after an install.

**Comment by lurch** [comment]
> Yes it works with the constructor method. However even after doing that successfully you cannot use open_fs until a restart.

In which case, "don't use open_fs" sounds like the easiest workaround? :shrug:

**Comment by althonos** [comment]
The `fs.opener` registry uses an [entry point](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#entry-points) to install external openers, and it does so once, when you import `fs` for the first time. 

You can however install the opener manually at any time with the `Registry.install` method:
```python
import fs.opener
from fs_s3fs.opener import S3FSOpener

fs.opener.registry.install(S3FSOpener)
# fs.open_fs("s3fs://...") should now work
```

**Comment by lurch** [comment]
@althonos Nice - is it worth adding that to the docs?
