### ISSUE TITLE
Question opendir factory

### ISSUE THREAD

**Issue by dAnjou** [PyFilesystem/pyfilesystem2#492]
Hi, the type of `opendir`'s factory is defined [like this](https://github.com/PyFilesystem/pyfilesystem2/blob/12cd2f416a641f9c81effb741620f939c8021aca/fs/base.py#L61):

    _OpendirFactory = Callable[[_T, Text], SubFS[_T]]

The documentation of `SubFS`, however, says:

> A sub-directory on another filesystem.

This seems contradictory to me. According to the type definition, both parent and sub filesystem need to be of the same type (`_T`) but the documentation sounds like the sub filesystem can be any other type.

Not a blocker, just noticed it because my type checker started complaining.

**Comment by lurch** [comment]
I think the "on another filesystem" in the [SubFS docs](https://docs.pyfilesystem.org/en/latest/reference/subfs.html) might implicitly mean "of a parent filesystem"? So AFAIK "both parent and sub filesystem need to be of the same type" is true?
(Although personally I have no knowledge of type-checking in Python, so maybe one of the other developers will be able to give a more useful answer :wink: )

**Comment by althonos** [comment]
Yes, as @lurch pointed, the *another* filesystem is taking the `SubFS` as a reference, so the *another* is actually its parent. The factory is expected to take the parent filesystem and the subfolder path, and to open a new `SubFS` in that path. This is mostly something we use internally to make sure filesystems are properly closed (bug: #51, PR: #53). 

Effectively, a `SubFS` subclass should be passed to the `factory`, not just any callable, but as long as it returns a `SubFS` we're fine with it.
