### ISSUE TITLE
fs.smb paths containing valid commas throws InvalidCharsInPath

### ISSUE THREAD

**Issue by SamRWest** [PyFilesystem/pyfilesystem2#494]
Hi,

**UPDATE:** 
I just realised that the `invalid_path_chars` are defined by fs.smbfs, not pyfilesystem.
For reference a simple workaround is just to set
```python
SMBFS._meta['invalid_path_chars'] = '\0"\[]:+|<>=;?*'
```
before accessing the offending path.

**ORIGINAL TEXT:**

I'm using `fs.smbfs==1.0.2` and `PyFilesystem==2.4.13` (also tested with today's git master).
The issue is that any smb with comma (,) characters in the path throws a `fs.errors.InvalidCharsInPath` from all functions I've tried.

As far as I can tell, comma is not actually an invalid character for this protocol/server though. 
Happy to submit a PR if this is a valid fix (see below), but I'm not sure whether commas _are_ actually invalid in some settings, and this fix is too simplistic. 

Here's a test to illustrate the issue:

``` python
    def test_smb_paths_with_commas(self):
        import socket
        import fs

        remote_host = 'server.com'
        share_path = "/path,with,commas"

        un = os.environ.get('SMB_UN')
        pw = os.environ.get('SMB_PW')
        domain = os.environ.get('SMB_DOMAIN')

        direct_tcp = True
        use_ntlm_v2 = True
        conn_port = 139 if direct_tcp is False else 445
        remote_ip = socket.gethostbyname(remote_host)

        smb_fs = fs.open_fs(f"smb://{un}:{pw}@{remote_ip}:{conn_port}/?direct-tcp={direct_tcp}&use_ntlm_v2={use_ntlm_v2}&domain={domain}&hostname={remote_host}")
        smb_fs.tree(path=share_path)  # throws fs.errors.InvalidCharsInPath: path '/path,with,commas' contains invalid characters

```

My simple fix is to change this section (starting line 1529) in fs.base.validatepath():
``` python
        invalid_chars = typing.cast(six.text_type, meta.get("invalid_path_chars"))
        if invalid_chars:
            if set(path).intersection(invalid_chars):
                raise errors.InvalidCharsInPath(path)

```
to this:
``` python
        invalid_chars = typing.cast(six.text_type, meta.get("invalid_path_chars"))
        invalid_chars = invalid_chars.replace(',','') # commas aren't invalid chars?!
        if invalid_chars:
            if set(path).intersection(invalid_chars):
                raise errors.InvalidCharsInPath(path)

```

And then my test passes fine.

**Comment by dargueta** [comment]
I guess we can close this then?

**Comment by althonos** [comment]
I think I can move this to althonos/fs.smbfs once I get back to my computer.

**Comment by SamuelWest** [comment]
Yep, you can close it. I'll follow up in the fs.smbfs issue instead. Sorry for the confusion.
