### ISSUE TITLE
What is the path to a Virtual Memory file created?

### ISSUE THREAD

**Issue by yuriachermann** [PyFilesystem/pyfilesystem2#495]
I'm trying to create a virtual XML file, copy some content to it, then access throw parsing, it may be simple, but every path that I'm trying to use ( like `'mem://mem_test.xml'` or `'{}'.format(mem_file)` ) are not working... What path should I use to access a file in the Virtual Memory?

```
import fs
import xml.etree.ElementTree as Et

mem_fs = fs.open_fs('mem://')
os_fs = fs.open_fs(".")
mem_file = mem_fs.open('mem_test.xml', 'rw')
fs.copy.copy_file(os_fs, 'test.xml', mem_fs, 'mem_test.xml')
tree = Et.parse('[string with path to mem_test]')
root = tree.getroot()
```

**Comment by dargueta** [comment]
What do you mean "is not working"? Are you getting an exception?

**Comment by yuriachermann** [comment]
I got this error:
```
Traceback (most recent call last):
  File "/home/yuri/OR/test.py", line 8, in <module>
    tree = Et.parse('mem_test.xml')
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'mem_test.xml'
```

**Comment by althonos** [comment]
Hi @yuriachermann , the whole point of `MemoryFS` is that it doesn't lie anywhere on you actual filesystem... So contrary to some other filesystems (like `TempFS`) resources on a `MemoryFS` won't have a [syspath](https://docs.pyfilesystem.org/en/latest/concepts.html#system-paths) that you can use.

However, the [`ElementTree.parse`](https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.parse) function also accepts a file object, so you can make you code work by getting a file handle from the `MemoryFS` and passing it to the function:
```python
import fs
import xml.etree.ElementTree as Et

mem_fs = fs.open_fs('mem://')
os_fs = fs.open_fs(".")
# mem_file = mem_fs.open('mem_test.xml', 'rw') # you don't need this, copy_file will create the file for you
fs.copy.copy_file(os_fs, 'test.xml', mem_fs, 'mem_test.xml')

with mem_fs.open('mem_test.xml') as mem_file:
    tree = Et.parse(mem_file)
root = tree.getroot()
```
