### ISSUE TITLE
Have objects returned by openbin inherit from IO.IOBase

### ISSUE THREAD

**Issue by althonos** [PyFilesystem/pyfilesystem2#50]
To support interfacing with the Python standard library, "file-like" objects should extend the [`IO.IOBase`](https://docs.python.org/3/library/io.html#io.IOBase) class (not really an abstract base class, but does nothing by itself), and the `fs.test.FSTestCases.openbin` updated accordingly with a `self.assertIsInstance(...)`.

Following classes are concerned, since the other filesystems already return a proper child object (`OSFS` and derived, `ZipFS`, `TarFS`)
* `fs.ftpfs.FTPFile`
* `fs.iotools.RawWrapper`
* `fs.memoryfs._MemoryFile`

I can provide a PR if you don't have the time to work on this @willmcgugan.

NB: neither `_MemoryFile` nor `FTPFile` implement `seekable`, `writeable` or `readable`, so they should be implemented to avoid returning `False` all the time like in the default `ÌOBase` implementation.

**Comment by willmcgugan** [comment]
Sounds like a good idea. The differences between file-like objects has always been irksome. A PR would be great.

**Comment by willmcgugan** [comment]
https://github.com/PyFilesystem/pyfilesystem2/pull/52
