### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by adriangb** [PyFilesystem/pyfilesystem2#501]
Hi, are there any plans for a new release? Last one was in March, and there's a critical fix I need that is in git but not released. Thanks!

**Comment by althonos** [comment]
I'm a bit busy this week regarding scientific stuff, and I wanted to address some documentation stuff before merging. I'll try to get that done next week, I agree it's been some time since last release.

**Comment by adriangb** [comment]
Awesome, thank you!

**Comment by althonos** [comment]
Sorry it took longer than expected, but `v2.4.14` is out now!
