### ISSUE TITLE
Delegate filesystems opened with fs.open_fs never close the base filesystem

### ISSUE THREAD

**Issue by althonos** [PyFilesystem/pyfilesystem2#51]
When using `fs.open_fs` to open a FS URL with an associated directory, the returned filesystem is a `SubFS`. Those are made not to close the delegate filesystem, which is perfectly fine because else the following code:
```python
with my_fs.opendir("/some/path") as dirfs:
    # ... do stuff ...
```
would cause `my_fs` to be closed otherwise.

**BUT** the side effect is that, if you open a resource with a path, then the filesystem will not be closed when you think you are closing it.

```python
from fs import open_fs

ebi_ftp = open_fs("ftp://ftp.ebi.ac.uk/pub/phd")
ebi_ftp.close()       # the actual FTPFS is not closed since ebi_ftp is a SubFS

ebi_ftp.isclosed()  # True
ebi_ftp.delegate_fs().is_closed() # False
```

So, when you expect a context manager to close the filesystem, it actually doesn't:
```python
with open_fs("ftp://ftp.ebi.ac.uk/pub/databases") as ebi_db:
     # ... blah blah ... #

print("Done working on the remote FTP server !)
print("I'm happy the FTP connection was closed automatically thanks to Pyfilesystem2")
# It wasn't.
```

**Comment by willmcgugan** [comment]
Ah. What do you think would be the best way to handle that? Maybe a specialized version of `SubFS` that closes its parent?

**Comment by althonos** [comment]
Yes, I was thinking about that as well, some kind of `ChrootFS` created only inside of `open_fs`, and that would just be a `SubFS` that would close the delegate.

**Comment by willmcgugan** [comment]
Any thoughts on https://github.com/PyFilesystem/pyfilesystem2/pull/53 ?

**Comment by althonos** [comment]
Fine by me !
