### ISSUE TITLE
Move away from pytz

### ISSUE THREAD

**Issue by djmattyg007** [PyFilesystem/pyfilesystem2#516]
pytz is known for doing funky things that aren't really compatible with the rest of the python ecosystem and in some cases simply don't make sense. Their timezone objects aren't even compatible with actual Python tzinfo objects.

Here's a discussion from matplotlib where they decided to drop it in favour of dateutil, which has also been recommended by the python documentation for years now:

https://github.com/matplotlib/matplotlib/issues/10443/

Alternatively (if you're willing to drop support for Python 3.8 and below), Python 3.9 has a new built-in zoneinfo module in the stdlib that provides the common use case of just loading timezone objects by name with accurate timezone info.

**Comment by djmattyg007** [comment]
This article provides a great writeup of why pytz is dangerous:

https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html

**Comment by lurch** [comment]
> This article provides a great writeup of why pytz is dangerous:
> 
> https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html

Interesting. `pytz` doesn't [appear to be used](https://github.com/PyFilesystem/pyfilesystem2/search?q=pytz) in too many places in PyFilesystem, so do you wanna create a suitable PR?

**Comment by djmattyg007** [comment]
Sure!
