### ISSUE TITLE
Moving to platformdirs results in changed paths in AppFS

### ISSUE THREAD

**Issue by tfeldmann** [PyFilesystem/pyfilesystem2#530]
Before:

```python
>>> fs.__version__
'2.4.15'
>>> fs.open_fs("userconf://test:test", create=True).getsyspath("/")
'/Users/tf/Library/Application Support/test/'
```

Current master branch:
```python
>>> fs.open_fs("userconf://test:test", create=True).getsyspath("/")
'/Users/tf/Library/Preferences/test/'
```

I don't think switching to platformdirs is such a good idea at this time. The paths seem to change even in minor version bumps:
https://github.com/platformdirs/platformdirs/issues/47

**Comment by althonos** [comment]
Oh, damn. I was expecting it to be a simple fork but we may want to go for stability.

**Comment by lurch** [comment]
ping @felixonmars who contributed #489

**Comment by felixonmars** [comment]
That's unfortunate :(

It seems it's not a minor version change though, according to replies to the linked issue. Sorry for overlooking it, but I still think this is a valid move because `appdirs` is indeed abandoned. Perhaps we could delay it to a later major bump?

**Comment by althonos** [comment]
I've reverted the patch from @felixonmars so that we can wait for a major release before changing it. For PyFilesystem3 we'll want to make the transition to `platformdirs`, but for now let's keep the things stable.
