### ISSUE TITLE
Invalid `isort` options in `setup.cfg`

### ISSUE THREAD

**Issue by tfeldmann** [PyFilesystem/pyfilesystem2#531]
I noticed isort is not working because `THIRD_PARTY` should be `THIRDPARTY` (https://pycqa.github.io/isort/docs/configuration/custom_sections_and_ordering.html).

Additionally I'd propose the settings:
```
profile = black
skip_gitignore = true
```
 
to enable black compatibility mode.

This touches quite a lot of files. Shall I submit a PR for that?

**Comment by lurch** [comment]
Sounds good to me :+1:

**Comment by althonos** [comment]
I'm also happy to merge if you make a PR for this!

**Comment by althonos** [comment]
Fixed in 486cf3aa49532fd70d22fb19429cc6d7c2eceb0a.
