### ISSUE TITLE
[FTPFS] Consider restructuring the initialisation of FTPFS

### ISSUE THREAD

**Issue by althonos** [PyFilesystem/pyfilesystem2#54]
I have some reserves about the initialisation of a FTPFS object, that come from the fact the FTP connection is not created right away:
* Keeping the password as an attribute of the `FTPFS` is IMO a bad idea for obvious security reasons
* If there's an authentification issue, it will not occur when creating the filesystem, but only after the first use of any `FS` method, causing a `PermissionDenied` to be raised.

So when a user creates a filesystem, he won't see any error until later in his code, which is not consistent with the way every other filesystem work (directly raising a `CreateFailed` error). 

But I suppose it is just a matter of taste, whether to classify an authentification error as a permission issue (could connect to the FTP server but not access to resources since the login failed) VS a filesystem creation issue (we connected to the FTP server but all of the resources will be unreachable, which for me sounds like a failure).

**Comment by willmcgugan** [comment]
> Keeping the password as an attribute of the FTPFS is IMO a bad idea for obvious security reasons

I'm not sure that is avoidable. FTPFS creates a new connection for each open file, which naturally requires a password. If it didn't do that then there would be no way to open more than one file at a time, or do other FS operations while a file is open.

> If there's an authentification issue, it will not occur when creating the filesystem, but only after the first use of any FS method, causing a PermissionDenied to be raised.

This is true. But from my use case it is essential. I use FS mostly for web development, where I construct an FS object on startup. I don't want the constructor to block or cause errors before the server even run -- so I like to keep the constructor light-weight.

It's also worth pointing out that a password failure is not necessarily a permanent state. A user account may be added or modified during the life-time of a FTPFS. Admittedly thats not all that likely, but certainly possible.

I do get the point that you might want to know about a password error prior to using the FS instance. Perhaps there is room for a method which can check the availability of the filesystem, without modifying it? Something similar to `os.access`. Open to suggestions for that one...

**Comment by althonos** [comment]
> I'm not sure that is avoidable. FTPFS creates a new connection for each open file, which naturally requires a password. If it didn't do that then there would be no way to open more than one file at a time, or do other FS operations while a file is open.

Okay, I didn't read the code well enough to figure that, then this is mandatory, and since Python has no private members...

> I do get the point that you might want to know about a password error prior to using the FS instance. Perhaps there is room for a method which can check the availability of the filesystem, without modifying it? Something similar to os.access. Open to suggestions for that one...

Why not overload the `FTPFS.check` method for that ? I completely agree with your point, and as I said, this is more of a design matter, and you're the one who decides !

**Comment by willmcgugan** [comment]
> Why not overload the FTPFS.check method for that ?

That does make sense. But most methods call that, so it might introduce exceptions in to methods where they may not be expected.

Would calling `.getinfo("/")` to check for authentication problems be a fudge?

>  this is more of a design matter, and you're the one who decides !

Everything is up for discussion. :-)

**Comment by willmcgugan** [comment]
Going to close this one, but I am still pondering an option method that checks connectivity for network filesystems...
