### ISSUE TITLE
open_fs(writeable=True) doesn't care about read-only filesystems

### ISSUE THREAD

**Issue by althonos** [PyFilesystem/pyfilesystem2#55]
Just noticed this quite important bug: when calling `fs.open_fs` with `writeable` set to `True` (which according to the doc requires the given FS or FS URL to be writeable), nothing happens even if the given FS or FS URL maps to a read-only filesystem. I tried rolling back to `2.0.2`, issue was also there.

Can be reproduced with
```python
>>> fs.open_fs("/path/to/an/existing/file.zip", writeable=True)
```

I think the registry should raise an error (`CreateFailed`, `ResourceReadOnly` ?) if the returned filesystem is read-only according to its metadata, but for now it relies on the individual openers doing their things (and since none of them actually care about the `writeable` keyword, it doesn't do anything)

**Comment by willmcgugan** [comment]
Good point. I agree the opener should raise an error there.

Although for this particular example the opener should probably uncompress the zip file in to a tmp directory, and re-compress it on close. Since I don't think there is anyway to open a zip for updating. I guess Tar is the same?

**Comment by althonos** [comment]
> Although for this particular example the opener should probably uncompress the zip file in to a tmp directory, and re-compress it on close. Since I don't think there is anyway to open a zip for updating. I guess Tar is the same?

I'm working on an updatable archive filesystem, where entries are extracted to another filesystem only when modified, plus other features (read/write archive from/to streams, etc.). Currently I have the ZipFS implemented, and I'll add the TarFS shortly ;)

**Comment by willmcgugan** [comment]
> Currently I have the ZipFS implemented, and I'll add the TarFS shortly ;)

Awesome. :-)

Keeping this issue open as a reminder to look at the opener errors.

**Comment by willmcgugan** [comment]
I'm thinking this should be the responsibility of the Openers. If it is asked for a writable filesystem that it can't return, it should raise some new exception derived from OpenerError. Should only effect the archive filesystems in the main library currently.
