### ISSUE TITLE
How to work with libraries that expect a str or PathLike object?

### ISSUE THREAD

**Issue by cyrillkuettel** [PyFilesystem/pyfilesystem2#552]
Whenever I work with other libraries that operate on a file inside a filesystem, I always find myself calling `path.getsyspath`
and passing that into some function of that library.

For example:

```python
from fs.subfs import SubFS

archive_dir: SubFS = self.app.filestorage.makedirs("/parent")
archive_dir.create("archive.zip")

sys_path = archive_dir.getsyspath('archive.zip')
with ZipFile(sys_path, "w", ZIP_DEFLATED) as zip_file:
    for match in archive_dir.glob('**/*.csv'):
        zip_file.write(archive_dir.getsyspath(match.path))

```
This runs fine. However, if I don't use the `getsyspath`, 

```python
archive = archive_dir.open('archive.zip')
with ZipFile(archive, "w", ZIP_DEFLATED) as zip_file:
    for match in archive_dir.glob('**/*.csv'):
        zip_file.write(archive_dir.getsyspath(match.path))

```
I get:
>TypeError: write() argument must be str, not bytes

I'm very much depending on `getsyspath` to open files with other libraries. Is there a way to do this without `getsyspath`?

**Comment by dargueta** [comment]
In this specific case, you should be using [ZipFS](https://docs.pyfilesystem.org/en/latest/reference/zipfs.html) instead of accessing the archive.

**Comment by cyrillkuettel** [comment]
Thanks for the answer. My goal was to create a zip from a directory.
Using [ZipFS](https://docs.pyfilesystem.org/en/latest/reference/zipfs.html), this ended up being much more concise:

```python
from fs.copy import copy_dir
from fs.zipfs import ZipFS

archive_dir = self.app.filestorage.makedirs("/parent")
zip_filesystem = ZipFS("archive.zip", write=True)

copy_dir(src_fs=archive_dir, src_path=".", dst_fs=zip_filesystem, dst_path=".")
```

**Comment by lurch** [comment]
>  Is there a way to do this without `getsyspath`?

IMHO it's always easiest to "stay inside" the PyFilesystem world as much as possible, and only use `getsyspath` as an "escape hatch" back to native paths when you *have* to deal with libraries outside of PyFilesystem.

**Comment by althonos** [comment]
For outside libraries, it's much better if they have a way to work with file-like objects rather with paths - in general, it makes the API less restrictive, and with PyFilesystem in particular it allows to use even virtual file systems and just have to use the `open` method.
