### ISSUE TITLE
[TarFS] Consider separating out getinfo_from_member(member)

### ISSUE THREAD

**Issue by jdonnerstag** [PyFilesystem/pyfilesystem2#57]
Hi,

In my use case I have 2 requirements:
- walk a tree where *.tar.gz, *.zip and possibly others are treated like directories
- open possibly large tar-files in streaming mode="r|*" and avoid jumping backwards and forwards within that file. This requirement is also the reason why my walker must return a file descriptor (fd) and ResourceInfo

I've implemented a walker that makes heavy use of yours and transparently handles the container files (*.tar.*) when such a file is found. It yields the fd and ResourceInfo exactly as wanted. Except that I had to copy a piece of your code from tarfs.py to create the Info object for tar file entries. Remember I'm opening the tar file myself and I'm (sequentially) iterating through it myself. Yet I still want to consistently return an Info object.

I called my new function getinfo_from_member(member) which is more or less a copy of the 2nd half of getinfo(). Remember that I'm not able to use the tarfs.getinfo() implementation because it "seeks" the information in the tar file, which I'm not able (don't want) to do in streaming mode.

It would be great if I didn't have to copy the source code but call a tarfs method instead. Do think you could separate it out?

thanks a lot
Juergen

**Comment by willmcgugan** [comment]
> It would be great if I didn't have to copy the source code but call a tarfs method instead. Do think you could separate it out?

Seems like a reasonable request. I'd accept a PR, but @althonos is the original author of TarFS and he might want to comment...

**Comment by althonos** [comment]
Thanks @willmcgugan ! Yes I have no objection about that. Only question is whether this method should be advertised as public (and maintained as such) or private (and this will be our little secret 😄 ).

@jdonnerstag : tell me if you need help on the PR !

**Comment by willmcgugan** [comment]
I'd probably go for a public method if another project depended on it.

@jdonnerstag I'm tidying up issues. Did you want to submit a PR for this?
