### ISSUE TITLE
Feature request: Add an option to mount a memory fs to the OS filesystem

### ISSUE THREAD

**Issue by embeddedpenguin** [PyFilesystem/pyfilesystem2#578]
The problem I'm trying to solve is this: I am trying to add a dry-run option to a program that git clones a couple repos and modifies them. To add a dry-run option, I need to simulate a fs or mock the fs calls. The best approach to this, in my opinion, is to make a virtual fs in ram and perform options there, leaving the original fs untouched. I tried doing this using pyfilesystem2's memory fs, but there seems to be no way to mount this to the host OS. I then tried using an OSFS, but it seems like all of those changes are persistent on disk. I did eventually get this working using a tmpfs, but it's still not ideal because it side skirts the simulating at the desired location, meaning any permissions/ownership issues wouldn't be seen from a dry-run.

It seems like pyfilesystem2 is the best library capable of solving this issue, but I'm struggling to figure out how to get pyfilesystem2 to do it. The only way I could really think of to do this is by adding an option to mount a memory fs to the OS's filesystem. If this feature can't be added, any advice on using pyfilesystem to solve this issue would be greatly appreciated

**Comment by dargueta** [comment]
If I understand this correctly, you want a memfs held in your program's memory to be accessible to other programs via the OS file system?

Operating systems specifically guard against this kind of thing for security reasons, but it is possible to get around using [FUSE](https://www.kernel.org/doc/html/latest/filesystems/fuse.html). There's [a Python binding](https://pypi.org/project/fuse-python/) for the library, so to pull this off you'll have to write a sort of compatibility layer between PyFilesystem and your program to do this.

The simplest route would be to use tmpfs. If it's really necessary you can try using [shutil](https://docs.python.org/3/library/shutil.html) to copy over  ownership and permissions flags from the source tree.

**Comment by embeddedpenguin** [comment]
If I tried to integrate fuse with pyfilesystem specifically to mount pyfs mem filesystems, would you be open to accepting a pr?

**Comment by dargueta** [comment]
I have no authority -- I've just merged a couple PRs and lurk around here, so that's more of a question for someone like @althonos.

My _personal_ feeling is that because FUSE doesn't work on Windows, support should be made available as a separate plugin (like [`fs-s3fs`](https://pypi.org/project/fs-s3fs/) or [`fs.archive`](https://pypi.org/project/fs.archive/)). There's documentation on how to do that [here](https://docs.pyfilesystem.org/en/latest/implementers.html).

**Comment by lurch** [comment]
FUSE _was_ supported in the earlier (no longer maintained) [pyfilesystem1](https://github.com/PyFilesystem/pyfilesystem) (see https://pyfilesystem.readthedocs.io/en/latest/expose.html ), but @willmcgugan didn't have the time (nor did anybody else) to port that over to pyfilesystem2 (see e.g. #274 and #567 ).
