### ISSUE TITLE
S3?

### ISSUE THREAD

**Issue by kgk** [PyFilesystem/pyfilesystem2#58]
I note that pffilesystem had an S3 driver.  any reason why it disappeared?

**Comment by althonos** [comment]
Pyfilesystem2 is a whole new codebase, so the S3 driver was not implemented in this new version yet.

**Comment by willmcgugan** [comment]
I have plans to write a S3 driver. Not sure when I'll get to it.

**Comment by willmcgugan** [comment]
https://github.com/pyfilesystem/s3fs
