### ISSUE TITLE
open_fs does not support fs parameter

### ISSUE THREAD

**Issue by jdonnerstag** [PyFilesystem/pyfilesystem2#63]
Hi, 

let's assume I have done `fs_1 = open_fs("/some/direc")` and I need a new fs derived from fs_1, then I'm not easily able to do it. E.g. `fs_2 = fs_1.open_fs("proj_dir")` or `fs_2 = open_fs("proj_dir", fs=fs_1)` doesn't seem to be supported. Instead I have to do `fs_2 = open_fs(path.join(fs_1.root_dir, "proj_dir"))`. Unfortunately though it is not a generic solution. E.g. if fs_1 is a TarFS or ZipFS it won't work anymore. In fact I even failed to find a workaround. Example:

    fs_1 = open_fs("tarfs://mydir/myfile.tar.gz")
    fs_2 = fs_1.open_fs("/direc/")
    fd = fs_2.open("myfile.csv") // or fs_2.walk()

Is that correct or am I missing something?

thanks a lot for your help
Juergen

**Comment by althonos** [comment]
Hi Juergen,

what you are probably looking for is the `opendir`  method. It opens a new `SubFS` using the given directory as its new root.

Then, the following code :
```python
fs1 = fs.open_fs('/some/dir')
fs2 = fs.open_fs('/some/dir/nested')
```
is equivalent to :
```python
fs1 = fs.open_fs('/some/dir')
fs2 = fs1.opendir('/nested')
```

Well, not actually equivalent : the first snippet allows to maintain two indépendent filesystems, whereas in the second, closing `fs1` will make `fs2` unusable. Same thing if you use a network filesystem : first snippet will create two independent connections, the second only one.

**Comment by willmcgugan** [comment]
Hi @jdonnerstag Did @althonos's answer help?

**Comment by jdonnerstag** [comment]
yes, thank you
