### ISSUE TITLE
PyPI has old documentation link

### ISSUE THREAD

**Issue by eswald** [PyFilesystem/pyfilesystem2#7]
The [fs page on PyPI](https://pypi.python.org/pypi/fs/2.0.0) points to [pythonhosted](http://pythonhosted.org/fs/) as the documentation link, which redirects to [the original pyfilesystem documentation](http://docs.pyfilesystem.org/en/latest/getting_started.html).  Probably not a huge deal, but it made me want to double-check which one I would get by pip installing it.

**Comment by willmcgugan** [comment]
Thanks. That should be sorted very soon.

**Comment by willmcgugan** [comment]
docs.pyfilesystem.org should be serving up the fs2 docs now.

**Comment by petmakris** [comment]
Should we consider support for various filesystems (as TahoeLAFS) obsolete?

**Comment by willmcgugan** [comment]
@petmakris Not at all. fs1 isn't going anywhere and will be maintained for a while. For fs2 they would have to be ported.
