### ISSUE TITLE
Add a function to mirror one filesystem directory to one in another filesystem

### ISSUE THREAD

**Issue by rkhwaja** [PyFilesystem/pyfilesystem2#73]
We have copy_dir_if_newer. I would like a similar thing which would also delete objects in the destination that aren't in the source.
My use case is a local backup of dropbox/onedrive etc.

**Comment by willmcgugan** [comment]
Yeah, I can see that being useful. I'll keep this issue open as a reminder.

**Comment by willmcgugan** [comment]
@rkhwaja Mirror functionality is a work in progress, see https://github.com/PyFilesystem/pyfilesystem2/pull/80/files

**Comment by willmcgugan** [comment]
Please try [fs.mirror](https://github.com/PyFilesystem/pyfilesystem2/blob/master/fs/mirror.py) in v2.0.11
