### ISSUE TITLE
when hassyspath() is false, getsyspath() could emulate a path to a file by making a local copy

### ISSUE THREAD

**Issue by notestaff** [PyFilesystem/pyfilesystem2#74]
PyFilelsystem hides many differences between filesystems, but it could hide one more.  For filesystems where hassyspath() is False, getsyspath() could still work by making a local copy of the file and returning a path to that.

**Comment by willmcgugan** [comment]
True, but I think that might be too much magic. There's no telling what  an app would use a syspath for or what assumptions it might make. Then you have the problem that the FS object might not reflect any changes made via the syspath.

I can see that being a useful utility for some use-cases, but too problematic to make part of the library...

**Comment by althonos** [comment]
@notestaff : you could actually create a filesystem wrapper that does what you want if that is an usecase you need :)
