### ISSUE TITLE
test_case_sensitive test fail

### ISSUE THREAD

**Issue by willmcgugan** [PyFilesystem/pyfilesystem2#76]
```
======================================================================
ERROR: test_case_sensitive (tests.test_ftpfs.TestFTPFS)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/will/projects/pyfilesystem2/fs/test.py", line 1755, in test_case_sensitive
    self.fs.makedir('Foo')
  File "/Users/will/projects/pyfilesystem2/fs/ftpfs.py", line 540, in makedir
    raise errors.DirectoryExists(path)
DirectoryExists: directory 'Foo' exists
```

This is occurring on OSX which has case insensitive paths. FTPFS meta has `"case_insensitive" : False`.

I don't know of an easy way to detect the case sensitivity of an ftp server. AFAICT its not exposed.

@althonos any suggestions?

**Comment by willmcgugan** [comment]
Turns out there is no practical way to know if a FTP server has case sensitive or insensitive paths. It depends on the filesystem the server is running on. So there is now way to reliably set the `"case_insenstive"` switch in meta.

Best solution I can think of was to just remove that flag from the ftp meta. This required a clarification in the docs that the keys aren't guaranteed to be present.

**Comment by althonos** [comment]
I think that's the best way to proceed as well. Clients should assume the server is case insensitive by default.
