### ISSUE TITLE
Special chars in connection strings cause issues

### ISSUE THREAD

**Issue by caesarshift** [PyFilesystem/pyfilesystem2#78]
I stumbled across this when using a password with an @ sign in it with fs.smbfs.

The easy (short-sighted?) fix for this specific issue is to make the regex match greedy.

See commit here:

https://github.com/caesarshift/pyfilesystem2/commit/56b0a82a41e5f447c3bdcbc563e007d6f47339e2

However, I'm just now learning pyfilesystem2, so I don't know all the different string patterns that you allow for input. I don't believe the change from non-greedy to greedy will break any existing patterns, but I can't be 100% sure.

Additionally, the question then becomes, what if you want a ':' in the password? The partition method a few lines later would cause that to fail.

So maybe my commit is to short-sighted, and it is just better to support the RFC 3986 which says that special characters should be url encoded?

https://stackoverflow.com/questions/6718471/escaping-username-characters-in-basic-auth-urls
http://www.faqs.org/rfcs/rfc3986.html

Thoughts welcome. I'm willing to submit a pull request with either (allow @ in password OR url decode username/password).

**Comment by willmcgugan** [comment]
Something similar [came up recently](https://github.com/PyFilesystem/pyfilesystem2/pull/72). I'm not keen on the greedy regex, I suspect that might backfire at some point. So the url encoding is probably the way to go.

I'm working in that area at the moment. So I can add the username / password encoding.

**Comment by willmcgugan** [comment]
[Work in progress](https://github.com/PyFilesystem/pyfilesystem2/pull/75)

**Comment by caesarshift** [comment]
Sounds good. I'm sure you've thought of this, but it's a potentially backwards incompatible change if someone just happens to have a password that looks like a url encoded string.

**Comment by willmcgugan** [comment]
Good point.

**Comment by willmcgugan** [comment]
username and password support percent encoding in v2.0.10, and some other changes to FS URLs...

https://docs.pyfilesystem.org/en/latest/openers.html
