### ISSUE TITLE
Caching functionality - is it planned to implement?

### ISSUE THREAD

**Issue by fresheed** [PyFilesystem/pyfilesystem2#81]
For my project it would be useful to cache large files. Are there any plans to implement it? For simplest variant, one could simply override openbin call to store files somewhere.
Also, looking at pyfilesystem (first version) I see classes such as CacheFS. It allows to cache metadata without actual file contents. Was it removed for some purpose or it's just not yet ported?

**Comment by althonos** [comment]
The closest thing to `CacheFS` is actually [`fs.wrap.WrapCachedDir`](http://pyfilesystem2.readthedocs.io/en/latest/reference/wrap.html#fs.wrap.WrapCachedDir) in the second version.

**Comment by willmcgugan** [comment]
Yeah, it would work like this, typically:

```python
from fs.wrap import cache_directory
cached_fs = cache_directory(my_fs)
```

Unfortunately its not quite equivalent to CacheFS. It won't refresh the cache if anything is modified. Probably worth some work on that...

**Comment by Ryanb58** [comment]
Another option would be to wrap the open method in a `memorize` function/decorator. That way caching doesn't impact other pyfilesystem users. Then you would be able to set the thresholds and such specific to your applications needs.

**Comment by willmcgugan** [comment]
Going to close this one. Some kind of data caching filesystem might be a nice addition, but there doesn't appear to be the motivation to implement it. As always, PRs welcome!

**Comment by adyanth** [comment]
Any updates on this? Any way to cache files from remote file systems like google drive, instead of making an expensive API call every time for small items?

**Comment by willmcgugan** [comment]
@adyanth It's possible, but such a cache hasn't been implemented. If it's commercial, I am available for freelance work.

**Comment by adyanth** [comment]
No, just a hobby project of mine. 
Can you point me towards any suitable modules for the same?

**Comment by willmcgugan** [comment]
I don't know of anything with similar features of PyFilesystem, but if you wanted to tackle it yourself, I'd start with a WrapFS (https://docs.pyfilesystem.org/en/latest/reference/wrapfs.html). Which lets you take an existing filesystem and add features to it.

**Comment by adyanth** [comment]
Oh cool, I will have a look.
CacheFS seems to be written using WrapFS, but not exactly written for remote file systems, I think.
Maybe fs.remote is something that might work.
Thanks!
