### ISSUE TITLE
Error when Server (proxy) does not support "FEAT"-command

### ISSUE THREAD

**Issue by muffl0n** [PyFilesystem/pyfilesystem2#82]
Based on the new version 2.0.11 I did a quick patching of the fs.opener.ftpfs.FTPOpener#open_fs method to use our proxy if specified:
```
        if parse_result.params['proxy']:
            username = '{}@{}'.format(parse_result.username, ftp_host)
            ftp_host = parse_result.params['proxy']
        else:
            username = parse_result.username
        ftp_fs = FTPFS(
            ftp_host,
            port=ftp_port,
            user=username,
            passwd=parse_result.password,
        )
```

Unfortunately our proxy does not support the "FEAT"-Command and so I'm getting this error message:
```
Traceback (most recent call last):
  File "/foo/venv/lib64/python3.4/site-packages/fs/ftpfs.py", line 42, in ftp_errors
    yield
  File "/foo/venv/lib64/python3.4/site-packages/fs/ftpfs.py", line 372, in _read_dir
    self.ftp.retrlines(
  File "/foo/venv/lib64/python3.4/site-packages/fs/ftpfs.py", line 346, in ftp
    encoding = 'utf-8' if 'UTF8' in _ftp.sendcmd('FEAT') else 'latin-1'
  File "/usr/lib64/python3.4/ftplib.py", line 272, in sendcmd
    return self.getresp()
  File "/usr/lib64/python3.4/ftplib.py", line 245, in getresp
    raise error_perm(resp)
ftplib.error_perm: 500 'FEAT': command unrecognized.
```
For comparison, this is the output of lftp for the same connection:
```
-> % lftp user@ftp.example.org@proxy
Password: 
lftp user@ftp.example.org@proxy:~> debug
lftp user@ftp.example.org@proxy:~> ls
---- Connecting to proxy (x.x.x.x) port 21
<--- 220 proxy FTP server (Version x.x.x.x) ready.
---> FEAT
<--- 500 'FEAT': command unrecognized.
---> AUTH TLS
<--- 500 'AUTH': command unrecognized.
---> USER user@ftp.example.org
<--- 331 (not authenticated): Enter server password
---> PASS XXXX
...
```
See #72

I would expect PyFilesystem to not fail if "FEAT" is not supported.

**Comment by willmcgugan** [comment]
Looks like an easy fix.

**Comment by willmcgugan** [comment]
Surprised your proxy doesn't proxy the FEAT. That particular error means that FTPFS won't be able to detect the encoding, and will default to latin-1.

**Comment by willmcgugan** [comment]
Please give v2.0.12a0 (on PyPi) a try.

**Comment by muffl0n** [comment]
Looks promising! Thanks for the quick fix, will give it a try when I'm back at the office next week.

**Comment by muffl0n** [comment]
> surprised your proxy doesn't proxy the FEAT.
It can't because the "FEAT" is issued before the login. So the proxy does not have a connection to the target server and cannot proxy anything yet.

Your fix seems to work, though I'm getting an empty directory listing when connecting to my test-server. An anonymous connection to ftp.ubuntu.com on the other hand works flawelessly.

I'm tried to debug what's going on here but unfortunately had no luck so far.

**Comment by muffl0n** [comment]
> though I'm getting an empty directory listing when connecting to my test-server.

I was just to blind, sorry. Everything works as expected now. Though I'm pretty sure that my code for using the proxy (from the starting post) could be a bit cleaner.

**Comment by willmcgugan** [comment]
> It can't because the "FEAT" is issued before the login. So the proxy does not have a connection to the target server and cannot proxy anything yet.

Ah. Had a quick look at the code and I can't see how that would be the case for FTPFS. If it is that might be fixable. Without it, FTPFS will not be able to deal with utf-8 encoding.

**Comment by muffl0n** [comment]
I was hoping I could test that somehow but I have no FTP Server available that uses UTF-8. If you could help me out with a test account somewhere I could run a few tests.

**Comment by willmcgugan** [comment]
I think [pyftpdlib](https://github.com/giampaolo/pyftpdlib) supports utf-8 paths. It was @althonos who added the utf-8 support, he may have more input on this.

**Comment by muffl0n** [comment]
You were right, directories/files with UTF-8 names are broken and I have no idea how to fix this. Only idea I have is to do a second "FEAT" after logging in. But this might not be the most elegant solution.

As seen in #84, a failing "FEAT" command also results in a fallback to "plain old directory listings" instead of MLST.

**Comment by althonos** [comment]
Yes @willmcgugan, `pyftpdlib` supports utf-8 paths as long as your underlying filesystem does, that's how I could test UTF-8 path on my Linux machine, using `pyftpdlib.test.ThreadedTestFTP`.

**Comment by willmcgugan** [comment]
@muffl0n @althonos I suspect there is a better way of handling the features issue. I'm going to look in to that. Hopefully I won't end up re-writing ftplib.

I'll close this issue for now, and add a more specific issue to keep track.

**Comment by willmcgugan** [comment]
https://github.com/PyFilesystem/pyfilesystem2/issues/90
