### ISSUE TITLE
[FS] appendbytes should raise TypeError

### ISSUE THREAD

**Issue by althonos** [PyFilesystem/pyfilesystem2#83]
Hi there,
while rewriting the documentation, I realised that `FS.appendbytes` raises `ValueError`, but shouldn't: according to doc of `ValueError` and `TypeError`, `ValueError` should be raised when given *Inappropriate argument value (of correct type)*, while `TypeError` should be raised when given *Inappropriate argument type*.

Since the exception is raised when `FS.appendbytes(path, data)` is called with `data` not being a `bytes` instance, the exception should definitely be a `TypeError`.

**NB**: same goes for `appendtext`, `setbytes` and `settext`.

**Comment by willmcgugan** [comment]
Thanks. Should be fixed in master.
