### ISSUE TITLE
Add fs.dropboxfs to the index of filesystems

### ISSUE THREAD

**Issue by rkhwaja** [PyFilesystem/pyfilesystem2#87]
The PYPI name is fs.dropboxfs. The github/homepage is at https://github.com/rkhwaja/fs.dropboxfs

**Comment by willmcgugan** [comment]
Done. https://www.pyfilesystem.org/page/index-of-filesystems/

**Comment by althonos** [comment]
@rkhwaja : Don't hesitate to tag me if you need any help, in particular regarding extensions. And don't forget to add tests to make sure your FS is compliant ! 😉
