### ISSUE TITLE
open() fails when openbin() returns an requests stream

### ISSUE THREAD

**Issue by nuschk** [PyFilesystem/pyfilesystem2#9]
I'm unsure whether this is really a bug, maybe I'm just using it wrong.

But, when my file system's openbin() returns an http stream buffer, fs somehow calls flush() one time too many. Here's a stripped down example which only uses the relevant code from within the library (my use case is just `fs.open(..., 'rt')`, but it really boils down to this).

```
import requests
import fs.iotools
url = 'http://www.textfiles.com/hacking/saruman.add'
res = requests.get(url, stream=True)
with fs.iotools.make_stream("foo", bin_file=res.raw, encoding='latin-1') as f:
    final = f.read()
```

Here's the stacktrace:

```
ValueError                                Traceback (most recent call last)
<ipython-input-9-9842bf2256ce> in <module>()
      1 res = requests.get(url, stream=True)
      2 with fs.iotools.make_stream("foo", bin_file=res.raw, encoding="latin-1") as f:
----> 3     final = f.read()

/Users/bernhard/Projects/flatfox-website/env/lib/python3.5/site-packages/fs/iotools.py in flush(self)
     26
     27     def flush(self):
---> 28         return self._f.flush()
     29
     30     def isatty(self):

/Users/bernhard/Projects/flatfox-website/env/lib/python3.5/site-packages/requests/packages/urllib3/response.py in flush(self)
    426     def flush(self):
    427         if self._fp is not None and hasattr(self._fp, 'flush'):
--> 428             return self._fp.flush()
    429
    430     def readable(self):

/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py in flush(self)
    416
    417     def flush(self):
--> 418         super().flush()
    419         if self.fp:
    420             self.fp.flush()

ValueError: I/O operation on closed file.
```

BTW, thanks for the good work on this library!

**Comment by willmcgugan** [comment]
Thanks for the traceback.

I did some digging and it looks like the file-like object returned by requests closes the stream after a call to `read()`, which regular file objects don't do. I haven't quite managed to figure out why flush is called after the read.

Not sure yet what the best thing to do here is. You may find that you can't use `res.raw` directly, and you may have to provide some kind of wrapper that simulates the typical behavior. To simulate a regular file you will need to add support for seeking and writing etc. So the wrapper may be unavoidable. An alternative may be to copy the data to a temporary file and return that from openbin.

Open to suggestions / PRs to make that process easier...

**Comment by nuschk** [comment]
Thank you for the digging. I don't have a clue why flush is called either (I'm far from an expert in python streams though), and don't see a way of easily fixing it from within pyfs. 

From my code, though, it's easy. I just use `openbin()` and decode the content manually. I don't even need to write a wrapper.

So, as my use-case is certainly a bit of an edge-case (BrickFTP API access, if you're wondering), I now close the issue. If it ever pops up again in another context, I would gladly shelve out a few hours and try and make a PR if possible.
