### ISSUE TITLE
Some `validatepath` methods return None

### ISSUE THREAD

**Issue by althonos** [PyFilesystem/pyfilesystem2#92]
Hi Will, I saw that while improving the doc but didn't want to fix it in the same PR: some filesystems have a `validatepath` method that does not return a path, namely:

* `WrapFS` and `SubFS`
* `MultiFS`

It may be a good idea to add a test to make sure filesystems do conform as well.

**Comment by willmcgugan** [comment]
Good spot. MountFS was also returning the wrong thing. It returned a path from the mounted filesystem. Should be fixed with https://github.com/PyFilesystem/pyfilesystem2/commit/ea670519f99d58ef0d47ebded1772c67d8686ac4
