### ISSUE TITLE
scandir crash on permission denied

### ISSUE THREAD

**Issue by ReimarBauer** [PyFilesystem/pyfilesystem2#94]
fs/osfs.py", line 404, in _scandir
    for dir_entry in scandir(sys_path):
fs.errors.PermissionDenied: permission denied

Can that entry just become ignored ?

**Comment by ReimarBauer** [comment]
Hmm, this seems some other problem, the files are readable.

**Comment by willmcgugan** [comment]
Do you have `x` set on the directory?

OSFS will relay any errors it receives from the OS. If you get the same behaviour with os.listdir then the issue is not related to OSFS.

**Comment by ReimarBauer** [comment]
Hmm, yep, but if I set `ignore_errors=True`, shouldn't that error still happen?
The directory where it fails can be scanned using that path.

Is there a limit how much files/dirs can be scanned?

**Comment by willmcgugan** [comment]
The only `ignore_errors` parameter I know of is in walk.py. Is this error happening in a walk call?

Please give me more information so I can diagnose this. A short but working piece of code, and the full exception you get when you run it.

**Comment by ReimarBauer** [comment]
I started to write a QT Gui based on fs. It is in early state. 
https://github.com/ReimarBauer/fs_filepicker/blob/master/fslib/fs_filepicker.py#L53

There seems not an issue with os.listdir. Also the subdir works.

**Comment by willmcgugan** [comment]
That's a nice idea for a project.

If walk is throwing an exception when `ignore_errors` is True then that would indicated a bug. I'll need your figuring it out. Like a short simple example of code I can run myself (pasted here), and perhaps a listing of the directory it failed at.

Also, please ensure you are running the latest code.

**Comment by ReimarBauer** [comment]
You are fast :) Have to make an update on conda-forge, we have there 2.0.11. I am currently waiting for my 0.0.3 build there. 

I have no idea yet why it fails on that directory.

**Comment by ReimarBauer** [comment]
Found the cause,
I have a directory which is owned by root and I have no rights on that.

drwx------  3 root   root       4096 Jan  3  2017 .somedir

The origin `scandir `ignores it but, `_scandir` strumbles.

**Comment by willmcgugan** [comment]
Thanks, I'll look in to that.

**Comment by willmcgugan** [comment]
Fixed an issue in walk.py that may have affected you. Please give v2.0.13 a try.

**Comment by ReimarBauer** [comment]
issue solved
