### ISSUE TITLE
rename filter to fs_filter

### ISSUE THREAD

**Issue by ReimarBauer** [PyFilesystem/pyfilesystem2#96]
Hi 
currently the builtin *filter* becomes overwritten.
Can we rename it to fs_filter?

help(filter)

Help on built-in function filter in module __builtin__:

filter(...)
    filter(function or None, sequence) -> list, tuple, or string
    
    Return those items of sequence for which function(item) is true.  If
    function is None, return the items that are true.  If sequence is a tuple
    or string, return the same type, else return a list.

**Comment by willmcgugan** [comment]
I don't see anywhere that `filter` is defined in the module scope. Can you give me some code that demonstrates this issue?

**Comment by ReimarBauer** [comment]
I thought on this.

```
from fs import open_fs


def example(filter=[u'*.py']):
    help(filter)
    home_fs = open_fs('~/projects')
    for path in home_fs.walk.files(filter=['*.py']):
        print(path)

if __name__ == '__main__':
    example()
```

**Comment by althonos** [comment]
In this case this is only name shadowing, singe outsider of the `exemple` fonction `filter` still is the builtin function.

Since `fs.walk.files` does not use the filter function, this is no issue in the library.
